### ISSUE TITLE
gym.wrappers.Monitor does not record the correct video on mujoco locomotion environments

### ISSUE THREAD

**Issue by zihualiu** [openai/gym#1050]
`gym.wrappers.Monitor` returns an image of 500x500 section of the screen instead of a full recording of the agent. This problem is only applicable to mujoco environments such as HalfCheetah-v2, Hopper-v2 and is fine for many Atari environments. This problem is also replicable on mac and Ubuntu 16.04. 

Minimally reproducible code:
```
import gym
from gym.wrappers import Monitor
env = gym.make('HalfCheetah-v2')
env = Monitor(env, './video')
env.reset()
while True:
	env.render()
	obs, r, done, info = env.step([0,0,0,0,0,0])
	if done: break
```

**Comment by hzyjerry** [comment]
I have the same issue

**Comment by matthiasplappert** [comment]
Can you re-try this with the lastest version on master? We have just merged a fix for Mujoco rendering that should hopefully help here.

**Comment by sharma-arjun** [comment]
I just pulled in the latest master and built it, but it is still not fixed.

**Comment by christopherhesse** [comment]
I can't reproduce this issue anymore, is anyone still able to reproduce it?

**Comment by anandtrex** [comment]
I still have the problem.
I get this particular warning:
```
/home/anand/.virtualenvs/rl-online/lib/python3.5/site-packages/gym/logger.py:30: UserWarning: WARN: Tried to pass invalid video frame, marking as broken: Your frame has shape (0, 0, 3), but the VideoRecorder is configured for shape (400, 600, 3).
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
```

**Comment by jaekyeom** [comment]
I haven't tried reproducing this issue, but these might be related: #953 #1182

**Comment by Rowing0914** [comment]
I am having the same issue.

```
/usr/local/bin/python3.6 /home/username/Desktop/research/TF_RL/test/MuJoCo/mujoco_recording_test.py
Found 1 GPUs for rendering. Using device 0.
Traceback (most recent call last):
  File "/home/noio0925/Desktop/research/TF_RL/test/MuJoCo/mujoco_recording_test.py", line 5, in <module>
    env.reset()
  File "/usr/local/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 39, in reset
    self._after_reset(observation)
  File "/usr/local/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 188, in _after_reset
    self.reset_video_recorder()
  File "/usr/local/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 209, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/usr/local/lib/python3.6/site-packages/gym/wrappers/monitoring/video_recorder.py", line 101, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/local/lib/python3.6/site-packages/gym/core.py", line 233, in render
    return self.env.render(mode, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 134, in render
    self._get_viewer(mode).render(width, height, camera_id=camera_id)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 161, in _get_viewer
    self.viewer = mujoco_py.MjRenderContextOffscreen(self.sim, -1)
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

Process finished with exit code 1
```
