### ISSUE TITLE
Error when importing gym in python 3

### ISSUE THREAD

**Issue by husky-prophet** [openai/gym#1057]
I'm getting an error when I try to import gym, is it an error on my end or in the code? I'm running Ubuntu 18.04 LTS, and using python 3.6.5. Here is the error when I run `import gym`:
```>>> import gym
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/finlay/.local/lib/python3.6/site-packages/gym/__init__.py", line 50, in <module>
    from gym.scoreboard.api import upload
  File "/home/finlay/.local/lib/python3.6/site-packages/gym/scoreboard/api.py", line 7, in <module>
    from gym import benchmark_spec, error, monitoring
  File "/home/finlay/.local/lib/python3.6/site-packages/gym/monitoring/__init__.py", line 3, in <module>
    from gym.wrappers.monitoring import load_results, detect_training_manifests, load_env_info_from_manifests, _open_monitors
  File "/home/finlay/.local/lib/python3.6/site-packages/gym/wrappers/__init__.py", line 3, in <module>
    from gym.wrappers.monitoring import Monitor
ImportError: cannot import name 'Monitor'

```

Any help is appreciated

**Comment by Piyushrai558** [comment]
use pip uninstall and reinstall the package

**Comment by christopherhesse** [comment]
Thanks for answering @Piyushrai558!
