### ISSUE TITLE
Error installing gym

### ISSUE THREAD

**Issue by HamKenza** [openai/gym#1086]
I tried to install gym on a server 'pip install gym' but I get the following error:

Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build Box2D-kengz atari-py
Installing collected packages: pyglet, chardet, urllib3, idna, requests, PyOpenGL, imageio, glfw, pycparser, cffi, Cython, mujoco-py, Box2D-kengz, atari-py, gym

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 28] No space left on device

**Comment by leonardoaraujosantos** [comment]
Hi @HamKenza, sorry for the lame answer but IMHO the issue seems disk space (check the last message)
```IOError: [Errno 28] No space left on device```

**Comment by christopherhesse** [comment]
You should free up some disk space, thanks for answering @leonardoaraujosantos
