### ISSUE TITLE
Error Installing Atari with Py2.7

### ISSUE THREAD

**Issue by rcontesti** [openai/gym#1095]
Hi I have been following all the instructions, first installing all the required packages but I can't still install some of the libraries like atari on py2.7. Below is the error as well as the yaml I'm using.
Thank you

`(gym_ai) rcontesti@rcontesti-NUC7i7BNH ~/Documents/gym_ai/gym $ pip install -e .[atari]
Obtaining file:///home/rcontesti/Documents/gym_ai/gym
Requirement already satisfied: numpy>=1.10.4 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from gym==0.10.5) (1.14.5)
Requirement already satisfied: requests>=2.0 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from gym==0.10.5) (2.19.1)
Requirement already satisfied: six in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from gym==0.10.5) (1.11.0)
Requirement already satisfied: pyglet>=1.2.0 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from gym==0.10.5) (1.3.2)
Collecting atari_py>=0.1.1 (from gym==0.10.5)
  Using cached https://files.pythonhosted.org/packages/8b/38/3c6716ac9031a686cc3228f3855e48c08a40e4d7c490dd4c21c65b465205/atari-py-0.1.1.tar.gz
Collecting Pillow (from gym==0.10.5)
  Using cached https://files.pythonhosted.org/packages/6e/27/709a8493071ec649a56d5a3194f648ec7cd792189e994bbd2ef5d285670d/Pillow-5.2.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting PyOpenGL (from gym==0.10.5)
Requirement already satisfied: idna<2.8,>=2.5 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from requests>=2.0->gym==0.10.5) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from requests>=2.0->gym==0.10.5) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from requests>=2.0->gym==0.10.5) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from requests>=2.0->gym==0.10.5) (2018.4.16)
Requirement already satisfied: future in /home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages (from pyglet>=1.2.0->gym==0.10.5) (0.16.0)
Building wheels for collected packages: atari-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command /home/rcontesti/anaconda3/envs/gym_ai/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6YlTSK/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-WUTDcU --python-tag cp27:
  running bdist_wheel
  running build
  make: Entering directory '/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is unknown
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_CXX_COMPILER could be found.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
  Makefile:4: recipe for target 'build' failed
  make: *** [build] Error 1
  make: Leaving directory '/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface'
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6YlTSK/atari-py/setup.py", line 36, in <module>
      tests_require=['nose2']
    File "/home/rcontesti/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6YlTSK/atari-py/setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2
  
  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py, Pillow, PyOpenGL, gym
  Running setup.py install for atari-py ... error
    Complete output from command /home/rcontesti/anaconda3/envs/gym_ai/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6YlTSK/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2yU0ug/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make: Entering directory '/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:2 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
    Makefile:4: recipe for target 'build' failed
    make: *** [build] Error 1
    make: Leaving directory '/tmp/pip-install-6YlTSK/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6YlTSK/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/home/rcontesti/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/rcontesti/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6YlTSK/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/home/rcontesti/anaconda3/envs/gym_ai/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/home/rcontesti/anaconda3/envs/gym_ai/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6YlTSK/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2yU0ug/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6YlTSK/atari-py/
`

Here is also my yaml:
`name: gym_ai
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py27_1
  - anaconda-client=1.6.14=py27_0
  - asn1crypto=0.24.0=py27_0
  - backports=1.0=py27h63c9359_1
  - backports.shutil_get_terminal_size=1.0.0=py27h5bc021e_2
  - backports_abc=0.5=py27h7b3c97b_0
  - blas=1.0=mkl
  - bleach=2.1.3=py27_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py27_0
  - cffi=1.11.5=py27h9745a5d_0
  - chardet=3.0.4=py27hfa10054_1
  - clyent=1.2.2=py27h7276e6c_1
  - cmake=3.11.1=h307fef2_1
  - configparser=3.5.0=py27h5117587_0
  - cryptography=2.2.2=py27h14c3975_0
  - cython=0.28.3=py27h14c3975_0
  - decorator=4.3.0=py27_0
  - entrypoints=0.2.3=py27h502b47d_2
  - enum34=1.1.6=py27h99a27e9_1
  - expat=2.2.5=he0dffb1_0
  - functools32=3.2.3.2=py27h4ead58f_1
  - futures=3.2.0=py27h7b459c0_0
  - gmp=6.1.2=h6c8ec71_1
  - html5lib=1.0.1=py27h5233db4_0
  - idna=2.7=py27_0
  - intel-openmp=2018.0.3=0
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.8.2=py27_0
  - ipython=5.7.0=py27_0
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - ipywidgets=7.2.1=py27_0
  - jinja2=2.10=py27h4114e70_0
  - jsonschema=2.6.0=py27h7ed5aa4_0
  - jupyter_client=5.2.3=py27_0
  - jupyter_core=4.4.0=py27h345911c_0
  - libcurl=7.60.0=h1ad7b7a_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - markupsafe=1.0=py27h97b2822_1
  - mistune=0.8.3=py27h14c3975_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.1=py27h3010b51_0
  - mkl_random=1.0.1=py27h629b387_0
  - nb_anacondacloud=1.4.0=py27_0
  - nb_conda=2.2.1=py27hec22543_0
  - nb_conda_kernels=2.1.0=py27_0
  - nbconvert=5.3.1=py27he041f76_0
  - nbformat=4.4.0=py27hed7f2b2_0
  - nbpresent=3.0.2=py27hcce4ef4_1
  - ncurses=6.1=hf484d3e_0
  - notebook=5.5.0=py27_0
  - numpy=1.14.5=py27hcd700cb_3
  - numpy-base=1.14.5=py27hdbf6ddf_3
  - openssl=1.0.2o=h20670df_0
  - pandas=0.23.1=py27h637b7d7_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py27h428e1e5_1
  - pathlib2=2.3.2=py27_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.4=py27h09770e1_0
  - pip=10.0.1=py27_0
  - prompt_toolkit=1.0.15=py27h1b593e1_0
  - ptyprocess=0.6.0=py27_0
  - pycparser=2.18=py27hefa08c5_1
  - pygments=2.2.0=py27h4a8b6f5_0
  - pyopenssl=18.0.0=py27_0
  - pysocks=1.6.8=py27_0
  - python=2.7.15=h1571d57_0
  - python-dateutil=2.7.3=py27_0
  - pytz=2018.5=py27_0
  - pyyaml=3.12=py27h2d70dd7_1
  - pyzmq=17.0.0=py27h14c3975_1
  - readline=7.0=ha6073c6_4
  - requests=2.19.1=py27_0
  - scandir=1.7=py27h14c3975_0
  - send2trash=1.5.0=py27_0
  - setuptools=39.2.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - six=1.11.0=py27h5f960f1_1
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py27_1
  - testpath=0.3.1=py27hc38d2c4_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py27_0
  - traitlets=4.3.2=py27hd6ce930_0
  - urllib3=1.23=py27_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - webencodings=0.5.1=py27hff10b21_1
  - wheel=0.31.1=py27_0
  - widgetsnbextension=3.2.1=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - backports.functools-lru-cache==1.5
    - future==0.16.0
    - gym==0.10.5
    - pyglet==1.3.2
    - pyparsing==2.2.0
    - virtualenv==16.0.0
prefix: /home/rcontesti/anaconda3/envs/gym_ai`

**Comment by rcontesti** [comment]
I solve it with:

sudo apt-get install build-essential 
sudo apt-get install g++
