### ISSUE TITLE
python 2.7  stats_recorder.py   TypeError: array([-603.39919478]) is not JSON serializable

### ISSUE THREAD

**Issue by zdx3578** [openai/gym#116]
______________________________________________
[2016-05-23 09:51:19,319] Starting new video recorder writing to /home/ubuntu/work/out/openaigym.video.None.10003.video000000.mp4
Xlib:  extension "RANDR" missing on display ":99".
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[2016-05-23 09:54:02,025] Episode 1 finished after 400 timesteps, reward [-603.39919478]
[2016-05-23 09:54:02,456] Starting new video recorder writing to /home/ubuntu/work/out/openaigym.video.None.10003.video000001.mp4
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
Traceback (most recent call last):
  File "naf.py", line 187, in <module>
    observation = env.reset()
  File "/home/ubuntu/work/gym/gym/core.py", line 113, in reset
    self.monitor._after_reset(observation)
  File "/home/ubuntu/work/gym/gym/monitoring/monitor.py", line 238, in _after_reset
    self.flush()
  File "/home/ubuntu/work/gym/gym/monitoring/monitor.py", line 130, in flush
    self.stats_recorder.flush()
  File "/home/ubuntu/work/gym/gym/monitoring/stats_recorder.py", line 72, in flush
    }, f)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([-603.39919478]) is not JSON serializable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ubuntu/work/gym/gym/utils/atexit_utils.py", line 44, in close_envs_and_monitors
    monitor_closer.close()
  File "/home/ubuntu/work/gym/gym/utils/atexit_utils.py", line 36, in close
    obj.close()
  File "/home/ubuntu/work/gym/gym/monitoring/monitor.py", line 152, in close
    self.stats_recorder.close()
  File "/home/ubuntu/work/gym/gym/monitoring/stats_recorder.py", line 59, in close
    self.flush()
  File "/home/ubuntu/work/gym/gym/monitoring/stats_recorder.py", line 72, in flush
    }, f)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([-603.39919478]) is not JSON serializable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ubuntu/work/gym/gym/utils/atexit_utils.py", line 44, in close_envs_and_monitors
    monitor_closer.close()
  File "/home/ubuntu/work/gym/gym/utils/atexit_utils.py", line 36, in close
    obj.close()
  File "/home/ubuntu/work/gym/gym/monitoring/monitor.py", line 152, in close
    self.stats_recorder.close()
  File "/home/ubuntu/work/gym/gym/monitoring/stats_recorder.py", line 59, in close
    self.flush()
  File "/home/ubuntu/work/gym/gym/monitoring/stats_recorder.py", line 72, in flush
    }, f)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([-603.39919478]) is not JSON serializable

**Comment by zdx3578** [comment]
i just str it :  

                'episode_rewards': str(self.episode_rewards),

**Comment by mthrok** [comment]
How about [this](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.tolist.html)?
```python
str(self.episode_rewards.tolist())
```

**Comment by jietang** [comment]
I'm confused about why episode_rewards is a numpy array. Which environment were you testing with wen you encountered this, and are you using the latest master branch?

**Comment by zdx3578** [comment]
HumanoidStandup-v1

**Comment by zdx3578** [comment]
env HumanoidStandup-v1 have a bug; will fix

**Comment by jietang** [comment]
Closing, I think HumanoidStandup-v1 is merged and fixed.
