### ISSUE TITLE
Error in using Baselines algorithm to train HalfCheetah-v2

### ISSUE THREAD

**Issue by huangjiancong1** [openai/gym#1163]
Command:
`python -m baselines.run --alg=ppo2 --env=HalfCheetah-v2 --network=mlp --num_timesteps=2e7 --ent_coef=0.1 --num_hidden=32 --num_layers=3 --value_network=copy --save_path=baselines/baselines/ppo2/halfcheetah/models_2e7`

Error output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/huang/baselines/baselines/run.py", line 234, in <module>
    main()
  File "/home/huang/baselines/baselines/run.py", line 211, in main
    model, env = train(args, extra_args)
  File "/home/huang/baselines/baselines/run.py", line 79, in train
    **alg_kwargs
  File "/home/huang/baselines/baselines/ppo2/ppo2.py", line 245, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/home/huang/baselines/baselines/ppo2/ppo2.py", line 110, in run
    self.obs[:], rewards, self.dones, infos = self.env.step(actions)
  File "/home/huang/baselines/baselines/common/vec_env/__init__.py", line 98, in step
    return self.step_wait()
  File "/home/huang/baselines/baselines/common/vec_env/vec_normalize.py", line 23, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "/home/huang/baselines/baselines/common/vec_env/dummy_vec_env.py", line 40, in step_wait
    obs, self.buf_rews[e], self.buf_dones[e], self.buf_infos[e] = self.envs[e].step(action)
  File "/home/huang/baselines/baselines/bench/monitor.py", line 60, in step
    ob, rew, done, info = self.env.step(action)
  File "/home/huang/gym/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/huang/gym/gym/envs/mujoco/half_cheetah.py", line 12, in step
    self.do_simulation(action, self.frame_skip)
  File "/home/huang/gym/gym/envs/mujoco/mujoco_env.py", line 106, in do_simulation
    self.sim.step()
  File "mujoco_py/mjsim.pyx", line 119, in mujoco_py.cymj.MjSim.step
  File "mujoco_py/cymj.pyx", line 115, in mujoco_py.cymj.wrap_mujoco_warning.__exit__
  File "mujoco_py/cymj.pyx", line 75, in mujoco_py.cymj.c_warning_callback
  File "/home/huang/venv/lib/python3.6/site-packages/mujoco_py/builder.py", line 331, in user_warning_raise_exception
    raise MujocoException('Got MuJoCo Warning: {}'.format(warn))
mujoco_py.builder.MujocoException: Got MuJoCo Warning: Unknown warning type Time = 35.7000.

```

Before it , i choice `--num_timesteps=100000`, It can finish trainning and play.
But, i use `--num_timesteps=2e7` now, It can train at the beginning, and Trackback nearly after 1 hours.

**Comment by pzhokhov** [comment]
I see you have created the same issue in baselines: https://github.com/openai/baselines/issues/587, let's move the discussion there
