### ISSUE TITLE
Can't Install Atari Dependencies on Ubuntu 

### ISSUE THREAD

**Issue by iam-mhaseeb** [openai/gym#1170]
I tried installing OpenGym it via `sudo pip3 install gym` It worked like a charm!
When I tried installing **Atari Dependencies** it didn't worked. 

Here is the complete traceback.

```
Requirement already satisfied: gym[atari] in /usr/local/lib/python3.5/dist-packages (0.10.5)
Requirement already satisfied: numpy>=1.10.4 in /home/haseeb/.local/lib/python3.5/site-packages (from gym[atari]) (1.15.0)
Requirement already satisfied: requests>=2.0 in /home/haseeb/.local/lib/python3.5/site-packages (from gym[atari]) (2.19.1)
Requirement already satisfied: six in /home/haseeb/.local/lib/python3.5/site-packages (from gym[atari]) (1.11.0)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from gym[atari]) (1.3.2)
Collecting atari_py>=0.1.1 (from gym[atari])
  Downloading https://files.pythonhosted.org/packages/8b/38/3c6716ac9031a686cc3228f3855e48c08a40e4d7c490dd4c21c65b465205/atari-py-0.1.1.tar.gz (760kB)
    100% |████████████████████████████████| 768kB 421kB/s 
Requirement already satisfied: Pillow in /home/haseeb/.local/lib/python3.5/site-packages (from gym[atari]) (5.2.0)
Collecting PyOpenGL (from gym[atari])
  Downloading https://files.pythonhosted.org/packages/9c/1d/4544708aaa89f26c97cc09450bb333a23724a320923e74d73e028b3560f9/PyOpenGL-3.1.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 570kB/s 
Requirement already satisfied: idna<2.8,>=2.5 in /home/haseeb/.local/lib/python3.5/site-packages (from requests>=2.0->gym[atari]) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/haseeb/.local/lib/python3.5/site-packages (from requests>=2.0->gym[atari]) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/haseeb/.local/lib/python3.5/site-packages (from requests>=2.0->gym[atari]) (2018.8.24)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/haseeb/.local/lib/python3.5/site-packages (from requests>=2.0->gym[atari]) (1.23)
Requirement already satisfied: future in /usr/local/lib/python3.5/dist-packages (from pyglet>=1.2.0->gym[atari]) (0.16.0)
Installing collected packages: atari-py, PyOpenGL
  Running setup.py install for atari-py ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vipt9kpd/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-aa55xd6k/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make: Entering directory '/tmp/pip-install-vipt9kpd/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    /bin/sh: 1: cmake: not found
    Makefile:4: recipe for target 'build' failed
    make: *** [build] Error 127
    make: Leaving directory '/tmp/pip-install-vipt9kpd/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vipt9kpd/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vipt9kpd/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vipt9kpd/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-aa55xd6k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-vipt9kpd/atari-py/
```

**Comment by pzhokhov** [comment]
Hi @iam-mhaseeb! atari-py requires some system packages and some compilation steps. In particular, from your error trace, it looks like `cmake` is missing; you can install it via `brew install cmake` on osx and `sudo apt-get install cmake` on ubuntu. Please refer to https://github.com/openai/gym#installing-everything section for more info. Closing this for now, please reopen if installing system packages does not help.

**Comment by iam-mhaseeb** [comment]
It worked like a charm!
Thanks a billion.
