### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'Space'

### ISSUE THREAD

**Issue by adil25** [openai/gym#1180]
After installing gym as soon as i ran my code so i got this below error, please for further details observe the below output with error, and please help me out to overcome this error. Thanks everyone in advance.

/home/adil/anaconda3/bin/python "/home/adil/Desktop/POMDP's paper/DRQN_minecraft.py"
/home/adil/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/adil/Desktop/POMDP's paper/DRQN_minecraft.py", line 47, in <module>
    env = gym.envs.make('MinecraftBasic-v0')
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/home/adil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/adil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym_minecraft-0.0.2-py3.6.egg/gym_minecraft/envs/__init__.py", line 1, in <module>
    from gym_minecraft.envs.minecraft_env import *
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym_minecraft-0.0.2-py3.6.egg/gym_minecraft/envs/minecraft_env.py", line 9, in <module>
    from gym import spaces, error
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/spaces/__init__.py", line 1, in <module>
    from gym.spaces.box import Box
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym/spaces/box.py", line 5, in <module>
    class Box(gym.Space):
AttributeError: module 'gym' has no attribute 'Space'

Process finished with exit code 1

**Comment by pzhokhov** [comment]
Hi @adil25! Which version of the gym are you using? (if you have installed it using pip, use `pip freeze | grep gym`) This looks to me like either old version; or some other module with name gym is installed... Actually, can you just post here the output of `pip freeze` ? Thanks!

**Comment by adil25** [comment]
ok, thanks, i got it, i will also post the output of pip freeze
    On Thursday, October 4, 2018, 1:30:02 AM GMT+8, pzhokhov <notifications@github.com> wrote:  
 
 
Hi @adil25! Which version of the gym are you using? (if you have installed it using pip, use pip freeze | grep gym) This looks to me like either old version; or some other module with name gym is installed... Actually, can you just post here the output of pip freeze ? Thanks!

**Comment by adil25** [comment]
@pzhokhov Here is the output after typing your suggested command i.e. pip freeze|grep gym

 pip freeze|grep gym
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gym==0.10.5
gym-minecraft==0.0.2

**Comment by adil25** [comment]
we are facing an error after running the code. could you please help us? thanks
[2018-10-07 10:56:26,665] Making new env: MinecraftBasic-v0
2018-10-07 10:57:26.056640: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
#######################################
% Win : 0.2%
% Nothing : 0.0%
% Loss : 0.0%
Nb J before win: 79.0
/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
out=out, **kwargs)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
Nb J before die: nan
Total Steps: 79
I: 0
Epsilon: 1

LAST EPISODE MOVES
Buffer Move 0 : move 1
Move Array 0 : move 1
ZPos : 0.5
XPos : 3.5
Yaw : 0.0
1 0 0 0
Buffer Move 1 : turn -1
Move Array 1 : turn -1
ZPos : 0.5
XPos : 3.5
Yaw : 0.0
0 0 0 1
Buffer Move 2 : move -1
Move Array 2 : move -1
ZPos : 1.5
XPos : 3.5
Yaw : 270.0
0 1 0 0
Buffer Move 3 : move 1
Move Array 3 : move 1
ZPos : 1.5
XPos : 3.5
Yaw : 270.0
1 0 0 0
Buffer Move 4 : turn -1
Move Array 4 : turn -1
ZPos : 1.5
XPos : 3.5
Yaw : 270.0
0 0 0 1
[2018-10-07 11:00:57,885] Agent missed 3 observation(s).
[2018-10-07 11:00:57,886] Agent missed 3 observation(s).
Process finished with exit code 135 (interrupted by signal 7: SIGEMT)

**Comment by christopherhesse** [comment]
This looks to be a bug in `gym_minecraft`, they need to do `import gym.spaces` instead of just `import gym`.

**Comment by adil25** [comment]
ok, Thanks
    On Friday, February 8, 2019, 5:51:36 PM PST, Christopher Hesse <notifications@github.com> wrote:  
 
 
Closed #1180.
