### ISSUE TITLE
import mujoco_p has error

### ISSUE THREAD

**Issue by dotd** [openai/gym#1181]
Hi,

After installing Mujoco-py on Ubuntu 18.4 on Lenovo Y530 and doing import mujoco_py in the python shell I get the following error. How do I install this KHR/khrplatform.h as stated below? I tried to google it but nothing really solves my problem.

Thanks!

>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /home/dotan/pythons/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/home/dotan/mujoco/mujoco-py/mujoco_py -I/home/dotan/.mujoco/mjpro150/include -I/home/dotan/pythons/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/dotan/pythons/anaconda3/include/python3.6m -c /home/dotan/mujoco/mujoco-py/mujoco_py/cymj.c -o /home/dotan/mujoco/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.59_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/dotan/mujoco/mujoco-py/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /home/dotan/pythons/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/home/dotan/mujoco/mujoco-py/mujoco_py -I/home/dotan/.mujoco/mjpro150/include -I/home/dotan/pythons/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/dotan/pythons/anaconda3/include/python3.6m -c /home/dotan/mujoco/mujoco-py/mujoco_py/gl/osmesashim.c -o /home/dotan/mujoco/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.59_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/dotan/mujoco/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/osmesa.h:58,
                 from /home/dotan/mujoco/mujoco-py/mujoco_py/gl/osmesashim.c:1:
/usr/include/GL/glext.h:467:10: fatal error: KHR/khrplatform.h: No such file or directory
 #include <KHR/khrplatform.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 476, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 97, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 210, in build
    built_so_file_path = self._build_impl()
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 264, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 233, in _build_impl
    dist.run_commands()
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dotan/pythons/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/dotan/mujoco/mujoco-py/mujoco_py/builder.py", line 133, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/dotan/pythons/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
>>> export
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'export' is not defined

**Comment by christopherhesse** [comment]
I'm afraid this is a `mujoco-py` issue and should be filed on https://github.com/openai/mujoco-py
