### ISSUE TITLE
Can't install mujoco, gym

### ISSUE THREAD

**Issue by damiaan111** [openai/gym#1232]
I followed all steps and cmake is installed, but i keep getting this error and can't figure out the problem.
It says requirements already satisfied for all the other packages in gym.

Can someone please help me out.

Installing collected packages: mujoco-py, gym
  Running setup.py install for mujoco-py ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3mzKKG/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-M7EVS3-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3mzKKG/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-3mzKKG/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "mujoco_py/builder.py", line 495
        print(MISSING_KEY_MESSAGE.format(key_path), file=sys.stderr)
                                                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3mzKKG/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-M7EVS3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3mzKKG/mujoco-py/

**Comment by damiaan111** [comment]
I have Python 3.5.6 installed

**Comment by daniel-s-ingram** [comment]
What line did you use to attempt the installation? It looks like you may have used the wrong version of pip.

**Comment by GhaziBenDahmen** [comment]
Well you're not using pip3 for this installation anyways "/usr/lib/python2.7/distutils/dist.py"
Either wrong python version or wrong pip version

**Comment by christopherhesse** [comment]
As people pointed out, `mujoco_py` requires Python 3, sorry about that!
