### ISSUE TITLE
Do rendering on remote server

### ISSUE THREAD

**Issue by laoreja** [openai/gym#1252]
How to do rendering for mujoco on a remote server? ssh -X and -Y does not work.
I googled around, people say that bin/docker_entrypoint offers one solution. But that file is not clear to me. Maybe you can clarify on that file?

The error message is:

```
GLFW error (code %d): %s 65544 b'X11: RandR gamma ramp support seems broken'
GLFW error (code %d): %s 65542 b'EGL: Failed to get EGL display: Success'
Creating window glfw
GLFW error (code %d): %s 65542 b'GLX: No GLXFBConfigs returned'
GLFW error (code %d): %s 65545 b'GLX: Failed to find a suitable GLXFBConfig'
Traceback (most recent call last):
  File "run_expert.py", line 76, in <module>
    main()
  File "run_expert.py", line 59, in main
    env.render()
  File "/disk2/xiuye_data/gym/gym/core.py", line 275, in render
    return self.env.render(mode, **kwargs)
  File "/disk2/xiuye_data/gym/gym/envs/mujoco/mujoco_env.py", line 118, in render
    self._get_viewer(mode).render()
  File "/disk2/xiuye_data/gym/gym/envs/mujoco/mujoco_env.py", line 130, in _get_viewer
    self.viewer = mujoco_py.MjViewer(self.sim)
  File "/home/xiuye/.pyenv/versions/3.6.5/lib/python3.6/site-packages/mujoco_py/mjviewer.py", line 133, in __init__
    super().__init__(sim)
  File "/home/xiuye/.pyenv/versions/3.6.5/lib/python3.6/site-packages/mujoco_py/mjviewer.py", line 26, in __init__
    super().__init__(sim)
  File "mujoco_py/mjrendercontext.pyx", line 278, in mujoco_py.cymj.MjRenderContextWindow.__init__
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 96, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 48, in mujoco_py.cymj.GlfwContext.__init__
  File "mujoco_py/opengl_context.pyx", line 97, in mujoco_py.cymj.GlfwContext._create_window
mujoco_py.cymj.GlfwError: Failed to create GLFW window
```

**Comment by christopherhesse** [comment]
Sadly you need to run an X server on the remote machine to get this to work.  You probably want to do this with `Xvfb` which creates a software renderer, the docker entrypoint actually uses this here: https://github.com/openai/gym/blob/647e1e20ff948263551595b4aa13439f72f3b73c/bin/docker_entrypoint#L7

**Comment by dhruvramani** [comment]
I created this [mini-package ](https://github.com/dhruvramani/gym-render-browser) which allows you to render your environment onto a browser by just adding one line to your code. This might help you.
Put your code in a function and replace your normal `env.render()` with `yield env.render(mode='rgb_array')`. Encapsulate this function with the `render_browser` decorator.

```python
import gym
from render_browser import render_browser

@render_browser
def test_policy(policy):
    # Your function/code here.
    env = gym.make('Breakout-v0')
    obs = env.reset()

    while True:
        yield env.render(mode='rgb_array')
        # ... run policy ...
        obs, rew, _, _ = env.step(action)

test_policy(policy)    
```
When you visit `your_ip:5000` on your browser, `test_policy()` will be called and you'll be able to see the rendered environment on your browser window.

**Comment by vonHartz** [comment]
> Sadly you need to run an X server on the remote machine to get this to work. You probably want to do this with `Xvfb` which creates a software renderer, the docker entrypoint actually uses this here:
> 
> https://github.com/openai/gym/blob/647e1e20ff948263551595b4aa13439f72f3b73c/bin/docker_entrypoint#L7

I have tried something like this: `xvfb-run --auto-servernum --server-num=1 -e /dev/stdout python train.py`, but still get the same error as the OP:

```
Creating offscreen glfw
GLFW error (code %d): %s 65542 b'GLX: No GLXFBConfigs returned'
GLFW error (code %d): %s 65545 b'GLX: Failed to find a suitable GLXFBConfig'
```
Any idea what might be the cause?
