### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" when running cem.py

### ISSUE THREAD

**Issue by stefan-reich** [openai/gym#1282]
Hi,

I simply run the examples/agents/cem.py demo script (from GitHub) like so:

```python3 examples/agents/cem.py```

after

```sudo -H pip install gym```

This is on Peppermint Linux. The demo runs fine, but in the end, there is this exception:

```
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/cem-agent-results')
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7f506917c710>>
Traceback (most recent call last):
  File "/home/stefan/dev/gym-master/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/home/stefan/dev/gym-master/gym/envs/classic_control/rendering.py", line 62, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/base.py", line 334, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/lib.py", line 97, in errcheck
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by christopherhesse** [comment]
According to this issue https://github.com/openai/gym/issues/1094 you may not be calling `env.close()` at the end of your script.  If that doesn't work, please post a short script that reproduces the error so I can look at it.

**Comment by stefan-reich** [comment]
As I said, I just run [the example from GitHub](https://github.com/openai/gym/blob/master/examples/agents/cem.py).

**Comment by christopherhesse** [comment]
Ah sorry about that, made a PR: https://github.com/openai/gym/pull/1321

**Comment by christopherhesse** [comment]
Fixed!  Thanks for the bug report!
