### ISSUE TITLE
pyglet.gl.lib.GLException: b'out of memory

### ISSUE THREAD

**Issue by zle1992** [openai/gym#1288]
run some steps  , I get a error like this. How to solve this?

Traceback (most recent call last):
  File "Breakout.py", line 226, in <module>
    main()
  File "Breakout.py", line 221, in main
    run()
  File "Breakout.py", line 202, in run
    env.render()  # render on the screen
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/gym/envs/atari/atari_env.py", line 110, in render
    self.viewer.imshow(img)
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/gym/envs/classic_control/rendering.py", line 345, in imshow
    texture = image.get_texture()
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/pyglet/image/__init__.py", line 859, in get_texture
    force_rectangle)
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/pyglet/image/__init__.py", line 844, in create_texture
    rectangle, force_rectangle)
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/pyglet/image/__init__.py", line 1564, in create
    blank)
  File "/home/gpu401/gpu_environment_installlocation/anaconda_installlocation/lib/python3.5/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'out of memory'

 run some steps

**Comment by christopherhesse** [comment]
Could you post an example script that reproduces this error?

**Comment by christopherhesse** [comment]
Closing due to lack of activity.

**Comment by rvadaga** [comment]
I hit the same out of memory exception from pyglet/gym with the car-racing environment. 

Here is the link to the [script](https://gist.github.com/rvadaga/fa4e00812022dbaf6fceb83c00c9f3b4) that I ran. This is the traceback for the exception:

```
Traceback (most recent call last):
  File "drive_manually.py", line 90, in <module>
    next_state, r, done, info = env.step(a)
  File "/Users/rahul/anaconda3/envs/deeprl/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 376, in step
    self.state = self.render("state_pixels")
  File "/Users/rahul/anaconda3/envs/deeprl/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 471, in render
    pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
  File "/Users/rahul/anaconda3/envs/deeprl/lib/python3.7/site-packages/pyglet/image/__init__.py", line 2047, in get_image_data
    self.gl_format, GL_UNSIGNED_BYTE, buffer)
  File "/Users/rahul/anaconda3/envs/deeprl/lib/python3.7/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'out of memory'
```

I use conda 4.8.4 with python 3.7.9. Here are other relevant packages and their respective versions:
gym==0.17.3
Box2D==2.3.10
pyglet==1.5.0 (since gym==0.17.3 supports >=1.4.0 and <=1.5.0; 1.5.7 is the latest pyglet version)

Any solution to this problem?
