### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid value'

### ISSUE THREAD

**Issue by Xavier449446** [openai/gym#1330]
Traceback (most recent call last):
  File "C:\Users\xavier\Desktop\Game\game_start.py", line 52, in <module>
    win=Gamewindow(1500,950, resizable=True)
  File "C:\Users\xavier\Desktop\Game\game_start.py", line 29, in __init__
    self.bg=pyglet.sprite.Sprite(bg,x=0,y=0)
  File "C:\Users\xavier\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\sprite.py", line 243, in __init__
    self._texture = img.get_texture()
  File "C:\Users\xavier\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\image\__init__.py", line 859, in get_texture
    force_rectangle)
  File "C:\Users\xavier\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\image\__init__.py", line 844, in create_texture
    rectangle, force_rectangle)
  File "C:\Users\xavier\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\image\__init__.py", line 1564, in create
    blank)
  File "C:\Users\xavier\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\gl\lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'
![bg1](https://user-images.githubusercontent.com/47718724/52915510-d0699700-3289-11e9-82e4-18312a892643.png)

[Game.zip](https://github.com/openai/gym/files/2873124/Game.zip)

**Comment by christopherhesse** [comment]
Is this a gym issue or a pyglet issue?

**Comment by christopherhesse** [comment]
Since the stack trace doesn't seem to include any gym code, I will close this as being a pyglet issue.
