### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by GbengaOdesanmi** [openai/gym#1334]
Please Can someone help me to solve this problem. thanks in advance

logging to /tmp/openai-2019-02-22-03-23-35-777880
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    run(**args)
  File "main.py", line 28, in run
    env = gym.make(env_id)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/gym/envs/registration.py", line 87, in make
    env = cls(**_kwargs)
  File "/home/gbenga/Downloads/asymmetric-actor-critic-master/environment/particle.py", line 19, in __init__
    mujoco_env.MujocoEnv.__init__(self, os.path.join(os.getcwd(), 'environment/assets/particle.xml'), 5)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 42, in __init__
    observation, _reward, done, _info = self.step(np.zeros(self.model.nu))
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/gym/core.py", line 62, in step
    raise NotImplementedError
NotImplementedError

**Comment by christopherhesse** [comment]
It looks like https://github.com/bhairavmehta95/asymmetric-actor-critic/blob/master/environment/particle.py has not updated to use the new `step` method instead of `_step`, you should install an older version of gym or else request that the author update their code to use the new interface.  Sorry for the trouble!
