### ISSUE TITLE
gym==0.12.1 installation error: conflicting types for ‘PFNGLFRAGMENTLIGHTFVSGIXPROC’

### ISSUE THREAD

**Issue by hartikainen** [openai/gym#1430]
I'm trying to install gym==0.12.1 with the new mujoco 2.0 support on the following setup:
- OS: Ubuntu 18.04
- Conda version: 4.6.11
- Python version: 3.6.5
- gym version: 0.12.1
- mujoco_py version: 2.0.2.0

I get the following error:
```
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /opt/conda/envs/softlearning/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py -I/root/.mujoco/mujoco200/include -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/numpy/core/include -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/vendor/egl -I/opt/conda/envs/softlearning/include/python3.6m -c /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/cymj.c -o /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxgpuextensionbuilder/temp.linux-x86_64-3.6/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /opt/conda/envs/softlearning/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py -I/root/.mujoco/mujoco200/include -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/numpy/core/include -I/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/vendor/egl -I/opt/conda/envs/softlearning/include/python3.6m -c /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c -o /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxgpuextensionbuilder/temp.linux-x86_64-3.6/opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.o -fopenmp -w
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12066:25: error: conflicting types for ‘PFNGLFRAGMENTLIGHTFVSGIXPROC’
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, const GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16092:28: note: previous declaration of ‘PFNGLFRAGMENTLIGHTFVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, GLfloat* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12068:25: error: conflicting types for ‘PFNGLFRAGMENTLIGHTIVSGIXPROC’
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTIVSGIXPROC) (GLenum light, GLenum pname, const GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16094:28: note: previous declaration of ‘PFNGLFRAGMENTLIGHTIVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTIVSGIXPROC) (GLenum light, GLenum pname, GLint* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12070:25: error: conflicting types for ‘PFNGLFRAGMENTLIGHTMODELFVSGIXPROC’
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTMODELFVSGIXPROC) (GLenum pname, const GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16088:28: note: previous declaration of ‘PFNGLFRAGMENTLIGHTMODELFVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTMODELFVSGIXPROC) (GLenum pname, GLfloat* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12072:25: error: conflicting types for ‘PFNGLFRAGMENTLIGHTMODELIVSGIXPROC’
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTMODELIVSGIXPROC) (GLenum pname, const GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16090:28: note: previous declaration of ‘PFNGLFRAGMENTLIGHTMODELIVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTMODELIVSGIXPROC) (GLenum pname, GLint* params);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12079:25: error: conflicting types for ‘PFNGLGETFRAGMENTMATERIALFVSGIXPROC’
 typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALFVSGIXPROC) (GLenum face, GLenum pname, GLfloat *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16101:28: note: previous declaration of ‘PFNGLGETFRAGMENTMATERIALFVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALFVSGIXPROC) (GLenum face, GLenum pname, const GLfloat* data);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:7:0:
/usr/include/GL/glext.h:12080:25: error: conflicting types for ‘PFNGLGETFRAGMENTMATERIALIVSGIXPROC’
 typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, GLint *params);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/softlearning/lib/python3.6/site-packages/mujoco_py/gl/eglshim.c:4:0:
/usr/include/GL/glew.h:16102:28: note: previous declaration of ‘PFNGLGETFRAGMENTMATERIALIVSGIXPROC’ was here
 typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, const GLint* data);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/opt/conda/envs/softlearning/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/opt/conda/envs/softlearning/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/conda/envs/softlearning/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/conda/envs/softlearning/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

I guess this might have something to do with conflicting glew versions. Has anyone seen this before or have ideas of how to fix it? I'm happy to provide more information if needed.

**Comment by hartikainen** [comment]
I don't think this is specific to 0.12.1 or mujoco 2.0 after all. I was trying to reinstall 0.12.0 with mujoco 1.5 on the same machine and got the same error. Any hints of fixing/debugging this error would still be appreciated.

**Comment by christopherhesse** [comment]
This looks like an issue mujoco_py, could you file it on that repo?  https://github.com/openai/mujoco-py  Thanks!

**Comment by hartikainen** [comment]
For reference: https://github.com/openai/mujoco-py/issues/383
