### ISSUE TITLE
async env with spawn context handles errors oddly

### ISSUE THREAD

**Issue by christopherhesse** [openai/gym#1542]
The following code is incorrect, but fails in an odd way:

```
import gym
import numpy as np


def main():
    def make_env():
        return gym.make("PongNoFrameskip-v4")

    venv = gym.vector.AsyncVectorEnv([make_env] * 3, context="spawn")
    venv.reset()
    while True:
        obs, rews, dones, infos = venv.step(np.array([venv.action_space.sample() for _ in range(venv.num_envs)]))


if __name__ == "__main__":
    main()
```

This produces:

```
ERROR: Received the following error from Worker-2: TypeError: only size-1 arrays can be converted to Python scalars
ERROR: Shutting down Worker-2.
ERROR: Received the following error from Worker-0: TypeError: only size-1 arrays can be converted to Python scalars
ERROR: Shutting down Worker-0.
ERROR: Received the following error from Worker-1: TypeError: only size-1 arrays can be converted to Python scalars
ERROR: Shutting down Worker-1.
ERROR: Raising the last exception back to the main process.
Traceback (most recent call last):
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 45, in <module>
    main()
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 41, in main
    obs, rews, dones, infos = venv.step(np.array([venv.action_space.sample() for _ in range(venv.num_envs)]))
  File "/Users/csh/agi/gym/gym/vector/vector_env.py", line 54, in step
    return self.step_wait()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 228, in step_wait
    self._raise_if_errors()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 327, in _raise_if_errors
    raise exctype(value)
TypeError: only size-1 arrays can be converted to Python scalars
/Users/csh/agi/gym/gym/logger.py:30: UserWarning: WARN: Calling `close` while waiting for a pending call to `step` to complete.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Exception ignored in: <function AsyncVectorEnv.__del__ at 0x10d461950>
Traceback (most recent call last):
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 332, in __del__
    self.close(terminate=True)
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 265, in close
    function(timeout)
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 223, in step_wait
    if not self._poll(timeout):
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 296, in _poll
    if pipe.closed or (not pipe.poll(delta)):
AttributeError: 'NoneType' object has no attribute 'closed'
```
There's a different error when using a "fork" context:

```
Traceback (most recent call last):
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 45, in <module>
    main()
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 41, in main
    obs, rews, dones, infos = venv.step(np.array([venv.action_space.sample() for _ in range(venv.num_envs)]))
  File "/Users/csh/agi/gym/gym/vector/vector_env.py", line 54, in step
    return self.step_wait()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 231, in step_wait
    observations_list, rewards, dones, infos = zip(*results)
TypeError: zip argument #1 must support iteration
```

**Comment by tristandeleu** [comment]
This is due to the way the actions are created. You should either call `venv.action_space.sample()`, or `np.array([venv.single_action_space.sample() for _ in range(venv.num_envs)])`. This works for me:
```python
import gym
import numpy as np


def main():
    def make_env():
        return gym.make("PongNoFrameskip-v4")

    venv = gym.vector.AsyncVectorEnv([make_env] * 3, context="spawn")
    venv.reset()
    while True:
        actions = venv.action_space.sample()
        obs, rews, dones, infos = venv.step(actions)
        print(obs.shape, rews, dones)


if __name__ == "__main__":
    main()
```
For both `context="spawn"` and `context="fork"`. I remember having some issues with spawn at some point, but I can't reproduce the issue I was having.
That being said, the error (`TypeError: only size-1 arrays can be converted to Python scalars`) should have been raised in a better way, so this is a sign of something going wrong in `_raise_if_errors`.

**Comment by christopherhesse** [comment]
Thanks!  Yeah, I'm aware that the code is incorrect, it's the handling of the error that was odd.  The most common issue with `"spawn"` is not doing `if __name__` in your test script.

**Comment by tristandeleu** [comment]
The error handling definitely has some issue. They should both be covered by #1556.
