### ISSUE TITLE
VectorEnv close() uses logger which performs late import of `six` resulting in odd error message

### ISSUE THREAD

**Issue by christopherhesse** [openai/gym#1546]
```
from gym.vector import make

venv = make("PongNoFrameskip-v4", num_envs=3)
obs, rews, dones, infos = venv.step(venv.action_space.sample())
print(obs.shape, rews, dones, infos)
```

This script sometimes produces an extra exception:

```
ERROR: Received the following error from Worker-0: AssertionError: Cannot call env.step() before calling reset()
ERROR: Shutting down Worker-0.
ERROR: Received the following error from Worker-2: AssertionError: Cannot call env.step() before calling reset()
ERROR: Shutting down Worker-2.
ERROR: Received the following error from Worker-1: AssertionError: Cannot call env.step() before calling reset()
ERROR: Shutting down Worker-1.
ERROR: Raising the last exception back to the main process.
Traceback (most recent call last):
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 4, in <module>
    obs, rews, dones, infos = venv.step(venv.action_space.sample())
  File "/Users/csh/agi/gym/gym/vector/vector_env.py", line 54, in step
    return self.step_wait()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 228, in step_wait
    self._raise_if_errors()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 327, in _raise_if_errors
    raise exctype(value)
AssertionError: Cannot call env.step() before calling reset()
Exception ignored in: <function AsyncVectorEnv.__del__ at 0x111340950>
Traceback (most recent call last):
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 332, in __del__
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 263, in close
  File "/Users/csh/agi/gym/gym/logger.py", line 30, in warn
  File "/Users/csh/agi/gym/gym/utils/colorize.py", line 27, in colorize
ModuleNotFoundError: import of six halted; None in sys.modules
```

There's an extra `ModuleNotFoundError` due to a late import of `six` in `colorize`.

**Comment by christopherhesse** [comment]
Sometimes this script produces the following output:

```
Traceback (most recent call last):
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/csh/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/csh/agi/sandbox/oneoff/try_vec_env.py", line 4, in <module>
    obs, rews, dones, infos = venv.step(venv.action_space.sample())
  File "/Users/csh/agi/gym/gym/vector/vector_env.py", line 54, in step
    return self.step_wait()
  File "/Users/csh/agi/gym/gym/vector/async_vector_env.py", line 231, in step_wait
    observations_list, rewards, dones, infos = zip(*results)
TypeError: zip argument #1 must support iteration
```

Seems like some sort of race condition.

**Comment by tristandeleu** [comment]
This might be a race condition, I can't reproduce it unfortunately
