### ISSUE TITLE
FetchReach-v1 can't make environment

### ISSUE THREAD

**Issue by SieRaX** [openai/gym#1719]
Hello, I tried one of most basic codes of openai gym trying to make FetchReach-v1 env like this.
```
`import gym

env = gym.make("FetchReach-v1")`

```
However, the code didn't work and gave this message

```
'/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    env = gym.make("FetchReach-v1")
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/robotics/__init__.py", line 1, in <module>
    from gym.envs.robotics.fetch_env import FetchEnv
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/robotics/fetch_env.py", line 3, in <module>
    from gym.envs.robotics import rotations, robot_env, utils
  File "/home/matthewcool/.local/lib/python3.7/site-packages/gym/envs/robotics/robot_env.py", line 10, in <module>
    import mujoco_py
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/mujoco_py/builder.py", line 507, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/mujoco_py/builder.py", line 101, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/home/matthewcool/anaconda3/envs/my_env/lib/python3.7/site-packages/mujoco_py/builder.py", line 124, in load_dynamic_ext
    return loader.load_module()
  File "__init__.pxd", line 918, in init mujoco_py.cymj
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
Did I do something wrong? How can I fix this kind of problem? Thank you.

**Comment by SieRaX** [comment]
Sorry. It is working now. It was gym version problem! Thank you!

**Comment by SohShiHui-UTAR** [comment]
Hi may I know how did you able to solve this problem?
