### ISSUE TITLE
import classic_control.rendering wrong

### ISSUE THREAD

**Issue by nicehiro** [openai/gym#1779]
Everything went all right before I upgrade python to 3.8.

When I import this module,
```
from gym.envs.classic_control import rendering
```
wired things happened:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 19, in <module>
    from . import xlib_vidmoderestore
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/canvas/xlib_vidmoderestore.py", line 23, in <module>
    from pyglet.libs.x11 import xlib
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/hiro/Documents/grid-world/venv/lib/python3.8/site-packages/pyglet/libs/x11/xlib.py", line 2928, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

How can I figure this out? Thanks!

**Comment by nicehiro** [comment]
Seems like a pyglet and python 3.7.6+ bug. So I close this issue.

https://github.com/pyglet/pyglet/issues/112

**Comment by YeeCY** [comment]
Upgrade to pyglet 1.4.9 solves the issue though gym complains about the pyglet version.

`pip install pyglet==1.4.9`
