### ISSUE TITLE
Issue starting FrozenLake Environment

### ISSUE THREAD

**Issue by BlooberryPi3** [openai/gym#1808]
I am just trying to start up in learning how this stuff works, but im immediately getting met by an error from the frozenlake stuff. I have no idea why it's happening or what I can do to fix it? Please help.

```Traceback (most recent call last):
  File "C:\Users\hatty\Desktop\gaems\Gym scripts\allagentsmall.py", line 10, in <module>
    env = gym.make("FrozenLake-v0")
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 58, in make
    cls = load(self.entry_point)
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\toy_text\__init__.py", line 7, in <module>
    from gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\toy_text\kellycoinflip.py", line 1, in <module>
    from scipy.stats import genpareto
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\hatty\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

**Comment by christopherhesse** [comment]
It looks like your scipy is busted.  Could you make a new environment using miniconda and see if you get the same error? https://conda.io/projects/conda/en/latest/user-guide/install/windows.html

**Comment by BlooberryPi3** [comment]
I'm not really sure how I would do that? Sorry. I've not really used miniconda or other things.

**Comment by BlooberryPi3** [comment]
Uhm, nobody can help?

**Comment by christopherhesse** [comment]
If you follow the instructions you can likely install miniconda.  If you don't want to use miniconda, you should try uninstalling and reinstalling your python environment.

**Comment by BlooberryPi3** [comment]
So reinstalling python fully? Or am I misunderstanding.. Or reinstalling gym itself fully?

**Comment by jkterry1** [comment]
Hey, it's been well over a year so I'm closing this due to inactivity
