### ISSUE TITLE
ModuleNotFoundError: No module named 'gym.spaces.dict_space'

### ISSUE THREAD

**Issue by AmitMandliya** [openai/gym#1848]
Can anyone please help:

I am getting below error while running this command:

**bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/lock_and_return.npz**
```

Inferred:
	names: examples/hide_and_seek_quadrant.jsonnet examples/lock_and_return.npz
	arguments: {}


/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/amitmandliya/.local/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-03-21 01:11:38,582 From /home/amitmandliya/amit/multi-agent-emergence-environments/ma_policy/load_policy.py:57: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

2020-03-21 01:11:38,582 From /home/amitmandliya/amit/multi-agent-emergence-environments/ma_policy/load_policy.py:58: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2020-03-21 01:11:38,582 From /home/amitmandliya/amit/multi-agent-emergence-environments/ma_policy/load_policy.py:61: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-21 01:11:38.589402: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-21 01:11:38.615025: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099940000 Hz
2020-03-21 01:11:38.616291: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x18f19a0 executing computations on platform Host. Devices:
2020-03-21 01:11:38.616386: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "bin/examine.py", line 91, in <module>
    main()
  File "/home/amitmandliya/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/amitmandliya/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/amitmandliya/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/amitmandliya/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bin/examine.py", line 68, in main
    for i, name in enumerate(policy_names)]
  File "bin/examine.py", line 68, in <listcomp>
    for i, name in enumerate(policy_names)]
  File "/home/amitmandliya/amit/multi-agent-emergence-environments/ma_policy/load_policy.py", line 65, in load_policy
    policy_fn_and_args_raw = pickle.loads(policy_dict['policy_fn_and_args'])

```

**Comment by christopherhesse** [comment]
It looks like you are loading a pickled object, can you tell me the gym version you have installed and the gym version that was installed on the copy of python that made that pickled object?

**Comment by ZhaochenXU-718** [comment]
Hi! I got the same error: **ModuleNotFoundError: No module named 'gym.spaces.dict_space'**. And my gym version is 0.15.7.

**Comment by HACLANG** [comment]
try:
```
pip3 uninstall gym

pip3 install gym==0.10.5

```

**Comment by jkterry1** [comment]
The current version of gym is 0.21.0
