### ISSUE TITLE
VideoRecorder is not working on CentOS 7 / RHEL 7

### ISSUE THREAD

**Issue by zlig** [openai/gym#1894]
The following error has been referenced in multiple issues already ( https://github.com/openai/gym/issues/948 https://github.com/openai/gym/issues/855 https://github.com/openai/gym/issues/35 ) :

```
Traceback (most recent call last):
  File "random_agent.py", line 43, in <module>
    ob, reward, done, _ = env.step(action)
  File "/home/user/miniconda3/envs/tf/lib/python3.7/site-packages/gym/wrappers/monitor.py", line 32, in step
    done = self._after_step(observation, reward, done, info)
  File "/home/user/miniconda3/envs/tf/lib/python3.7/site-packages/gym/wrappers/monitor.py", line 179, in _after_step
    self.video_recorder.capture_frame()
  File "/home/user/miniconda3/envs/tf/lib/python3.7/site-packages/gym/wrappers/monitoring/video_recorder.py", line 116, in capture_frame
    self._encode_image_frame(frame)
  File "/home/user/miniconda3/envs/tf/lib/python3.7/site-packages/gym/wrappers/monitoring/video_recorder.py", line 166, in _encode_image_frame
    self.encoder.capture_frame(frame)
  File "/home/user/miniconda3/envs/tf/lib/python3.7/site-packages/gym/wrappers/monitoring/video_recorder.py", line 301, in capture_frame
    self.proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe
```

The suggested methods are usually to install `libav` or `ffmpeg` on the system or the conda environment. When using a CentOS7 or RHEL7, however, these solutions aren't working because `libav` is not available on these platforms. The code uses the alternative `ffmpeg` with the same arguments than for `avconv`, which unfortunately doesn't record correctly as the arguments don't apply directly.

Created the PR https://github.com/openai/gym/pull/1893 to provide the correct arguments to ffmpeg, and also to address the lack of clarity when something goes wrong.

Tested on  RHEL 7.7 with using Anaconda 2020.02 with Python 3.7.7 and ffmpeg version 4.0 (from yum directly)

**Comment by andrewsonin** [comment]
The same issue

**Comment by jkterry1** [comment]
Closed by PR
