### ISSUE TITLE
Unable to install atari environment lineup.

### ISSUE THREAD

**Issue by saahiluppal** [openai/gym#1977]
I Have tried to methods for installation
1. pip install gym[atari] --user  # pip version 19.3.1
2. git clone https://github.com/openai/gym
    cd gym/
    pip3 install -e .[all] --user

and same traceback in both cases.
```bash
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-aqmgq9av/atari-py/setup.py", line 36, in <module>
      setup(name='atari-py',
    File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/clevermind/.local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-aqmgq9av/atari-py/setup.py", line 23, in run
      subprocess.check_call(['cmake', '--build', '.'], cwd=cwd)
    File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for atari-py

```
Can anyone troubleshoot this issue?

**Comment by christopherhesse** [comment]
There are atari-py wheels for python versions up to 3.7.  At some point we intend to switch to ale-py which should support python 3.8, but for now please use python 3.7 unless you want to debug build issues.
