### ISSUE TITLE
Getting a DockerException on env.configure(remotes=1), from the example code for the universe.

### ISSUE THREAD

**Issue by utanko** [openai/gym#2043]
>>> env = gym.make('flashgames.DuskDrive-v0')
[2020-09-04 12:02:38,413] Making new env: flashgames.DuskDrive-v0
/home/utanko/.local/lib/python3.6/site-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
>>> env.configure(remotes=1)  # automatically creates a local docker container
[2020-09-04 12:02:55,423] Writing logs to file: /tmp/universe-4217.log
[2020-09-04 12:02:55,429] Connection pool is full, discarding connection: localhost
Traceback (most recent call last):
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/client.py", line 116, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 565, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _get_timeout
    return Timeout.from_float(timeout)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/utanko/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/utanko/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/utanko/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/utanko/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/utanko/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/utanko/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/utanko/universe/universe/remotes/docker_remote.py", line 44, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/utanko/universe/universe/remotes/docker_remote.py", line 163, in __init__
    self.client, self.info = get_client()
  File "/home/utanko/universe/universe/remotes/docker_remote.py", line 157, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/home/utanko/.local/lib/python3.6/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

**Comment by jkterry1** [comment]
This is not an issue in the Gym repository itself
