### ISSUE TITLE
Numpy exception in gym module

### ISSUE THREAD

**Issue by Dasein-Yang** [openai/gym#2045]
Python 3.6.9 numpy 1.17.2 gym 0.9.0

When I run my algorithm(which has been tested successfully in this version) with the same environment, this exception happened and trace back shows me this information, but when I can successfully `import gym ` or `import datetime` in python (command line) .

```bash

Traceback (most recent call last):
  File "./NCS-C-base.py", line 15, in <module>
    import gym
  File "/home/yangqi/anaconda3/envs/tf1.5/lib/python3.6/site-packages/gym/__init__.py", line 48, in <module>
    sanity_check_dependencies()
  File "/home/yangqi/anaconda3/envs/tf1.5/lib/python3.6/site-packages/gym/__init__.py", line 16, in sanity_check_dependencies
    import numpy
  File "/home/yangqi/anaconda3/envs/tf1.5/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/yangqi/anaconda3/envs/tf1.5/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/home/yangqi/anaconda3/envs/tf1.5/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: PyCapsule_Import could not import module "datetime"
```

I try to install and uninstall numpy == 1.17 and 1.18.4\ try to uninstall gym = 0.9.0,0.10.0,...0.15.4 and all these didn't work. How can I repair my environment? And why it happened? I would be very grateful for your help! Thanks!

**Comment by jkterry1** [comment]
there is virtually a 100% chance that this issue is with your local machine
