### ISSUE TITLE
env.render() can not work

### ISSUE THREAD

**Issue by LucasPKU** [openai/gym#2068]
I try use gym in Ubuntu, but it can not work. And I try just create a new environment with conda with python 3.6.12, but it still can not work.
It is too upset to find I can not use this program in the first step...
The error messages are as follow:
Traceback (most recent call last):
  File "gg.py", line 5, in <module>
    env.render()
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 580, in __init__
    config = screen.get_best_config(template_config)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/canvas/base.py", line 192, in get_best_config
    configs = self.get_matching_configs(template)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 220, in get_matching_configs
    configs = template.match(canvas)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 58, in match
    have_13 = info.have_version(1, 3)
  File "/home/Lucas/miniconda3/lib/python3.7/site-packages/pyglet/gl/glx_info.py", line 86, in have_version
    client_version = self.get_client_version().split()[0]
IndexError: list index out of range

**Comment by jxfruit** [comment]
is this issue have been solved?
