### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by jsdd25** [openai/gym#2152]
I am having problems running examples/agents/random_agent.py to run a simple random agent. A very simple program fails when trying to load the GL context and I really do not know how to fix it:
`(base) jin@jin-MS-7B94:~/RL-learn/gym/examples/agents$ python random_agent.py 
INFO: Making new env: CartPole-v0
/home/jin/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
INFO: Clearing 3 monitor files from previous run (because force=True was provided)
INFO: Starting new video recorder writing to /home/jin/RL-learn/gym/examples/agents/ttt/random-agent-results/openaigym.video.0.4554.video000000.mp4
Traceback (most recent call last):
  File "random_agent.py", line 40, in <module>
    ob = env.reset()
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 39, in reset
    self._after_reset(observation)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 193, in _after_reset
    self.reset_video_recorder()
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 214, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py", line 101, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/core.py", line 275, in render
    return self.env.render(mode, **kwargs)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 150, in render
    from gym.envs.classic_control import rendering
  File "/home/jin/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/window/__init__.py", line 515, in __init__
    context = config.create_context(gl.current_context)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 186, in create_context
    return XlibContextARB(self, share)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 300, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/jin/anaconda3/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 203, in __init__
    raise gl.ContextException('Could not create GL context') 
pyglet.gl.ContextException: Could not create GL context
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/home/jin/RL-learn/gym/examples/agents/ttt/random-agent-results')
`
I have test OpenGL by running `glxgears` and `glxinfo` at the command prompt. The first one can show spinning gears. The second can give a dump of OpenGL details.
Could anyone give me help? Thanks a lot!

**Comment by dsalarc** [comment]
I'm with a similar problem
Trying to run a simple gym test:


> import gym
env = gym.make('CartPole-v0')
env.reset()
env.render()

The following problem occurs:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/dsalarc/anaconda3/envs/baselines/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

When trying to run glxgears:

> X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  35
  Current serial number in output stream:  36
