### ISSUE TITLE
 Getting “object has no attribute ‘unwrapped’” when creating a custom multi agent environment

### ISSUE THREAD

**Issue by aviskarkc10** [openai/gym#2253]
I am trying to create a custom multi agent environment with `rllib`, but get the following error:

```
Traceback (most recent call last):
  File "server.py", line 134, in <module>
    env = gym.make("rl_agent-v0")
  File "/home/aviskarkc10/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/aviskarkc10/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/aviskarkc10/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 65, in make
    env.unwrapped.spec = spec
AttributeError: 'RLAgent_v0' object has no attribute 'unwrapped'
```

My agent is a subclass of `MultiAgentEnv` which is imported from `ray.rllib.env`

The environment works fine for when I use the `gym.Env` subclass but fails when I convert it to a multi agent one

**Comment by Ascrypto** [comment]
I am having the same problem. Were you able to solve it?
