### ISSUE TITLE
Invalid action space for DoomDeathmatch-v0

### ISSUE THREAD

**Issue by danijar** [openai/gym#243]
Random sampling from the action space crashes the `DoomDeathmatch-v0` environment (Ubuntu 14.04 x64, Python 3.4, gym 0.1.4 via pip3). Here is the example program. Changing either the environment or passing an action vector of zeroes prevents the crash.

```python
import numpy as np
import gym
from doom_py import ScreenResolution

env = gym.make('DoomDeathmatch-v0')
# Works with: env = gym.make('DoomMyWayHome-v0')
env.configure(screen_resolution=ScreenResolution.RES_160X120)
observation = env.reset()
done = False
while not done:
    env.render()
    action = env.action_space.sample()
    # Works with: action = np.zeros(env.action_space.shape, dtype=int)
    observation, reward, done, info = env.step(action)
```

Console output:

```
[2016-07-12 14:59:07,851] Making new env: DoomDeathmatch-v0


*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x278

Generating vizdoom-crash.log and killing process 16023, please wait... 40	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Warning: Cannot convert string "xft:DejaVu Sans Mono:pixelsize=16" to type FontStruct
Traceback (most recent call last):
  File "doom.py", line 21, in <module>
    observation, reward, done, info = env.step(action)
  File "/usr/local/lib/python3.4/dist-packages/gym/core.py", line 121, in step
    observation, reward, done, info = self._step(action)
  File "/usr/local/lib/python3.4/dist-packages/gym/envs/doom/doom_env.py", line 160, in _step
    reward = self.game.make_action(list_action)
doom_py.vizdoom.ViZDoomErrorException: Controlled ViZDoom instance reported error.
Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x7f28e179bb70>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gym/envs/classic_control/rendering.py", line 332, in __del__
  File "/usr/local/lib/python3.4/dist-packages/gym/envs/classic_control/rendering.py", line 329, in close
  File "/usr/local/lib/python3.4/dist-packages/pyglet/window/xlib/__init__.py", line 474, in close
  File "/usr/local/lib/python3.4/dist-packages/pyglet/gl/xlib.py", line 343, in destroy
  File "/usr/local/lib/python3.4/dist-packages/pyglet/gl/base.py", line 333, in destroy
  File "/usr/local/lib/python3.4/dist-packages/pyglet/gl/xlib.py", line 333, in detach
  File "/usr/local/lib/python3.4/dist-packages/pyglet/gl/lib.py", line 96, in errcheck
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable
zsh: segmentation fault (core dumped)  python3 doom.py
```

**Comment by gdb** [comment]
@ppaquette mind taking a look?

**Comment by ppaquette** [comment]
Same fatal error as bug #167

This is triggered when `action[33]` (DROP_SELECTED_WEAPON) is called when the weapon has already been dropped.

This code triggers the crash:
```python
import numpy as np
import gym
env = gym.make('DoomDeathmatch-v0')
observation = env.reset()
done = False
while not done:
    env.render()
    action = np.zeros(env.action_space.shape, dtype=int)
    action[33] = 1
    observation, reward, done, info = env.step(action)
```

This code does not trigger the crash:
```python
import numpy as np
import gym
env = gym.make('DoomDeathmatch-v0')
observation = env.reset()
done = False
while not done:
    env.render()
    action = env.action_space.sample()
    action[33] = 0
    observation, reward, done, info = env.step(action)
```

Submitted a patch to ignore `action[33]` for the moment until fixed upstream, and will submit an upstream bug report.

The patch might also fix #167.

**Comment by danijar** [comment]
Thanks a lot.

**Comment by arpit15** [comment]
I have obtaining a similar error even after applying the fix. The following the vizdoom crash log
[log](https://gist.github.com/arpit15/09d99c29ec048adb49f22ad941b54985)
I see the problem was also present in the vizdoom which might have been fixed by adding [this](https://github.com/Marqt/ViZDoom/commit/dac22dc11dc235c2ebad1bfc7b9e9f2fbcd1bb4b) commit. This seemed to not made in the current version of doom_py. 
Can somebody confirm if this is the problem? I will try to recompile doom_py package with the changes and see if it works.
