### ISSUE TITLE
[Bug Report] BipedalWalker' object has no attribute 'joints'

### ISSUE THREAD

**Issue by VineetTambe** [openai/gym#2463]
I am trying to run the BipedalWalker-v3 environment. The same code works on my other machine with same setup but throwing this error on the other machine.

```
Traceback (most recent call last):
  File "Bipedal_MMPI.py", line 115, in <module>
    bipedal_mppi_gym.control()
  File "Bipedal_MMPI.py", line 57, in control
    self.simulate_rollouts(k, temp)
  File "Bipedal_MMPI.py", line 38, in simulate_rollouts
    _, reward, _, _ = copy_env.step(rollout_action_t)
  File "/home/vineet/rlenv/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 18, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/vineet/rlenv/lib/python3.8/site-packages/gym/envs/box2d/bipedal_walker.py", line 412, in step
    self.joints[0].motorSpeed = float(SPEED_HIP * np.sign(action[0]))
AttributeError: 'BipedalWalker' object has no attribute 'joints'
```

**System Info**
Ubuntu 20.04LTS
Mujoco150
gym[all] version (0.21.0)
python3.8.10

Any help will be appreciated. Thanks in advance!

**Comment by younik** [comment]
Could you provide a Minimal Reproducible Example? 
I have the same specifications but I can't reproduce the error @VineetTambe
