### ISSUE TITLE
[Bug] Failed to install correctly on Linux (ImportError: Library "GLU" not found.)

### ISSUE THREAD

**Issue by RafayAK** [openai/gym#2478]
**Describe the bug**
Followed the simple guide of installing gym through `pip install gym` and it fails to render the sample program

**Code example**
```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) #  take a random action
env.close()
```

The Error: 
```bash
/home/rafay_veeve/anaconda3/envs/pytorch/bin/python /home/rafay_veeve/Documents/RL_stuff/main.py
Traceback (most recent call last):
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rafay_veeve/Documents/RL_stuff/main.py", line 5, in <module>
    env.render()
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/gym/core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 179, in render
    from gym.envs.classic_control import rendering
  File "/home/rafay_veeve/anaconda3/envs/pytorch/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 29, in <module>
    raise ImportError(
ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL installed. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
    

Process finished with exit code 1

```

**System Info**
- PopOS 21.04 (basically Ubuntu 21.04)
- Running gym in a Conda environment
- Python version: 3.8.12

**Additional context**

The way I installed gym and its dependencies:
```
pip install gym # Successfully installed gym-0.21.0
pip install gym[atari]  # Successfully installed ale-py-0.7.2
pip install  pyglet  #  Successfully installed pyglet-1.5.21

# Install OpenGL packages
sudo apt install freeglut3-dev freeglut3 libgl1-mesa-dev libglu1-mesa-dev libxext-dev libxt-dev
sudo apt install python3-opengl libgl1-mesa-glx libglu1-mesa
```

I am basically installing Gym to use with PyTorch here are the packages installed in my conda environment:
```bash
# packages in environment at /home/rafay_veeve/anaconda3/envs/pytorch:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
ale-py                    0.7.2                    pypi_0    pypi
anyio                     3.3.4            py38h578d9bd_0    conda-forge
argon2-cffi               21.1.0           py38h497a2fe_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bottleneck                1.3.2            py38heb32a55_1    anaconda
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.2               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0                    pypi_0    pypi
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
debugpy                   1.4.1            py38h709712a_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
fastdtw                   0.3.4            py38h81c977d_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0  
giflib                    5.2.1                h7b6447c_0  
glfw                      2.3.0                    pypi_0    pypi
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
gym                       0.21.0                   pypi_0    pypi
hdf5                      1.12.1          nompi_h2750804_101    conda-forge
idna                      3.2                pyhd3eb1b0_0  
imageio                   2.10.1                   pypi_0    pypi
importlib-metadata        4.8.1            py38h578d9bd_0    conda-forge
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350  
ipykernel                 6.4.1            py38he5a9106_0    conda-forge
ipython                   7.28.0           py38he5a9106_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.1.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py38h578d9bd_0    conda-forge
jupyter_server            1.11.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.19.2               hcc1bbae_2    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0            11_linux64_mkl    conda-forge
libcblas                  3.9.0            11_linux64_mkl    conda-forge
libcurl                   7.79.1               h2574ce0_1    conda-forge
libedit                   3.1.20210714         h7f8727e_0  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h516909a_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h3942068_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
lockfile                  0.12.2                   pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mediapipe                 0.8.8.1                  pypi_0    pypi
mistune                   0.8.4           py38h497a2fe_1004    conda-forge
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.2            py38h51133e4_0  
nbclassic                 0.3.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.2.0            py38h578d9bd_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1  
ninja                     1.10.2               hff7bd54_1  
notebook                  6.4.4              pyha770c72_0    conda-forge
numba                     0.53.1           py38h8b71fd7_1    conda-forge
numexpr                   2.7.3            py38h22e1b3c_1  
numpy                     1.21.2           py38h20f2e39_0  
numpy-base                1.21.2           py38h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
opencv-contrib-python     4.5.3.56                 pypi_0    pypi
opencv-python             4.5.4.58                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.3            py38h8c16a72_0  
pandoc                    2.14.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1002    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0  
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
protobuf                  3.18.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyglet                    1.5.21                   pypi_0    pypi
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.1           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyzmq                     22.2.1           py38h295c915_1  
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-unixsocket       0.2.0                      py_0    conda-forge
scikit-learn              0.24.2           py38hdc147b9_0    conda-forge
scipy                     1.7.1            py38h292c36d_2  
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sniffio                   1.2.0            py38h578d9bd_1    conda-forge
sqlite                    3.36.0               hc218d9a_0  
terminado                 0.12.1           py38h578d9bd_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h1ccaba5_0  
torchaudio                0.9.1                      py38    pytorch
torchvision               0.10.1               py38_cu102    pytorch
tornado                   6.1              py38h497a2fe_1    conda-forge
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
tslearn                   0.5.2            py38h6c62de6_0    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          0.58.0           py38h06a4308_4  
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.9                haebb681_0  

```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by RafayAK** [comment]
The problem is the PyCharm installation I was using. For some reason, if PyCharm Flatpak is used it fails to find the relevant OpenGL packages as mentioned here (https://stackoverflow.com/a/52909744/4699994)
