### ISSUE TITLE
Object has no attribute _shape

### ISSUE THREAD

**Issue by Ascrypto** [openai/gym#2483]
I have a class derived from gym.Space, which invokes two methods: contains() and sample(). The code worked fine at first, but after integrating Ray library with the code I keep getting the error message described below. I noticed the same function is defined in both space.py (Gym 0.21) and preprocessors.py (Ray 0.8.5). 

`Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::BaselinePPOTrainer.train() (pid=2843, ip=172.31.82.103)
  File "python/ray/_raylet.pyx", line 424, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 462, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 448, in __init__
    super().__init__(config, logger_creator)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/tune/trainable.py", line 174, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 591, in _setup
    self._init(self.config, self.env_creator)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 115, in _init
    self.workers = self._make_workers(env_creator, self._policy,
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 657, in _make_workers
    return WorkerSet(
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 60, in __init__
    self._local_worker = self._make_worker(
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 243, in _make_worker
    worker = cls(
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 376, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 835, in _build_policy_map
    preprocessor = ModelCatalog.get_preprocessor_for_space(
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 403, in get_preprocessor_for_space
    prep = cls(observation_space, options)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 33, in __init__
    self.shape = self._init_shape(obs_space, self._options)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 223, in _init_shape
    preprocessor = get_preprocessor(space)(space, self._options)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 250, in get_preprocessor
    legacy_patch_shapes(space)
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 286, in legacy_patch_shapes
    return space.shape
  File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/gym/spaces/space.py", line 41, in shape
    return self._shape
**AttributeError: 'MySpace' object has no attribute '_shape'`**

**Comment by RedTachyon** [comment]
You defined the space wrong, you probably need to add a `self._shape` field. Impossible to say more without details

**Comment by Ascrypto** [comment]
I added: 
`def shape(self): 
       return self._shape
`
to MySpace class although it is not used in the code. However, adding it caused this error: 
` File "/home/ubuntu/PycharmProjects/project/venv/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 34, in __init__
    self._size = int(np.product(self.shape))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'method'` 
Prior to including /ray/rllib/modls/preproccessors.py, there was no problem with the way MySpace class was defined.
