### ISSUE TITLE
[Bug Report]   env.render() not work

### ISSUE THREAD

**Issue by tmrhj** [openai/gym#2557]
I  use gym in Windows10, but it can not work. And  environment with conda with python 3.9.7.

env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
	env.render()
	env.step(env.action_space.sample())  # take a random action
env.close()

Traceback (most recent call last):
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyWorkspace\AutoRL\com\worlk\test\gym_test.py", line 31, in <module>
    t2()
  File "D:\PyWorkspace\AutoRL\com\worlk\test\gym_test.py", line 25, in t2
    env.render()
  File "D:\AI\Anaconda3\lib\site-packages\gym\core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "D:\AI\Anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py", line 179, in render
    from gym.envs.classic_control import rendering
  File "D:\AI\Anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\gl\__init__.py", line 236, in <module>
    import pyglet.window
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\gl\__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 131, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 493, in __init__
    display = get_platform().get_default_display()
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 1765, in get_default_display
    return pyglet.canvas.get_display()
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\canvas\__init__.py", line 77, in get_display
    from pyglet.app import displays
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\app\__init__.py", line 177, in <module>
    event_loop = EventLoop()
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\app\base.py", line 116, in __init__
    self.clock = clock.get_default()
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "D:\AI\Anaconda3\lib\site-packages\pyglet\clock.py", line 165, in <module>
    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by jkterry1** [comment]
Hey, pyglet has lots of wierd errors like this, we're currently in the process of getting rid of it for all environments
