### ISSUE TITLE
ImportError: cannot import name 'error' from 'gym'

### ISSUE THREAD

**Issue by jaiswalharsh** [openai/gym#2569]
I have been trying to launch the lunar_lander.py script from `/gym/gym/envs/box2d` directory but I get the following:

`Traceback (most recent call last):
  File "lunar_lander.py", line 46, in <module>
    from gym import error, spaces
ImportError: cannot import name 'error' from 'gym' (unknown location)`

I tried to skip importing _error_ then I got the same error but for importing _spaces_ from _gym_.

I am running this with the following config:
OS: Ubuntu 18.04
Python version: 3.7.5
gym version: 0.21.0

Any help would be appreciated. Thank you in advance!

**Comment by balisujohn** [comment]
Did you install from source? If not, definitely try this first.
`cd gym
python3.75 -m pip install -e .`

**Comment by jkterry1** [comment]
Hey, I'm closing due to inactivity, please feel free to converse if you have further questions though

**Comment by shivaniraochepuri21** [comment]
> I have been trying to launch the lunar_lander.py script from `/gym/gym/envs/box2d` directory but I get the following:
> 
> `Traceback (most recent call last): File "lunar_lander.py", line 46, in <module> from gym import error, spaces ImportError: cannot import name 'error' from 'gym' (unknown location)`
> 
> I tried to skip importing _error_ then I got the same error but for importing _spaces_ from _gym_.
> 
> I am running this with the following config: OS: Ubuntu 18.04 Python version: 3.7.5 gym version: 0.21.0
> 
> Any help would be appreciated. Thank you in advance!

Hi, I have the same issue. Were you able to solve it? Thanks IA
