### ISSUE TITLE
Can't create 0.22.0 atari environment and new release has not updated version number

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [openai/gym#2624]
Bug 1. 
Gym version number is 0.21.0 while the most recent release is 0.22.0
https://github.com/openai/gym/blob/master/gym/version.py
https://github.com/openai/gym/releases/tag/0.22.0

Bug 2. 
I have cloned the repository and tried to create an atari environment however it throws an error about the seed
```
> import gym
> gym.make('ALE/Breakout-v5')
A.L.E: Arcade Learning Environment (version 0.7.4+069f8bd)
[Powered by Stella]
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-52e43c1205a5>", line 1, in <module>
    gym.make('Breakout')
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/gym/envs/atari/environment.py", line 123, in __init__
    self.seed()
  File "/home/mark/anaconda3/envs/penguin/lib/python3.9/site-packages/gym/envs/atari/environment.py", line 165, in seed
    self.np_random, seed1 = seeding.np_random(seed)
AttributeError: can't set attribute
``` 

This git commit appears to be the cause of the problem
https://github.com/openai/gym/commit/2be9e60a4dd8fa55f78d54110a928147ddbcd4ad
The problem doesn't occur with the previous commit - 8819d561132082f6130d4a2388c68a963f41ec4f

But I can't work out what the issue is as the commit doesn't change any of the code in envs/atari/environment.py

**Comment by jkterry1** [comment]
@pseudo-rnd-thoughts could you please email me to discuss at jkterry@umd.edu?
