### ISSUE TITLE
[Bug Report] `gym.make("CartPole-v1")` prompts `ModuleNotFoundError: No module named 'pygame'`

### ISSUE THREAD

**Issue by vwxyzjn** [openai/gym#2634]
**Describe the bug**
Pygame is a required dependency for `CartPole-v1` now but gym does not require pygame by default. As a result, when doing something like 

```
pip install gym
python -c "import gym;gym.make('CartPole-v1')"
```

prompts

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 139, in make
    cls = load(self.entry_point)
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 55, in load
    mod = importlib.import_module(mod_name)
  File "/home/costa/.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
    from gym.envs.classic_control.cartpole import CartPoleEnv
  File "/home/costa/.cache/pypoetry/virtualenvs/tttt-PLHdinwv-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

See 
[![asciicast](https://asciinema.org/a/YBdQQj0icX3blrWz7UU5CtbRG.svg)](https://asciinema.org/a/YBdQQj0icX3blrWz7UU5CtbRG)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by Kayzwer** [comment]
I solved it by just `pip install pygame`

**Comment by kir0ul** [comment]
My understanding is that it's not a bug, as the CartPole environment is part of Classic Control, it should be installed with `pip install gym[classic_control]` as described in the [Classic Control docs](https://www.gymlibrary.ml/pages/environments/classic_control/), then it should install Pygame as it is a [requirement in `setup.py` for the Classic Control environments](https://github.com/openai/gym/blob/master/setup.py#L16).

**Comment by jkterry1** [comment]
@kir0ul is correct. This was actually required to have the rendering work before if you installed gym from a clean install previously because it used pyglet
