### ISSUE TITLE
[Bug Report] ~1500 missing warnings with pytest --forked option

### ISSUE THREAD

**Issue by kir0ul** [openai/gym#2647]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
I don't know if I'm missing something but it seems to me the pytest `--forked` option is missing to report **a lot** of warnings.

**Code example**
With the `--forked` option I get only **2 warnings** (as it is currently the case in CI):
```
❯ docker run gym-docker pytest --forked --import-mode=append
+ export DISPLAY=:0
+ DISPLAY=:0
+ display=0
+ file=/tmp/.X11-unix/X0
+ Xvfb -screen 0 1024x768x24
++ seq 1 10
+ for i in $(seq 1 10)
+ '[' -e /tmp/.X11-unix/X0 ']'
+ echo 'Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)'
+ sleep 1
Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
+ for i in $(seq 1 10)
+ '[' -e /tmp/.X11-unix/X0 ']'
+ break
+ '[' -e /tmp/.X11-unix/X0 ']'
+ exec pytest --forked --import-mode=append
============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /usr/local/gym
plugins: forked-1.4.0
collected 623 items / 5 skipped / 618 selected

tests/test_core.py ............                                          [  1%]
tests/envs/test_action_dim_check.py s                                    [  2%]
tests/envs/test_determinism.py ................                          [  4%]
tests/envs/test_envs.py ..................................               [ 10%]
tests/envs/test_frozenlake_dfs.py .                                      [ 10%]
tests/envs/test_lunar_lander.py ..                                       [ 10%]
tests/envs/test_mujoco_v2_to_v3_conversion.py s                          [ 10%]
tests/envs/test_registration.py ......................................   [ 16%]
tests/spaces/test_spaces.py ............................................ [ 23%]
............................................................             [ 33%]
tests/spaces/test_utils.py ............................................. [ 40%]
....................................                                     [ 46%]
tests/utils/test_atexit.py .                                             [ 46%]
tests/utils/test_env_checker.py .                                        [ 46%]
tests/utils/test_seeding.py ..                                           [ 47%]
tests/vector/test_async_vector_env.py ..............................     [ 52%]
tests/vector/test_numpy_utils.py ....................................... [ 58%]
.......................................                                  [ 64%]
tests/vector/test_shared_memory.py ..................................... [ 70%]
........................................................................ [ 82%]
.......                                                                  [ 83%]
tests/vector/test_spaces.py ..............................               [ 87%]
tests/vector/test_sync_vector_env.py ........                            [ 89%]
tests/vector/test_vector_env.py ...                                      [ 89%]
tests/vector/test_vector_env_wrapper.py .                                [ 89%]
tests/wrappers/flatten_test.py ......                                    [ 90%]
tests/wrappers/nested_dict_test.py ..........                            [ 92%]
tests/wrappers/test_clip_action.py .                                     [ 92%]
tests/wrappers/test_filter_observation.py .......                        [ 93%]
tests/wrappers/test_flatten_observation.py .                             [ 93%]
tests/wrappers/test_normalize.py ......                                  [ 94%]
tests/wrappers/test_order_enforcing.py .                                 [ 95%]
tests/wrappers/test_pixel_observation.py ....                            [ 95%]
tests/wrappers/test_record_episode_statistics.py .........               [ 97%]
tests/wrappers/test_record_video.py .Exception ignored in: <function VideoRecorder.__del__ at 0x7fb463eaeb90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 193, in __del__
    self.close()
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 182, in close
    self.write_metadata()
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 188, in write_metadata
    with open(self.metadata_path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/gym/videos/rl-video-step-0.meta.json'
...                                 [ 97%]
tests/wrappers/test_rescale_action.py .                                  [ 97%]
tests/wrappers/test_time_aware_observation.py ..                         [ 98%]
tests/wrappers/test_time_limit.py .                                      [ 98%]
tests/wrappers/test_transform_observation.py ..                          [ 98%]
tests/wrappers/test_transform_reward.py ..                               [ 99%]
tests/wrappers/test_video_recorder.py ......                             [100%]

=============================== warnings summary ===============================
../lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9
  /usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils.spawn

../lib/python3.10/site-packages/gym/spaces/box.py:78
  /usr/local/lib/python3.10/site-packages/gym/spaces/box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
    logger.warn(f"Box bound precision lowered by casting to {self.dtype}")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 621 passed, 7 skipped, 2 warnings in 39.42s ==================
```

Now **without** the `--forked` option I get **~1500 warnings**:
```
❯ docker run gym-docker pytest --import-mode=append
+ export DISPLAY=:0
+ DISPLAY=:0
+ display=0
+ file=/tmp/.X11-unix/X0
+ Xvfb -screen 0 1024x768x24
++ seq 1 10
+ for i in $(seq 1 10)
+ '[' -e /tmp/.X11-unix/X0 ']'
+ echo 'Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)'
+ sleep 1
Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
+ for i in $(seq 1 10)
+ '[' -e /tmp/.X11-unix/X0 ']'
+ break
+ '[' -e /tmp/.X11-unix/X0 ']'
+ exec pytest --import-mode=append
============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /usr/local/gym
plugins: forked-1.4.0
collected 623 items / 5 skipped / 618 selected

tests/test_core.py ............                                          [  1%]
tests/envs/test_action_dim_check.py s                                    [  2%]
tests/envs/test_determinism.py ................                          [  4%]
tests/envs/test_envs.py ..................................               [ 10%]
tests/envs/test_frozenlake_dfs.py .                                      [ 10%]
tests/envs/test_lunar_lander.py ..                                       [ 10%]
tests/envs/test_mujoco_v2_to_v3_conversion.py s                          [ 10%]
tests/envs/test_registration.py ......................................   [ 16%]
tests/spaces/test_spaces.py ............................................ [ 23%]
............................................................             [ 33%]
tests/spaces/test_utils.py ............................................. [ 40%]
....................................                                     [ 46%]
tests/utils/test_atexit.py .                                             [ 46%]
tests/utils/test_env_checker.py .                                        [ 46%]
tests/utils/test_seeding.py ..                                           [ 47%]
tests/vector/test_async_vector_env.py ..............................     [ 52%]
tests/vector/test_numpy_utils.py ....................................... [ 58%]
.......................................                                  [ 64%]
tests/vector/test_shared_memory.py ..................................... [ 70%]
........................................................................ [ 82%]
.......                                                                  [ 83%]
tests/vector/test_spaces.py ..............................               [ 87%]
tests/vector/test_sync_vector_env.py ........                            [ 89%]
tests/vector/test_vector_env.py ...                                      [ 89%]
tests/vector/test_vector_env_wrapper.py .                                [ 89%]
tests/wrappers/flatten_test.py ......                                    [ 90%]
tests/wrappers/nested_dict_test.py ..........                            [ 92%]
tests/wrappers/test_clip_action.py .                                     [ 92%]
tests/wrappers/test_filter_observation.py .......                        [ 93%]
tests/wrappers/test_flatten_observation.py .                             [ 93%]
tests/wrappers/test_normalize.py ......                                  [ 94%]
tests/wrappers/test_order_enforcing.py .                                 [ 95%]
tests/wrappers/test_pixel_observation.py ....                            [ 95%]
tests/wrappers/test_record_episode_statistics.py .........               [ 97%]
tests/wrappers/test_record_video.py .Exception ignored in: <function VideoRecorder.__del__ at 0x7f0366c06b90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 193, in __del__
    self.close()
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 182, in close
    self.write_metadata()
  File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 188, in write_metadata
    with open(self.metadata_path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/gym/videos/rl-video-step-0.meta.json'
...                                 [ 97%]
tests/wrappers/test_rescale_action.py .                                  [ 97%]
tests/wrappers/test_time_aware_observation.py ..                         [ 98%]
tests/wrappers/test_time_limit.py .                                      [ 98%]
tests/wrappers/test_transform_observation.py ..                          [ 98%]
tests/wrappers/test_transform_reward.py ..                               [ 99%]
tests/wrappers/test_video_recorder.py ......                             [100%]

=============================== warnings summary ===============================
../lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9
  /usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils.spawn

../lib/python3.10/site-packages/gym/spaces/box.py:78
tests/wrappers/test_normalize.py::test_normalize_observation[False]
tests/wrappers/test_normalize.py::test_normalize_observation[True]
tests/wrappers/test_normalize.py::test_normalize_reset_info
tests/wrappers/test_normalize.py::test_normalize_return
tests/wrappers/test_normalize.py::test_normalize_observation_vector_env
tests/wrappers/test_normalize.py::test_normalize_return_vector_env
  /usr/local/lib/python3.10/site-packages/gym/spaces/box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
    logger.warn(f"Box bound precision lowered by casting to {self.dtype}")

tests/envs/test_determinism.py: 80 warnings
tests/envs/test_envs.py: 137 warnings
tests/spaces/test_spaces.py: 266 warnings
tests/spaces/test_utils.py: 176 warnings
tests/utils/test_env_checker.py: 2 warnings
tests/vector/test_async_vector_env.py: 16 warnings
tests/vector/test_numpy_utils.py: 64 warnings
tests/vector/test_shared_memory.py: 128 warnings
tests/vector/test_sync_vector_env.py: 8 warnings
tests/wrappers/test_normalize.py: 6 warnings
tests/wrappers/test_record_episode_statistics.py: 181 warnings
tests/wrappers/test_record_video.py: 398 warnings
tests/wrappers/test_time_aware_observation.py: 2 warnings
tests/wrappers/test_transform_observation.py: 1 warning
tests/wrappers/test_transform_reward.py: 14 warnings
  /usr/local/lib/python3.10/site-packages/gym/utils/seeding.py:47: DeprecationWarning: WARN: Function `rng.randint(low, [high, size, dtype])` is marked as deprecated and will be removed in the future. Please use `rng.integers(low, [high, size, dtype])` instead.
    deprecation(

tests/envs/test_envs.py::test_env[spec1]
tests/envs/test_envs.py::test_env[spec2]
tests/envs/test_envs.py::test_env[spec10]
tests/envs/test_envs.py::test_env[spec11]
  /usr/local/lib/python3.10/site-packages/gym/utils/env_checker.py:116: UserWarning: WARN: Agent's minimum observation space value is -infinity. This is probably too low.
    logger.warn(

tests/envs/test_envs.py::test_env[spec1]
tests/envs/test_envs.py::test_env[spec2]
tests/envs/test_envs.py::test_env[spec10]
tests/envs/test_envs.py::test_env[spec11]
  /usr/local/lib/python3.10/site-packages/gym/utils/env_checker.py:120: UserWarning: WARN: Agent's maxmimum observation space value is infinity. This is probably too high
    logger.warn(

tests/envs/test_envs.py::test_env[spec4]
tests/envs/test_envs.py::test_env[spec14]
  /usr/local/lib/python3.10/site-packages/gym/utils/env_checker.py:162: UserWarning: WARN: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
    logger.warn(

tests/envs/test_envs.py::test_env[spec14]
tests/envs/test_envs.py::test_env[spec14]
tests/envs/test_envs.py::test_env[spec14]
tests/envs/test_envs.py::test_env[spec14]
  /usr/local/lib/python3.10/site-packages/gym/envs/classic_control/pendulum.py:183: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
    scale_img = pygame.transform.flip(scale_img, is_flip, True)

tests/spaces/test_spaces.py::test_box_dtype_check
tests/vector/test_spaces.py::test_iterate[Box0]
tests/vector/test_spaces.py::test_iterate[Box4]
tests/vector/test_spaces.py::test_iterate[Dict1]
tests/vector/test_spaces.py::test_iterate_custom_space[Tuple]
  /usr/local/lib/python3.10/site-packages/gym/spaces/box.py:153: UserWarning: WARN: Casting input x to numpy array.    logger.warn("Casting input x to numpy array.")

tests/vector/test_async_vector_env.py::test_custom_space_async_vector_env_shared_memory
  /usr/local/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function AsyncVectorEnv.__del__ at 0x7f0366be9ea0>
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/gym/vector/async_vector_env.py", line 631, in __del__
      self.close(terminate=True)
    File "/usr/local/lib/python3.10/site-packages/gym/vector/vector_env.py", line 193, in close
      self.close_extras(**kwargs)
    File "/usr/local/lib/python3.10/site-packages/gym/vector/async_vector_env.py", line 543, in close_extras
      if self._state != AsyncState.DEFAULT:
  AttributeError: 'AsyncVectorEnv' object has no attribute '_state'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/wrappers/test_record_video.py::test_record_video_reset_return_info
  /usr/local/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function VideoRecorder.__del__ at 0x7f0366c06b90>
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 193, in __del__
      self.close()
    File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 182, in close
      self.write_metadata()
    File "/usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py", line 188, in write_metadata
      with open(self.metadata_path, "w") as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/gym/videos/rl-video-step-0.meta.json'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/wrappers/test_video_recorder.py::test_record_breaking_render_method
  /usr/local/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:136: UserWarning: WARN: Env returned None on render(). Disabling further rendering for video recorder by marking as disabled: path=/tmp/tmpqrycjchl.mp4 metadata_path=/tmp/tmpqrycjchl.meta.json
    logger.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================ 621 passed, 7 skipped, 1509 warnings in 21.03s ================
```

Is this intended? Is the pytest `--forked` option mandatory for some reason?

**System Info**
Describe the characteristic of your environment:
 * Gym installed with: `docker build -f py.Dockerfile --build-arg MUJOCO_KEY=./mjkey.txt --build-arg PYTHON_VERSION=3.10 --tag gym-docker .`
 * OS/version of Linux: Debian 11 Bullseye (from the Docker image)
 * Python version: 3.10.2 (from the Docker image)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
So I assume that [pytest-forked](https://github.com/pytest-dev/pytest-forked) is bugged? We presumably should remove it, file and upstream report, and fix issues leading to all the CI issues

**Comment by pseudo-rnd-thoughts** [comment]
I have reduced the number of warnings to 10 and I believe I can reduce the number down further
I will create a merge request for the changes soon

However, I have got stuck with an error that appears for tests/vector/test_async_vector_env.py 
In test_custom_space_async_vector_env_shared_memory, there is a __del__ error where a variable (_state) doesn't exist anymore however I can't see where the variable is deleted
Small warning, if you are using pycharm then pytest doesn't show this issue for me, I could only see it in the terminal
Any ideas?

**Comment by pseudo-rnd-thoughts** [comment]
With this PR merged, could this issue be closed?
