### ISSUE TITLE
[Gym] Gym env KeyError

### ISSUE THREAD

**Issue by lishizhen1412** [openai/gym#2696]
### KeyError: (<weakref at 0x000001DCF9A9FE08; to 'Win32Window' at 0x000001DCF96B85F8>,)

OS: Windows10, 64bits

`Exception ignored in: <function Viewer.__del__ at 0x000001DCF9A88730>
Traceback (most recent call last):
  File "E:\02_code\easy-rl-1.0.0\venv\lib\site-packages\gym\envs\classic_control\rendering.py", line 165, in __del__
    self.close()
  File "E:\02_code\easy-rl-1.0.0\venv\lib\site-packages\gym\envs\classic_control\rendering.py", line 83, in close
    self.window.close()
  File "E:\02_code\easy-rl-1.0.0\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 299, in close
    super(Win32Window, self).close()
  File "E:\02_code\easy-rl-1.0.0\venv\lib\site-packages\pyglet\window\__init__.py", line 823, in close
    app.windows.remove(self)
  File "D:\Program Files\Python37\lib\_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: (<weakref at 0x000001DCF9A9FE08; to 'Win32Window' at 0x000001DCF96B85F8>,)

进程已结束,退出代码0`

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the stacktrace but do you have any code that caused this?

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity, please let us know if you need anymore help
