### ISSUE TITLE
[bug] pip install gym[atari] - insufficient dependencies

### ISSUE THREAD

**Issue by ikamensh** [openai/gym#2709]
**Describe the bug**
installing gym with atari extras doesn't install `pygame` but it's still imported (erroring out) during render() call of atari env.

**Code example**
`pip install gym[atari]`
`python -c "import gym; env=gym.make('Pong-v4'); env.render()"`

Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python3.8/site-packages/gym/core.py", line 286, in render
    return self.env.render(mode, **kwargs)
  File "python3.8/site-packages/gym/core.py", line 286, in render
    return self.env.render(mode, **kwargs)
  File "python3.8/site-packages/gym/envs/atari/environment.py", line 264, in render
    from gym.envs.classic_control import rendering
  File "python3.8/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
    from gym.envs.classic_control.cartpole import CartPoleEnv
  File "python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

**System Info**
pip freeze                                                                                                 (matari) 11:09:59
ale-py==0.7.4
AutoROM==0.4.2
AutoROM.accept-rom-license==0.4.2
gym==0.23.1
gym-notices==0.0.6
idna==3.3
numpy==1.21.2
requests==2.26.0
torch==1.11.0

python -V                                                                                                      (matari) 11:10:22
Python 3.8.5

** Suggested solution **

Either change import structure or include pygame into dependencies associated with "atari" extra in setup.py

**Comment by ikamensh** [comment]
Reported it to ALE package https://github.com/openai/gym/issues/2709 , probably more relevant there.
