### ISSUE TITLE
ImportError: cannot import name 'Monitor' from 'gym.wrappers'

### ISSUE THREAD

**Issue by lu0909** [openai/gym#2718]
The error message is as follows:
Traceback (most recent call last):
  File "F:\xx\rsa-rl\code\rsa-rl-tutorials-master\rsa-rl-tutorials-master\examples\ksp-agent.py", line 8, in <module>
    from rsarl.envs import DeepRMSAEnv
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl\__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl\utils\__init__.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl\utils\random_seed.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl\__init__.py", line 20, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl\wrappers\__init__.py", line 4, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl\wrappers\monitor.py", line 4, in <module>
ImportError: cannot import name 'Monitor' from 'gym.wrappers' (C:\Users\xx\.conda\envs\pytorch2\lib\site-packages\gym-0.23.1-py3.9.egg\gym\wrappers\__init__.py)

**System Info**
Describe the characteristic of your environment:
 *Gym was installed using pip in anaconda prompt.
 *  OS/version is windows10. 
 * Python version is python3.9.

**Additional context**

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by balisujohn** [comment]
It has been removed; please see https://github.com/openai/gym/issues/2674 for earlier discussion related to this.
