### ISSUE TITLE
[Bug Report] Taxi env.render(mode='rgb_array') broken

### ISSUE THREAD

**Issue by trigaten** [openai/gym#2736]
```python
import gym
env = gym.make("Taxi-v3")
env.reset()
env.render(mode='rgb_array')
```
yields

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/vid/lib/python3.9/site-packages/gym/core.py", line 286, in render
    return self.env.render(**kwargs)
  File "/opt/anaconda3/envs/vid/lib/python3.9/site-packages/gym/core.py", line 286, in render
    return self.env.render(**kwargs)
  File "/opt/anaconda3/envs/vid/lib/python3.9/site-packages/gym/envs/toy_text/taxi.py", line 234, in render
    return self._render_gui(mode)
  File "/opt/anaconda3/envs/vid/lib/python3.9/site-packages/gym/envs/toy_text/taxi.py", line 269, in _render_gui
    self.destination_img = self.destination_img.convert_alpha()
pygame.error: No video mode has been set
```

@younik

**Comment by younik** [comment]
Oh thank you, I experienced this and I forgot to commit the fix

**Comment by Catadanna** [comment]
Hallo I still have the problem, I run;

```
import gym
env = gym.make("Taxi-v3")
env.reset()
env.render(mode='rgb_array')
```

and I get the error : 

`TypeError: render() got an unexpected keyword argument 'mode'`

I work on Jupyter notebook, Ubuntu 20, and gym version 0.26.2. 
I worked on a previous gym version before and everything worked OK. With the new gym version `render` does no longer work.

**Comment by younik** [comment]
> I tried this too:
> 
> ```
> env = gym.make(game, render_mode="rgb_array")
> env.reset()
> env.render()
> ```

Hello, 
This is the correct way to go from gym 0.26. What do you mean by "it renders nothing"? With `rgb_array` render is supposed to return a `np.ndarray`

**Comment by shreya-sk** [comment]
import numpy as np
import random
import gym

env = gym.make("Taxi-v3")
env.reset()  
env.render() 

action_size = env.action_space.n
print("Action size ", action_size)

state_size = env.observation_space.n
print("State size ", state_size)

-------
Running on vscode, macOS
all packages are installed and loaded
Trying to run the above code, but the env.render() results in an error -

  File "/Users/user/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/Users/user/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
  File "/Users/user/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/gym/envs/toy_text/taxi.py", line 284, in render
    return self._render_gui(self.render_mode)
  File "/Users/user/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/gym/envs/toy_text/taxi.py", line 290, in _render_gui
    raise DependencyNotInstalled(
gym.error.DependencyNotInstalled: pygame is not installed, run `pip install gym[toy_text]`

-----

**Comment by trigaten** [comment]
@shreya-sk Recommend you upgrade to [Gymnasium](https://gymnasium.farama.org), the up to date version of Gym.
