### ISSUE TITLE
[Bug Report] Unable to serialize environment

### ISSUE THREAD

**Issue by bentotten** [openai/gym#2840]
In version 0.24.0, the RadSearch environment listed below throws a TypeError for trying to pickle a SwigPyObject, however it executes correctly in version 0.20.0. This is particularly a problem when multithreading using the multiprocessing library, however it can be reproduced by directly pickling also.

Environment: https://github.com/peproctor/radiation_ppo/tree/main/gym_rad_search

**Code example**

Multiprocessing traceback:
```
Traceback (most recent call last):
  File "test_policy.py", line 558, in <module>
    mc_results.append(p.map(func,params)) 
  File "lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle SwigPyObject objects
```

Reproduce with pickling:
```
import gym
import joblib

init_dims = {'bbox': [[0.0,0.0],[2700.0,0.0],[2700.0,2700.0],[0.0,2700.0]], 'area_obs':[200.0,500.0]}
env_name = 'gym_rad_search:RadSearch-v0'
env = gym.make(env_name,**init_dims)
joblib.dump(env, 'pickletest')
```

**System Info**
Ubuntu 20.04.4
gym installed with pip
Python 3.7.12

**Additional context**
Issue is not present in v0.20.0, but appears in v0.24.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Running this code on a macbook, python 3.9 then I have no issues running your example script above.
Are you sure that you are running on gym v0.24.0 as that release is not on pypi, as of this comment.

Could you help narrow down what particular object, joblib or multiprocessing are struggling to pickle? 
I suspect that the issue is originating from the visibility module used as this seems to have been generated by SWIG

**Comment by bentotten** [comment]
Interestingly, this issue appears to be stemming from using Python 3.7

For posterity, Gym 0.24.0 was installed from a .zip with pip, to resolve the `Re-added gym.make("MODULE:ENV") import style that was accidentally removed in v0.22 @arjun-kg` bug in post-0.21.0 versions and multiprocessing in test_policy.py was where the pickling issue was appearing (most likely due to the visibility module, as you mentioned).

**Comment by bentotten** [comment]
Accidental issue close with a finger slip, apologies -
With a fresh ubuntu install and setup, retried with Python 3.9, unfortunately still encountering the issue with both the pickle test code and with the test_policy.py code from project. When gym is rolled back to v0.20.0, both execute successfully; definitely believe it is the visibility module in the custom env you mentioned, though I'm unsure why it pickles in one version and not the other.

Gym 0.24.0 was installed from a .zip with pip, to resolve the `Re-added gym.make("MODULE:ENV") import style that was accidentally removed in v0.22 @arjun-kg` bug in post-0.21.0 versions
Specifically running into issues with multiprocessing, likely due to the visibility module you mentioned;

**Comment by arjun-kg** [comment]
I can reproduce the issue for this env. But I am able to use `joblib.dump` for other environments through `gym.make("MODULE:ENV")` so, there's no problem there. I assume @pseudo-rnd-thoughts is right and the issue is from the `visibility` package.

**Comment by jkterry1** [comment]
Hey, I think the issue here has been resolved so I'm going to close this, please let me know if something changes.
