### ISSUE TITLE
[Bug Report] not able to import gym

### ISSUE THREAD

**Issue by tonystark262** [openai/gym#2944]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
Receiving type error when importing gym library.

**Code example**
`import gym`

**Stack Trace**
`
>>> import gym
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/rl/lib/python3.7/site-packages/gym/__init__.py", line 15, in <module>
    from gym.envs import make, spec, register
  File "/home/ubuntu/anaconda3/envs/rl/lib/python3.7/site-packages/gym/envs/__init__.py", line 5, in <module>
    _load_env_plugins()
  File "/home/ubuntu/anaconda3/envs/rl/lib/python3.7/site-packages/gym/envs/registration.py", line 258, in load_env_plugins
    for plugin in metadata.entry_points(group=entry_point):
TypeError: entry_points() got an unexpected keyword argument 'group'
`

**System Info**
Describe the characteristic of your environment:
 * pip install gym==0.24.1
 * ubuntu 18.04
 * 3.7.13

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by imnotkind** [comment]
I have a same problem too.. also py3.7

**Comment by pseudo-rnd-thoughts** [comment]
Using a fresh install of python 3.7.13 using conda and gym v0.24.1, Im unable to replicate your issue which is strange

**Comment by RedTachyon** [comment]
I can't replicate this either on python 3.7.13 + gym 0.24.1 + ubuntu 20.04, I think it's very likely there's something wrong with your installation.

**Comment by gianlucadecola** [comment]
Working also for me with ubuntu 18.04 and python3.7.13

**Comment by tonystark262** [comment]
fresh install worked!
