### ISSUE TITLE
TypeError when observations are dictionaries 

### ISSUE THREAD

**Issue by lucaslehnert** [openai/gym#2956]
A TypeError is raised when defining an environment with dictionary observations. 

```
$ python test_dict_observations.py 
Traceback (most recent call last):
  File "[...]/gym/test_dict_observations.py", line 53, in <module>
    test_dict_env()
  File "[...]/gym/test_dict_observations.py", line 42, in test_dict_env
    obs, rew, done, truncated, info = env.step(0)
  File "[...]/gym/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "[...]/gym/gym/wrappers/step_api_compatibility.py", line 53, in step
    step_returns = self.env.step(action)
  File "[...]/gym/gym/wrappers/env_checker.py", line 37, in step
    return passive_env_step_check(self.env, action)
  File "[...]/gym/gym/utils/passive_env_checker.py", line 284, in passive_env_step_check
    if np.any(np.isnan(obs)):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

The following script reproduces this.

```
import gym
import numpy as np
from gym.spaces import Discrete, Box, Dict


class TestDictEnv(gym.Env):
    def __init__(self):
        self.actions = [0]
        self.action_space = Discrete(len(self.actions))

        self.observation_space = Dict(
            {
                "img": Box(low=0, high=255, shape=(8, 8, 3), dtype="uint8"),
                "idx": Discrete(4),
            }
        )
        self.reward_range = (0, 1)

    def _get_observation(self):
        return {"img": np.zeros((8, 8, 3), dtype=np.uint8), "idx": 0}

    def reset(self, seed=None, return_info=None, options=None):
        return self._get_observation()

    def step(self, action):
        return self._get_observation(), 0.0, False, False, {}


def test_dict_env():
    gym.envs.register(
        id="TestDictEnv-v0", 
        entry_point="test_dict_observations:TestDictEnv", 
        new_step_api=True
    )
    env = gym.make("TestDictEnv-v0", new_step_api=True)
    obs = env.reset()
    assert isinstance(obs, dict)
    assert isinstance(obs["img"], np.ndarray)
    assert isinstance(obs["idx"], int)

    obs, rew, done, truncated, info = env.step(0)
    assert isinstance(obs, dict)
    assert isinstance(obs["img"], np.ndarray)
    assert isinstance(obs["idx"], int)
    assert isinstance(rew, float)
    assert isinstance(done, bool)
    assert isinstance(truncated, bool)
    assert isinstance(info, dict)


if __name__ == "__main__":
    test_dict_env()
```

**System Info**
Describe the characteristic of your environment:
 * Gym was installed by cloning the current git repo.
 * Windows 10 with WSL 2.0 and Ubuntu 20.04 VM.
 * Python version: 3.9

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, this is being fixed in #2903 already
