### ISSUE TITLE
super().reset(seed=seed) causes TypeError: reset() got an unexpected keyword argument 'seed' error

### ISSUE THREAD

**Issue by Danielr1312** [openai/gym#3088]
Hello, I am attempting to create a custom environment for a maze game. I am using windows 10, Anaconda 4.14.0, python 3.9.12, and I have confirmed via gym.__version__ that I am using gym 0.26.0. I followed the documentation (https://www.gymlibrary.dev/content/environment_creation/) in creating my reset() function. The issue is that when I go to test my environment I get the following error:

```
Traceback (most recent call last):

  File ...\Code\Maze Game\test.py:13 in <module>
    observation, info = env.reset()

  File E:\anaconda3\lib\site-packages\gym\wrappers\time_limit.py:68 in reset
    return self.env.reset(**kwargs)

  File E:\anaconda3\lib\site-packages\gym\envs\classic_control\maze_game.py:48 in reset
    super().reset(seed = seed)

TypeError: reset() got an unexpected keyword argument 'seed'
```

Here is my MazeEnv class (this may have some other bugs since it is my first time making a custom env):
```
import gym
from gym import spaces
import pygame
import numpy as np
import math
import random

class MazeEnv(gym.Env):
    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 4}
    
    
    def __init__(self, render_mode=None, size=10.0):
        self.size = size
        self.window_size = 512
        
        self.observation_space = spaces.Dict(
            {
                "agent": spaces.Box(low=0.0, high=10.0, shape=(2,), dtype=np.float32),
                "target": spaces.Box(low=0.0, high=10.0, shape=(2,), dtype=np.float32)
                }
            )
        
        self.action_space = spaces.Box(low=-math.pi, high=math.pi, shape = (1,))
        
        assert render_mode is None or render_mode in self.metadata["render_modes"]
        self.render_mode = render_mode
        
        self.window = None
        self.clock = None
        
        
    def _get_obs(self):
        return {"agent": self._agent_location, "target": self._target_location}
    
    
    def _get_info(self):
        return {"distance": np.linalg.norm(self._agent_location - self._target_location, ord=2)}
    
    
    def reset(self, seed=None, options=None):
        super().reset(seed = seed)
        
        # agents starting location
        self._agent_location = [0.0, 10.0]
        self._target_location = [10.0, 0.0]
        
        observation = self._get_obs()
        info = self._get_info()
        
        if self.render_mode == "human":
            self._render_frame()
            
        return observation, info
    
    
    def step(self, action):
        terminated = False
        
        angle = random.gauss(action, math.pi/6)
        direction = [math.cos(angle)/2, math.sin(angle)/2]
        
        if self._agent_location[0] + direction[0] < 0.0 or self._agent_location[1] + direction[1] < 0.0 or self._agent_location[0] + direction[0] > 10.0 or self._agent_location[1] + direction[1] > 10.0:
            self._agent_location = [0.0, 10.0] 
        else:
            self._agent_location = self._agent_location + direction
            
        observation = self._get_obs()
        info = self._get_info()
        
        if info["distance"] < 0.5:
            terminated = True
        reward = 1 if terminated else 0
        
        if self.render_mode == "human":
            self._render_frame()
            
        return observation, reward, terminated, False, info
    
    
    def render(self):
        if self.render_mode == "rgb_array":
            return self._render_frame()
        
    def _render_frame(self):
        if self.window is None and self.render_mode == "human":
            pygame.init()
            pygame.display.init()
            self.window = pygame.display.set_mode((self.window_size, self.window_size))
        if self.clock is None and self.render_mode == "human":
            self.clock = pygame.time.Clock()
            
        canvas = pygame.Surface((self.window_size, self.window_size))
        canvas.fill((255, 255, 255))
        
        pygame.draw.circle(canvas, (255, 0, 0), self._target_location, 0.5, draw_top_left=True)
        
        pygame.draw.circle(canvas, (0,0,255), self._agent_location, 0.02)
        
        pygame.draw.line(canvas, (0,0,0), (0.0,0.0), (0.0,10.0))
        pygame.draw.line(canvas, (0,0,0), (0.0,0.0), (10.0,0.0))
        pygame.draw.line(canvas, (0,0,0), (10.0,0.0), (10.0,10.0))
        pygame.draw.line(canvas, (0,0,0), (0.0,10.0), (10.0,10.0))
        
        if self.render_mode == "human":
            # The following line copies our drawings from `canvas` to the visible window
            self.window.blit(canvas, canvas.get_rect())
            pygame.event.pump()
            pygame.display.update()

            # We need to ensure that human-rendering occurs at the predefined framerate.
            # The following line will automatically add a delay to keep the framerate stable.
            self.clock.tick(self.metadata["render_fps"])
        else:  # rgb_array
            return np.transpose(
                np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
            )
        
    def close(self):
        if self.window is not None:
            pygame.display.quit()
            pygame.quit()
```

I test my environment using the following code:
```
import gym

env = gym.make('MazeEnv-v0')

observation, info = env.reset()

for _ in range(1000):
    observation, reward, terminated, truncation, info = env.step(env.action_space.sample())
    
    if terminated:
        observation, info = env.reset()
        
env.close()
```

**Comment by balisujohn** [comment]
For completeness, it would be helpful if you posted the code where you are registering 'MazeEnv-v0'.

**Comment by Danielr1312** [comment]
I registered within __init__.py and placed my environment script within classic_control. Here is the registration:
```
register(
    id='MazeEnv-v0',
    entry_point='gym.envs.classic_control:MazeEnv',
    max_episode_steps=1000,
)
```

**Comment by balisujohn** [comment]
As a final test, what happens when you create the env with
````
env = MazeEnv()
````
instead of using `gym.make()`

**Comment by Danielr1312** [comment]
I get the following error:
```
Traceback (most recent call last):

  File ...\Code\Maze Game\test.py:11 in <module>
    env = MazeEnv()

NameError: name 'MazeEnv' is not defined
```

**Comment by balisujohn** [comment]
ah you have to import it, or you can just declare it in your test file to save time.

**Comment by Danielr1312** [comment]
So I added "from gym.envs.classic_control import MazeEnv" (importing the class), but I am still getting the same seed error

**Comment by balisujohn** [comment]
alright excellent seems like a bug unless I am missing something, I'll see if I can reproduce it.

**Comment by balisujohn** [comment]
I got this error:

````
Traceback (most recent call last):
  File "./tester.py", line 5, in <module>
    observation, info = env.reset()
  File "/home/john/Desktop/gym/gym/wrappers/time_limit.py", line 68, in reset
    return self.env.reset(**kwargs)
  File "/home/john/Desktop/gym/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/john/Desktop/gym/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/john/Desktop/gym/gym/utils/passive_env_checker.py", line 192, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/john/Desktop/gym/gym/envs/classic_control/maze_env.py", line 48, in reset
    info = self._get_info()
  File "/home/john/Desktop/gym/gym/envs/classic_control/maze_env.py", line 37, in _get_info
    return {"distance": np.linalg.norm(self._agent_location - self._target_location, ord=2)}
TypeError: unsupported operand type(s) for -: 'list' and 'list'
`````
And after I changed _agent_location and _target_location to np arrays instead of lists, I got no errors.

**Comment by pseudo-rnd-thoughts** [comment]
Changing all of the python lists to numpy arrays, I got no other errors.
I still don't understand your original error but I guess it is not caused by that

**Comment by balisujohn** [comment]
after calling gym.make, try printing out the class of env, and maybe its attributes. This could be a windows specific bug.

**Comment by Danielr1312** [comment]
print(env) produces:
```
runfile('D:/Desktop/Principe Lab/Divergence to Go/Code/Maze Game/test.py', wdir='D:/Desktop/Principe Lab/Divergence to Go/Code/Maze Game')
<TimeLimit<MazeEnv<MazeEnv-v0>>>
```
print(dir(env)) produces:
```
runfile('D:/Desktop/Principe Lab/Divergence to Go/Code/Maze Game/test.py', wdir='D:/Desktop/Principe Lab/Divergence to Go/Code/Maze Game')
<TimeLimit<MazeEnv<MazeEnv-v0>>>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_action_space', '_elapsed_steps', '_max_episode_steps', '_metadata', '_observation_space', '_reward_range', 'action_space', 'class_name', 'close', 'compute_reward', 'env', 'metadata', 'observation_space', 'render', 'reset', 'reward_range', 'seed', 'spec', 'step', 'unwrapped']
```

**Comment by pseudo-rnd-thoughts** [comment]
Could you run `print(gym.__version__)`

**Comment by Danielr1312** [comment]
```print(gym.__version__)``` returns ```0.26.0```

**Comment by balisujohn** [comment]
right now try print(super()) and also printing the parameters of super().reset which I think you can do using this technique https://stackoverflow.com/questions/582056/getting-list-of-parameter-names-inside-python-function

**Comment by Danielr1312** [comment]
running ```print(super())``` in my test script returns an error:
```
Traceback (most recent call last):

  File ...\Code\Maze Game\test.py:17 in <module>
    print(super())

RuntimeError: super(): no arguments
```

**Comment by balisujohn** [comment]
try print(super()) in the reset function of the maze game env, right before it calls super.reset(seed=seed)

**Comment by Danielr1312** [comment]
this is the output: ```<super: <class 'MazeEnv'>, <MazeEnv object>>```

**Comment by balisujohn** [comment]
yeah definitely add this line
````
        print(super().reset.__code__.co_varnames)
````
in the same place you just did the print(super())

You should get 
````
('self', 'seed', 'options')
````

**Comment by Danielr1312** [comment]
I just get ```('self',)```

**Comment by balisujohn** [comment]
alright how did you install gym. Did you use pip?

**Comment by Danielr1312** [comment]
Yes, I used 'pip install gym==0.26.0'. using conda install via 'conda install -c conda-forge gym' resutls in an older version of gym (0.23.0 if I remember correctly).

**Comment by balisujohn** [comment]
maybe you need to install with the -e flag(not 100% sure).

**Comment by Danielr1312** [comment]
I am not sure what you mean by this, to install my packages I use the anaconda command prompt which installs the package into the current environment

**Comment by pseudo-rnd-thoughts** [comment]
@Danielr1312 Could you join the discord server (https://discord.gg/nHg2JRN489) and we can discuss more there

**Comment by Danielr1312** [comment]
yes

**Comment by RibhavOjha** [comment]
was this issue resolved? i am getting the same problem
