### ISSUE TITLE
[Question] Custom Mujoco humanoid environment fails to initialize with TypeError

### ISSUE THREAD

**Issue by sunshineinsandiego** [openai/gym#3098]
Hi - I am trying to create a custom mujoco humanoid environment based on the [humanoid_standupv4](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoidstandup_v4.py) environment. I am also using a custom xml file based on the standard [humanoid model](https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/humanoid.xml). 

I followed these [directions](https://github.com/ashBabu/Utilities/wiki/Custom-MuJoCo-Environment-in-openai-gym) to create a custom environment package so my directory structure looks like:

```
FolderA/
     setup.py
     FolderB/
           __init__.py
           envs/
                __init__.py
                MyRobotEnv.py
                humanoid_modified.xml
```

`FolderA/setup.py `:
```
from setuptools import setup
setup(name='FolderB',
      version='0.1',
      install_requires=['gym',
                       'numpy'])
```

`FolderB/__init__.py`:
```
from gym.envs.registration import register
register(id='RobotName-v0',
         entry_point='FolderB.envs:HumanoidMod')
```

`FolderB/envs/__init__.py`:
```
from FolderB.envs.MyRobotEnv import HumanoidMod
```

`FolderB/envs/humanoid_modified.xml` is just a slightly modified version of the standard humanoid model:
```
<mujoco model="humanoid_modified">
    <compiler angle="degree" inertiafromgeom="true"/>
    <default>
        <joint armature="1" damping="1" limited="true"/>
        <geom conaffinity="1" condim="1" contype="1" margin="0.001" material="geom" rgba="0.8 0.6 .4 1"/>
        <motor ctrllimited="true" ctrlrange="-.4 .4"/>
    </default>
    <option integrator="RK4" iterations="50" solver="PGS" timestep="0.003">
        <!-- <flags solverstat="enable" energy="enable"/>-->
    </option>
    <size nkey="5" nuser_geom="1"/>
    <visual>
        <map fogend="5" fogstart="3"/>
    </visual>
...
```

`FolderB/envs/MyRobotEnv.py` is just a slightly modified version of the standard humanoid standup v4 environment:
```
import numpy as np

from gym import utils
from gym.envs.mujoco import MujocoEnv
from gym.spaces import Box

class HumanoidMod(MujocoEnv, utils.EzPickle):
    def __init__(self, **kwargs):
        observation_space = Box(
            low=-np.inf, high=np.inf, shape=(378,), dtype=np.float64
        )
        MujocoEnv.__init__(
            self,
            "absolute_path_to_edited_model/humanoid_modified.xml",
            5,
            observation_space = observation_space,
            **kwargs
        )
        utils.EzPickle.__init__(self, **kwargs)

    def _get_obs(self):
        data = self.data
        return np.concatenate(
            [
                data.qpos.flat[2:],
                data.qvel.flat,
                data.cinert.flat,
                data.cvel.flat,
                data.qfrc_actuator.flat,
                data.cfrc_ext.flat,
                data.energy.flat
            ]
        )
...
```

I installed this package:
```
$ cd FolderA 
$ python3 -m pip install -e .
Obtaining file:.../FolderA
  Preparing metadata (setup.py) ... done
...
Installing collected packages: FolderB
  Running setup.py develop for FolderB
Successfully installed FolderB-0.1
```

I then receive the following error when I try to `make` the environment:
```
$ python3
>>> import gym
>>> import FolderB
>>> env = gym.make('RobotName-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 592, in make
    env = env_creator(**_kwargs)
  File ".../FolderA/FolderB/envs/MyRobotEnv.py", line 169, in __init__
    MujocoEnv.__init__(
TypeError: __init__() got an unexpected keyword argument 'observation_space'
```

I'm not sure why making the environment gives an unexpected `observation_space` argument. The source code from the non-customized environment [humanoidstandup_v4.py](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoidstandup_v4.py) has an observation space argument [here](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoidstandup_v4.py#L198), so I'm clearly missing something. Thanks!

**Comment by sunshineinsandiego** [comment]
Uninstalled and re-installed `python3 -m pip install --upgrade gym` which fixed that error. But now receive the following error:

```
>>> import gym
>>> import FolderB
>>> env = gym.make('RobotName-v0')

You appear to be missing MuJoCo.  We expected to find the file here: `~/.mujoco/mujoco210`

I'm running Mac OSX 11.7, and I have Mujoco installed from the pre-built binary ([2.2.2])(https://github.com/deepmind/mujoco/releases) in my `Applications` folder:

```
~ $ cd /Applications/MuJoCo.app 
MuJoCo.app $ 
```

And it works fine:
![Screen Shot 2022-09-25 at 1 40 10 PM](https://user-images.githubusercontent.com/56661595/192164627-59fdc585-9003-4df7-8fb3-46c84d2b987c.png)

I also have `2.2.2` installed via `pip`:
```
(.venv) $ pip list
Package                 Version     Editable project location
----------------------- ----------- ------------------------------------------
...
Box2D                   2.3.10
...
FolderB                 0.1         /.../FolderA
...
glfw                    2.5.3
...
gym                     0.26.1
...
mujoco                  2.2.0
...
```

Should I be creating a sym link from place where python is looking for mujoco: `~/.mujoco/mujoco210`
```
You appear to be missing MuJoCo.  We expected to find the file here: `~/.mujoco/mujoco210`
```

To my `Application/MuJuCo.app` file or the `mujoco2.2.0` package or neither?

Thanks!

**Comment by sunshineinsandiego** [comment]
Added a symlink from `~/.mujoco/mujoco210` to my `pip` package installation location: /.../.venv/lib/python3.8/site-packages/mujoco` using:
```
$ ln -s ~/.mujoco/mujoco210 /.../.venv/lib/python3.8/site-packages/mujoco
```

Which solved the `You appear to be missing MuJoCo.` error, but gave rise to a new error:
```
(.venv) $ python3
Python 3.8.9 (default, Oct 26 2021, 07:25:54) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import FolderB
>>> env = gym.make('RobotName-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 581, in make
    env_creator = load(spec_.entry_point)
  File ".../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 61, in load
    mod = importlib.import_module(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/.../FolderA/FolderB/envs/__init__.py", line 1, in <module>
    from FolderB.envs.MyRobotEnv import HumanoidMod
  File "/.../FolderA/FolderB/envs/MyRobotEnv.py", line 4, in <module>
    from gym.envs.mujoco import MujocoEnv
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv, MuJocoPyEnv  # isort:skip
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 333, in _build_impl
    raise RuntimeError(
RuntimeError: Could not find supported GCC executable.

HINT: On OS X, install GCC 9.x with `brew install gcc@9`. or `port install gcc9`
```

Not sure if this is a `mujoco_py` issue or a `mujoco` issue?

My `mujoco-py` package is up to date:
```
% pip show mujoco-py
Name: mujoco-py
Version: 2.1.2.14
Summary: UNKNOWN
Home-page: https://github.com/openai/mujoco-py
Author: OpenAI Robotics Team
Author-email: robotics@openai.com
License: UNKNOWN
Location: /.../.venv/lib/python3.8/site-packages
Requires: cffi, Cython, fasteners, glfw, imageio, numpy
```

Do I need to be using the old `mujoco210` binaries rather than symlinking to the `mujoco220` pip package?

Thanks!

**Comment by pseudo-rnd-thoughts** [comment]
Testing with the latest gym version, I can't replicate the issue that you report.
I get separate issues but they would occur after this

**Comment by sunshineinsandiego** [comment]
Thanks. I first tried downloading the old `mujoco210` binaries and extracting to `~/.mujoco/mujoco210` which did not fix the error:

```
RuntimeError: Could not find supported GCC executable.
HINT: On OS X, install GCC 9.x with `brew install gcc@9`. or `port install gcc9`
```

Then installed `gcc` via `$brew install gcc@8` and tried to run this again. Got these errors:
```
>>> import gym
>>> import FolderB
>>> env = gym.make('RobotName-v0')
running build_ext
building 'mujoco_py.cymj' extension
/usr/local/bin/gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -DONMAC -I.venv/lib/python3.8/site-packages/mujoco_py -I/.../.venv/lib/python3.8/site-packages/mujoco_py -I/.../.mujoco/mujoco210/include -I/.../.venv/lib/python3.8/site-packages/numpy/core/include -I/.../.venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /.../.venv/lib/python3.8/site-packages/mujoco_py/cymj.c -o /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/temp.macosx-10.14-x86_64-cpython-38/.../.venv/lib/python3.8/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc-8: error: this compiler does not support arm64
gcc-8: error: unrecognized command line option '-iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders'
gcc-8: error: unrecognized command line option '-iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers'
Traceback (most recent call last):
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 178, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 980, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/bin/gcc-8' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 581, in make
    env_creator = load(spec_.entry_point)
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 61, in load
    mod = importlib.import_module(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/.../FolderA/FolderB/envs/__init__.py", line 1, in <module>
    from FolderB.envs.MyRobotEnv import HumanoidMod
  File "/.../FolderA/FolderB/envs/MyRobotEnv.py", line 4, in <module>
    from gym.envs.mujoco import MujocoEnv
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv, MuJocoPyEnv  # isort:skip
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 340, in _build_impl
    so_file_path = super()._build_impl()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 249, in _build_impl
    dist.run_commands()
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/.../.venv/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 149, in build_extensions
    build_ext.build_extensions(self)
  File "/.../.venv/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
    self._build_extensions_serial()
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
    self.build_extension(ext)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 540, in build_extension
    objects = self.compiler.compile(
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 591, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 180, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/local/bin/gcc-8' failed with exit code 1
```

Also tried with `gcc@9` and `gcc@6` and got the same errors.

**Comment by pseudo-rnd-thoughts** [comment]
Does any of the other mujoco -v3 environments work? Could you use the deepmind mujoco which is pre-compiled so shouldn't have this issue

**Comment by sunshineinsandiego** [comment]
The other mujoco environments don't work. I think it has something to do with the python bindings for mujoco-py that are a requirement to integrate mujoco with gym. After following the directions here: https://github.com/openai/mujoco-py, I try to start-up with the standard humanoid-v4 environment. There's a linker error because the compiler seems to building for arm64 despite the fact that I'm using an Intel Mac.

```
>>> env = gym.make('Humanoid-v4')
running build_ext
building 'mujoco_py.cymj' extension
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/local/opt/llvm/include -DONMAC -I.venv/lib/python3.8/site-packages/mujoco_py -I/.../.venv/lib/python3.8/site-packages/mujoco_py -I/.../.mujoco/mujoco210/include -I/.../.venv/lib/python3.8/site-packages/numpy/core/include -I/.../.venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /.../.venv/lib/python3.8/site-packages/mujoco_py/cymj.c -o /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/temp.macosx-10.14-x86_64-cpython-38/.../.venv/lib/python3.8/site-packages/mujoco_py/cymj.o -fopenmp -w
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/local/opt/llvm/include -DONMAC -I.venv/lib/python3.8/site-packages/mujoco_py -I/.../.venv/lib/python3.8/site-packages/mujoco_py -I/.../.mujoco/mujoco210/include -I/.../.venv/lib/python3.8/site-packages/numpy/core/include -I/.../.venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /.../.venv/lib/python3.8/site-packages/mujoco_py/gl/dummyshim.c -o /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/temp.macosx-10.14-x86_64-cpython-38/.../.venv/lib/python3.8/site-packages/mujoco_py/gl/dummyshim.o -fopenmp -w
/usr/local/opt/llvm/bin/clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -Wl,-headerpad,0x1000 -L/usr/local/opt/llvm/lib -I/usr/local/opt/llvm/include /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/temp.macosx-10.14-x86_64-cpython-38/.../.venv/lib/python3.8/site-packages/mujoco_py/cymj.o /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/temp.macosx-10.14-x86_64-cpython-38/.../.venv/lib/python3.8/site-packages/mujoco_py/gl/dummyshim.o -L/.../.mujoco/mujoco210/bin -Wl,-rpath,/.../.mujoco/mujoco210/bin -lmujoco210 -lglfw.3 -o /.../.venv/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_38_macextensionbuilder/lib.macosx-10.14-x86_64-cpython-38/mujoco_py/cymj.cpython-38-darwin.so -fopenmp
ld: warning: ignoring file /.../.mujoco/mujoco210/bin/libmujoco210.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /.../.mujoco/mujoco210/bin/libglfw.3.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/opt/llvm/lib/libomp.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: in '/usr/local/opt/llvm/lib/libunwind.dylib', building for macOS-arm64 but attempting to link with file built for macOS-x86_64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 259, in link
    self.spawn(linker + ld_args)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 980, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 581, in make
    env_creator = load(spec_.entry_point)
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 61, in load
    mod = importlib.import_module(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv, MuJocoPyEnv  # isort:skip
  File "/.../.venv/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 343, in _build_impl
    so_file_path = super()._build_impl()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 249, in _build_impl
    dist.run_commands()
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/.../.venv/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/.../.venv/lib/python3.8/site-packages/mujoco_py/builder.py", line 149, in build_extensions
    build_ext.build_extensions(self)
  File "/.../.venv/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
    self._build_extensions_serial()
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
    self.build_extension(ext)
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 564, in build_extension
    self.compiler.link_shared_object(
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 743, in link_shared_object
    self.link(
  File "/.../.venv/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 261, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1
>>> 

```

**Comment by pseudo-rnd-thoughts** [comment]
This is very weird but I suspect the issue is with your clang installation.
I don't have any issues with the mujoco or mujoco_py on my intel mac

**Comment by pseudo-rnd-thoughts** [comment]
Strangely, this bug occurred for me today. Not sure what I changed, I suspect it is something to do with multiple conda environments with mujoco-py and mujoco installed.

I was able to fix the bug through uninstalling mujoco_py as I was just using mujoco. Hope this fixes your issue?

**Comment by sunshineinsandiego** [comment]
Thanks, I think mujoco-py is necessary in order to interface mujoco with openai gym?

**Comment by pseudo-rnd-thoughts** [comment]
No, mujoco-py is a legacy project by OpenAI for using mujoco but when deepmind brought mujoco they released their own python mujoco called mujoco that does everything better.
However for the v2 and v3 mujoco environments they use mujoco-py with the v4 environments using mujoco

**Comment by sunshineinsandiego** [comment]
Got it. So I uninstalled mujoco-py, re-installed gym, gym[mujoco], and now it works! Thank you!
