### ISSUE TITLE
gym env.render() went wrong with pygame.

### ISSUE THREAD

**Issue by jiapei100** [openai/gym#3108]
My code is as simple as like that:

```console
➜  ~ python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> env = gym.make("Taxi-v3").env
>>> env.reset()
(121, {'prob': 1.0, 'action_mask': array([1, 1, 0, 1, 0, 0], dtype=int8)})
>>> env.render()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/gym/wrappers/order_enforcing.py", line 51, in render
    return self.env.render(*args, **kwargs)
  File "~/.local/lib/python3.10/site-packages/gym/wrappers/env_checker.py", line 53, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "~/.local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py", line 316, in env_render_passive_checker
    result = env.render(*args, **kwargs)
  File "~/.local/lib/python3.10/site-packages/gym/envs/toy_text/taxi.py", line 284, in render
    return self._render_gui(self.render_mode)
  File "~/.local/lib/python3.10/site-packages/gym/envs/toy_text/taxi.py", line 302, in _render_gui
    assert (
AssertionError: Something went wrong with pygame. This should never happen.
>>> 
```

Looks like **pygame windows** is **NOT** initialized. Any suggestions?

**pygame** and **gym** version incompatibility?

```console
➜  ~ pip show pygame
Name: pygame
Version: 2.1.2
Summary: Python Game Development
Home-page: https://www.pygame.org
Author: A community project.
Author-email: pygame@pygame.org
License: LGPL
Location: /home/longervision/.local/lib/python3.10/site-packages
Requires: 
Required-by: 
➜  ~ pip show gym
Name: gym
Version: 0.26.1
Summary: Gym: A universal API for reinforcement learning environments
Home-page: https://www.gymlibrary.dev/
Author: Gym Community
Author-email: jkterry@umd.edu
License: MIT
Location: /home/longervision/.local/lib/python3.10/site-packages
Requires: cloudpickle, gym-notices, numpy
Required-by: 
➜  ~ 
```

**Comment by pseudo-rnd-thoughts** [comment]
Render has been modified to use a new API.
You need to specify during initialisation the render mode
```python
import gym
env = gym.make("Taxi-v3", render_mode="human")
env.reset()
```

For human render mode then this will happen automatically during reset and step so you don't need to call render.
For RGB array render mode you will need to call render get the result.
`rgb_array_list` has additionally been added that returns all of the rgb array since the last reset or render call as a list

**Comment by RedTachyon** [comment]
Worth noting that this should have been caught earlier in the code. I think I added the "This should never happen" line because (I think) with the previous render API, it actually shouldn't have happened except maybe for some cursed situations. In the meantime, passing `render_mode` became mandatory and it has a default value of `None` (used to de facto be `"human"`) 

This, however, is a rather reasonable-looking code, and deserves a proper error message. So thanks for reporting it!
