### ISSUE TITLE
[Bug Report] AttributeError: 'Viewer' object has no attribute 'isopen'

### ISSUE THREAD

**Issue by CodeWithEhtisham** [openai/gym#3163]
i'm trying to run the following code into my Linux server but face this error. I tried to solve this issue but not found anything about it in the internet.

**python version** : 3.8
**linux version** : ubuntu 20.04.5 LTS
**Graphic Card** : NVIDIA Corporation TU104GL [Quadro RTX 5000] / NVIDIA Corporation TU104GL [Quadro RTX 5000]

**Here is my code**
`import gym
#from gym import wrappers
import os
os.environ['PYOPENGL_PLATFORM'] = 'egl'
env = gym.make('CartPole-v0')
env = gym.wrappers.Monitor(env,directory='cartpole-hill/',force=True,write_upon_reset=True)
env.reset()
for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done: break
env.close()`

**Error Message**
`Traceback (most recent call last):
  File "testing.py", line 7, in <module>
    env.reset()
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 56, in reset
    self._after_reset(observation)
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 241, in _after_reset
    self.reset_video_recorder()
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/wrappers/monitor.py", line 267, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py", line 132, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 181, in render
    self.viewer = rendering.Viewer(screen_width, screen_height)
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 88, in __init__
    self.window = get_window(width=width, height=height, display=display)
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 69, in get_window
    config = screen[0].get_best_config()  # selecting the first screen
  File "/home/anayat/.local/lib/python3.8/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
Exception ignored in: <function Viewer.__del__ at 0x7f6d0a7ce820>
Traceback (most recent call last):
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 185, in __del__
    self.close()
  File "/home/anayat/.local/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 99, in close
    if self.isopen and sys.meta_path:
AttributeError: 'Viewer' object has no attribute 'isopen'
`

i'm using x2go client to connect my system then run this code on it. i run this code on terminal as well as jupyter lab.

**Comment by pseudo-rnd-thoughts** [comment]
What gym version are you using, this seems like a very old version so it is difficult to know what is happening

**Comment by CodeWithEhtisham** [comment]
@pseudo-rnd-thoughts  i tried different versions of gym (0.19,0.20,0.21 or 0.26) but facing same issue.

**Comment by pseudo-rnd-thoughts** [comment]
You shouldn't be getting the same issue with the different versions. Monitor was removed in v22 I believe thought I think there is something else happening

**Comment by pseudo-rnd-thoughts** [comment]
Your code doesn't have any line breaks, I suspect the `env.close()` is causing the issue looking at the error stack trace.

**Comment by CodeWithEhtisham** [comment]
@pseudo-rnd-thoughts thanks
