### ISSUE TITLE
[Bug Report] program stuck when creating AsyncVectorEnv

### ISSUE THREAD

**Issue by mothyRose** [openai/gym#3191]
**Describe the bug**
program stuck when creating AsyncVectorEnv.

**Code example**
```
import gym
envs = gym.vector.AsyncVectorEnv([
        lambda: gym.make("CartPole-v1"),
        lambda: gym.make("CartPole-v1"),
        lambda: gym.make("CartPole-v1"),
    ]) 
```
**System Info**
Describe the characteristic of your environment:
 * Describe how Gym was installed (pip, docker, source, ...)
Gym is installed using pip.
``` pip install gym==0.21.0```
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it. 
     Windows
 * Python version 3.9.16

**Additional context**
When running the script, it output the message below and then got stucked.
I am not sure why this happen.. Maybe there is something wrong with my multiprocessing py file?
Maybe this is a stupid envrionment issue made by my own.. Please help... 

```
(base) PS E:\pCloud\tmp\codes\RL\HuggingFace> python tmp.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\pCloud\tmp\codes\RL\HuggingFace\tmp.py", line 2, in <module>
    envs = gym.vector.AsyncVectorEnv([# for parallel execution
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\async_vector_env.py", line 156, in __init__
    process.start()
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function VectorEnv.__del__ at 0x00000150DB6E81F0>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\vector_env.py", line 139, in __del__
    self.close(terminate=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\vector_env.py", line 121, in close
    self.close_extras(**kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\async_vector_env.py", line 320, in close_extras
    if self._state != AsyncState.DEFAULT:
AttributeError: 'AsyncVectorEnv' object has no attribute '_state'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\pCloud\tmp\codes\RL\HuggingFace\tmp.py", line 2, in <module>
    envs = gym.vector.AsyncVectorEnv([# for parallel execution
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\async_vector_env.py", line 156, in __init__
    process.start()
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "E:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function VectorEnv.__del__ at 0x000001F4639191F0>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\vector_env.py", line 139, in __del__
    self.close(terminate=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\vector_env.py", line 121, in close
    self.close_extras(**kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\gym\vector\async_vector_env.py", line 320, in close_extras
    if self._state != AsyncState.DEFAULT:
AttributeError: 'AsyncVectorEnv' object has no attribute '_state'
```
### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)
This issue github.com/openai/gym/issues/1544 seems to be similar, but it's different.

**Comment by mothyRose** [comment]
if I add one line of code ``` if __name__ == "__main__":``` at the beginning, it works fine..
The modified version:
```
import gym
if __name__ == "__main__":
    envs = gym.vector.AsyncVectorEnv([
            lambda: gym.make("CartPole-v1"),
            lambda: gym.make("CartPole-v1"),
            lambda: gym.make("CartPole-v1"),
        ]) 
    print(envs.reset())
```
Is it necessary to initialize the vector environment within the main statement, or is there a way to create the vector environment outside of it? Additionally, I'm unsure if this could be related to a multiprocess issue. As my knowledge on the topic is limited, any information on how to address this issue or resources I should refer to would be greatly appreciated.

**Comment by pseudo-rnd-thoughts** [comment]
This seems to be a known problem with multiprocessing that gym cannot solve to my knowledge. 
Your solution is correct
