### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'register_gym_envs'

### ISSUE THREAD

**Issue by StensonSimon** [openai/gym#3223]
I am getting an error when importing the module gym.

**Code example**
import gym

Error:

Traceback (most recent call last):
  File "/Users/stensonsimon/ReinforcementLearning/main.py", line 1, in <module>
    import gym
  File "/Users/stensonsimon/ReinforcementLearning/venv/lib/python3.9/site-packages/gym/__init__.py", line 13, in <module>
    from gym.envs import make, spec, register
  File "/Users/stensonsimon/ReinforcementLearning/venv/lib/python3.9/site-packages/gym/envs/__init__.py", line 10, in <module>
    _load_env_plugins()
  File "/Users/stensonsimon/ReinforcementLearning/venv/lib/python3.9/site-packages/gym/envs/registration.py", line 276, in load_env_plugins
    fn = plugin.load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: 'NoneType' object has no attribute 'register_gym_envs'

**System Info**
Describe the characteristic of your environment:
 * Describe how Gym was installed (pip, docker, source, ...) using pip
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it. 
 I am using MacOS 
 * Python version - 3.9

### Checklist

- [Y] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
This is a weird bug, what other modules have you got installed? 
`pip freeze`

What version of gym are you using?

**Comment by StensonSimon** [comment]
I am using gym 0.26.2. I tried 0.21.0 as well but had the same error.
 
 pip freeze gave the following:
- absl-py==1.4.0
- ale-py==0.7.4
- AutoROM==0.6.1
- AutoROM.accept-rom-license==0.6.1
- cachetools==5.3.1
- certifi==2023.5.7
- charset-normalizer==3.1.0
- click==8.1.3
- cloudpickle==2.2.1
- contourpy==1.1.0
- cycler==0.11.0
- Farama-Notifications==0.0.4
- filelock==3.12.2
- fonttools==4.40.0
- google-auth==2.20.0
- google-auth-oauthlib==1.0.0
- grpcio==1.54.2
- gym==0.26.2
- gym-notices==0.0.8
- gymnasium==0.28.1
- idna==3.4
- importlib-metadata==4.13.0
- importlib-resources==5.12.0
- jax-jumpy==1.0.0
- Jinja2==3.1.2
- kiwisolver==1.4.4
- Markdown==3.4.3
- markdown-it-py==3.0.0
- MarkupSafe==2.1.3
- matplotlib==3.7.1
- mdurl==0.1.2
- mpmath==1.3.0
- networkx==3.1
- numpy==1.25.0
- oauthlib==3.2.2
- opencv-python==4.7.0.72
- packaging==23.1
- pandas==2.0.2
- Pillow==9.5.0
- protobuf==4.23.3
- psutil==5.9.5
- pyasn1==0.5.0
- pyasn1-modules==0.3.0
- pygame==2.4.0
- Pygments==2.15.1
- pyparsing==3.1.0
- python-dateutil==2.8.2
- pytz==2023.3
- requests==2.31.0
- requests-oauthlib==1.3.1
- rich==13.4.2
- rsa==4.9
- six==1.16.0
- stable-baselines3==1.8.0
- sympy==1.12
- tensorboard==2.13.0
- tensorboard-data-server==0.7.1
- torch==2.0.1
- tqdm==4.65.0
- typing_extensions==4.6.3
- tzdata==2023.3
- urllib3==1.26.16
- Werkzeug==2.3.6
- zipp==3.15.0

**Comment by pseudo-rnd-thoughts** [comment]
There is something strange happening with ale-py, could you uninstall and reinstall ale-py.
Otherwise, I would create a new virtual environment and try again and see what happens

**Comment by StensonSimon** [comment]
HI, That solved the issue.
I uninstalled ale-py-0.7.4 and installed 0.8.1 which no longer throwed the error.
Thanks for the help!
