### ISSUE TITLE
Unable to install stablebaselines3[extra]

### ISSUE THREAD

**Issue by sandeep-selvaraj** [openai/gym#3226]
Hi, 

I'm trying to install stablebaselines3[extra]. But I get an issue with AutoROM
`-oauthlib<1.1,>=0.5->tensorboard>=2.9.1->stable-baselines3[extra]) (3.2.2)
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for AutoROM.accept-rom-license (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      copying AutoROM.py -> build/lib
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64
      creating build/bdist.linux-x86_64/wheel
      copying build/lib/AutoROM.py -> build/bdist.linux-x86_64/wheel
      running install_egg_info
      running egg_info
      writing AutoROM.accept_rom_license.egg-info/PKG-INFO
      writing dependency_links to AutoROM.accept_rom_license.egg-info/dependency_links.txt
      writing requirements to AutoROM.accept_rom_license.egg-info/requires.txt
      writing top-level names to AutoROM.accept_rom_license.egg-info/top_level.txt
      reading manifest file 'AutoROM.accept_rom_license.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'AutoROM.accept_rom_license.egg-info/SOURCES.txt'
      Copying AutoROM.accept_rom_license.egg-info to build/bdist.linux-x86_64/wheel/AutoROM.accept_rom_license-0.6.1-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/requests/compat.py", line 11, in <module>
          import chardet
      ModuleNotFoundError: No module named 'chardet'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/sase718e/.conda/envs/game_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/sase718e/.conda/envs/game_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/sase718e/.conda/envs/game_env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 378, in run
          self.run_command("install")
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 11, in run
        File "/tmp/pip-install-7uypmwb2/autorom-accept-rom-license_5182180c0d584b728e1c7b2006e7d45f/AutoROM.py", line 14, in <module>
          import requests
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/requests/__init__.py", line 45, in <module>
          from .exceptions import RequestsDependencyWarning
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/requests/exceptions.py", line 9, in <module>
          from .compat import JSONDecodeError as CompatJSONDecodeError
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/requests/compat.py", line 13, in <module>
          import charset_normalizer as chardet
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 24, in <module>
          from .api import from_bytes, from_fp, from_path
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/charset_normalizer/api.py", line 5, in <module>
          from .cd import (
        File "/tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/charset_normalizer/cd.py", line 9, in <module>
          from .md import is_suspiciously_successive_range
      ImportError: /tmp/pip-build-env-g9hf__sd/overlay/lib/python3.9/site-packages/charset_normalizer/md.cpython-39-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects
`
I have stablebaselines==2.0.0 installed, but it doesn't seem to train my model on the GPU, hence I tried to upgrade the version but I'm facing the above issue. Does anyone have any idea on how to resolve it?

**System Info**
I'm trying to run it on High Performance Computing system through a remote connection (SSH)

**Comment by pseudo-rnd-thoughts** [comment]
The error message says `ModuleNotFoundError: No module named 'chardet'`
I would try install chardet

**Comment by sandeep-selvaraj** [comment]
@pseudo-rnd-thoughts chardet is installed. 
![image](https://github.com/openai/gym/assets/53923656/02f533ca-7e2c-44cf-bd52-0b37dccdb26c)
