### ISSUE TITLE
[Bug Report] Vectorized Environments

### ISSUE THREAD

**Issue by histmeisah** [openai/gym#3229]
**Describe the bug**
I try to use Vectorized Environmets by gym,but some bugs occur in following:
Traceback (most recent call last):
  File "D:\pythoncode\TextStarCraft2\sc2_rl_agent\starcraftenv_test\gym_test\gym_test1.py", line 20, in <module>
    main()
  File "D:\pythoncode\TextStarCraft2\sc2_rl_agent\starcraftenv_test\gym_test\gym_test1.py", line 12, in main
    observations, rewards, terminated,truncated, infos = envs.step(actions)
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\vector_env.py", line 137, in step
    return self.step_wait()
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py", line 321, in step_wait
    obs, rew, terminated, truncated, info = result
TypeError: cannot unpack non-iterable NoneType object
D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py:457: UserWarning: WARN: Calling `close` while waiting for a pending call to `step` to complete.
  logger.warn(
Exception ignored in: <function AsyncVectorEnv.__del__ at 0x000001D3543CD5A0>
Traceback (most recent call last):
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py", line 546, in __del__
    self.close(terminate=True)
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\vector_env.py", line 205, in close
    self.close_extras(**kwargs)
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py", line 461, in close_extras
    function(timeout)
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py", line 311, in step_wait
    if not self._poll(timeout):
  File "D:\ide\conda\envs\sc2env\lib\site-packages\gym\vector\async_vector_env.py", line 493, in _poll
    if pipe.closed or (not pipe.poll(delta)):
  File "D:\ide\conda\envs\sc2env\lib\multiprocessing\connection.py", line 262, in poll
    return self._poll(timeout)
  File "D:\ide\conda\envs\sc2env\lib\multiprocessing\connection.py", line 333, in _poll
    _winapi.PeekNamedPipe(self._handle)[0] != 0):
BrokenPipeError: [WinError 109] 管道已结束。

**Code example**
here is my test code:
import gym

def main():
    envs = gym.vector.make("CartPole-v1", num_envs=3)
    observations = envs.reset()
    print("Observations: ", observations)

    actions = [envs.action_space.sample() for _ in range(envs.num_envs)]
    print("Actions: ", actions)

    observations, rewards, terminated,truncated, infos = envs.step(actions)
    print("Observations: ", observations)
    print("Rewards: ", rewards)
    print("Dones: ", terminated)
    print("Infos: ", infos)

if __name__ == "__main__":
    main() 

**System Info**
Describe the characteristic of your environment:
 * system:win10
 * gym                      0.26.2
 * gym-notices         0.0.8
 * python                 3.10

**Additional context**
when i read this document:https://www.gymlibrary.dev/content/vectorising/
i find the example code of Vectorized Environments still not change and the example code seems too simple for show the vector environment

**Comment by pseudo-rnd-thoughts** [comment]
Could you try
`actions = envs.action_space.sample()` or `actions = [envs.single_action_space.sample() for _ in range(envs.num_envs)]`
