### ISSUE TITLE
[Question] How can I install gym[classic_control] on Windows 11 pipenv?

### ISSUE THREAD

**Issue by nomocp** [openai/gym#3243]
I'm attempting to install gym[classic_control] module on Windows 11. I've already install pygame, setuptools, gym. Here is the command 
`pipenv install gym[classic_control]`

And error raised:

> Installing gym[classic_control]...
> Resolving gym...
> Installing...
> [=== ] Installing gym...[31m[1mError: [0m An error occurred while installing [32mgym[0m!
> Error text: Requirement already satisfied: gym in c:\users\x\.virtualenvs\deep_q_learning-xcn67gjw\lib\site-packages     
> (from -r c:\users\x\appdata\local\temp\pipenv-rx9y7e16-requirements\pipenv-qgo9flxa-requirement.txt (line 1)) (0.26.2)   
> Requirement already satisfied: numpy>=1.18.0 in c:\users\x\.virtualenvs\deep_q_learning-xcn67gjw\lib\site-packages (from 
> gym->-r c:\users\x\appdata\local\temp\pipenv-rx9y7e16-requirements\pipenv-qgo9flxa-requirement.txt (line 1)) (1.24.3)    
> Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\x\.virtualenvs\deep_q_learning-xcn67gjw\lib\site-packages  
> (from gym->-r c:\users\x\appdata\local\temp\pipenv-rx9y7e16-requirements\pipenv-qgo9flxa-requirement.txt (line 1))       
> (2.2.1)
> Requirement already satisfied: gym-notices>=0.0.4 in c:\users\x\.virtualenvs\deep_q_learning-xcn67gjw\lib\site-packages  
> (from gym->-r c:\users\x\appdata\local\temp\pipenv-rx9y7e16-requirements\pipenv-qgo9flxa-requirement.txt (line 1))       
> (0.0.8)
> Collecting pygame==2.1.0 (from gym->-r
> c:\users\x\appdata\local\temp\pipenv-rx9y7e16-requirements\pipenv-qgo9flxa-requirement.txt (line 1))
>   Using cached pygame-2.1.0.tar.gz (5.8 MB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
> 
> [36m  error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [77 lines of output]
> 
> 
>       WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
>       Using WINDOWS configuration...
> 
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\setup.py", line 
> 388, in <module>
>           buildconfig.config.main(AUTO_CONFIG)
>         File
> "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\buildconfig\config.py", line 
> 234, in main
>           deps = CFG.main(**kwds)
>                  ^^^^^^^^^^^^^^^^
>         File
> "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\buildconfig\config_win.py",  
> line 511, in main
>           return setup_prebuilt_sdl2(prebuilt_dir)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File
> "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\buildconfig\config_win.py",  
> line 471, in setup_prebuilt_sdl2
>          DEPS.configure()
>        File
> "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\buildconfig\config_win.py",  
> line 336, in configure
>          from . import vstools
>         File
> "C:\Users\x\AppData\Local\Temp\pip-install-nr8dilzt\pygame_1a6ace498d8f4ef19456b6a85632b977\buildconfig\vstools.py", line
> 11, in <module>
>           compiler.initialize()
>         File "C:\Users\x\.virtualenvs\Deep_Q_Learning-xcN67gjw\Lib\site-packages\setuptools\_distutils\msvc9compiler.py",
> line 403, in initialize
>           vc_env = query_vcvarsall(VERSION, plat_spec)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\x\.virtualenvs\Deep_Q_Learning-xcN67gjw\Lib\site-packages\setuptools\_distutils\msvc9compiler.py",
> line 281, in query_vcvarsall
>           raise DistutilsPlatformError("Unable to find vcvarsall.bat")
>       distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
>       Making dir :prebuilt_downloads:
>       Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip 13d952c333f3c2ebe9b7bc0075b4ad2f784e7584
>       Unzipping :prebuilt_downloads\SDL2-devel-2.0.16-VC.zip:
>       Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
> 137f86474691f4e12e76e07d58d5920c8d844d5b
>       Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
>       Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
> 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
>       Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
>       Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
> 9097148f4529cf19f805ccd007618dec280f0ecc
>       Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
>       Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
>       Unzipping :prebuilt_downloads\jpegsr9d.zip:
>       Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed   
>       Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
>       copying into .\prebuilt-x64
>       Path for SDL: prebuilt-x64\SDL2-2.0.16
>       ...Library directory for SDL: prebuilt-x64/SDL2-2.0.16/lib/x64
>       ...Include directory for SDL: prebuilt-x64/SDL2-2.0.16/include
>       Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
>       ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
>       ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
>       Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
>       ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
>       ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
>       Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
>       ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
>       ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
>       Path for PORTMIDI: prebuilt-x64
>       ...Library directory for PORTMIDI: prebuilt-x64/lib
>       ...Include directory for PORTMIDI: prebuilt-x64/include
>       DLL for SDL2: prebuilt-x64/SDL2-2.0.16/lib/x64/SDL2.dll
>       DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
>       DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
>       DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
>       DLL for portmidi: prebuilt-x64/lib/portmidi.dll
>       Path for FREETYPE not found. >      ...Found include dir but no library dir in prebuilt-x64.
>       Path for PNG not found.
>       ...Found include dir but no library dir in prebuilt-x64.
>       Path for JPEG not found.
>       ...Found include dir but no library dir in prebuilt-x64.
>       DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll
> 
>       ---
>       For help with compilation see:
>           https://www.pygame.org/wiki/CompileWindows
>       To contribute to pygame development see:
>           https://www.pygame.org/contribute.html
>       ---
>       
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> [0m
> This is likely caused by a bug in [32mgym[0m. Report this to its maintainers.
> Installation Failed

**Comment by pseudo-rnd-thoughts** [comment]
The issue is with Pygame not gym, see 
```
Path for FREETYPE not found. > ...Found include dir but no library dir in prebuilt-x64.
Path for PNG not found.
...Found include dir but no library dir in prebuilt-x64.
Path for JPEG not found.
...Found include dir but no library dir in prebuilt-x64.
DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

 ---
  For help with compilation see:
      https://www.pygame.org/wiki/CompileWindows
  To contribute to pygame development see:
      https://www.pygame.org/contribute.html
  ---
```

**Comment by code-admirer** [comment]
@nocpinmylf do you have setuptools installed ?
