### ISSUE TITLE
AttributeError: attempted to get missing private attribute '_domain_file'

### ISSUE THREAD

**Issue by emoLeader** [openai/gym#3276]
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    test_stats, global_stats = test_planner(
  File "/home/lzy/scenegraph-planners/ploi/traineval.py", line 162, in test_planner
    env.domain, state, timeout=timeout, domain_file_global=env._domain_file
  File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/core.py", line 235, in __getattr__
    raise AttributeError(
AttributeError: attempted to get missing private attribute '_domain_file'

how？please

**Comment by pseudo-rnd-thoughts** [comment]
change to env.unwrapped._domain_file

**Comment by emoLeader** [comment]
I really appreciate your help. It means a lot to me!!!!
