### ISSUE TITLE
Couldn't find lunar Lander v3

### ISSUE THREAD

**Issue by tahirbb** [openai/gym#3306]
Hi, 
I installed gymnasium ( pip install "gymnasium[all]" ) and tried to run lunar lander getting this error. What I missed here?

```console

~/anaconda3/envs/marlbase/lib/python3.10/site-packages/gymnasium/envs/box2d$ python lunar_lander.py 
Traceback (most recent call last):
  File "/home/thr/anaconda3/envs/marlbase/lib/python3.10/site-packages/gymnasium/envs/box2d/lunar_lander.py", line 884, in <module>
    env = gym.make("LunarLander-v3", render_mode="rgb_array")
  File "/home/thr/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 741, in make
    env_spec = _find_spec(id)
  File "/home/thr/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 527, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/thr/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 424, in _check_version_exists
    raise error.VersionNotFound(message)
gymnasium.error.VersionNotFound: Environment version `v3` for environment `LunarLander` doesn't exist. It provides versioned environments: [ `v2` ].

```

**Comment by pseudo-rnd-thoughts** [comment]
What version of Gymnasium are you using? ``gymnasium.__version__``

**Comment by tahirbb** [comment]
Hi,

```code
Python 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium
>>> print (gymnasium.__version__)
0.29.1
>>> 
```

**Comment by pseudo-rnd-thoughts** [comment]
Lunar lander is only on v1.0.0, otherwise use Lunar lander v2

**Comment by tahirbb** [comment]
Thanks for your time
