### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by crizCraig** [openai/gym#358]
Currently three failures in test_envs_semantics on [Windows only](https://ci.appveyor.com/project/crizCraig/gym/build/1.0.24/job/w8g77eegiawqrpmq)

```
======================================================================
FAIL: gym.envs.tests.test_envs_semantics.test_env_semantics:98
EnvSpec(FrozenLake8x8-v0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gym\gym\envs\tests\test_envs_semantics.py", line 88, in test_env_semantics
    assert rollout_dict[spec.id]['observations'] == observations_now, 'Observations not equal for {}'.format(spec.id)
AssertionError: Observations not equal for FrozenLake8x8-v0
-------------------- >> begin captured logging << --------------------
gym.envs.tests.test_envs_semantics: INFO: Testing rollout for FrozenLake8x8-v0 environment...
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: gym.envs.tests.test_envs_semantics.test_env_semantics:335
EnvSpec(FrozenLake-v0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gym\gym\envs\tests\test_envs_semantics.py", line 88, in test_env_semantics
    assert rollout_dict[spec.id]['observations'] == observations_now, 'Observations not equal for {}'.format(spec.id)
AssertionError: Observations not equal for FrozenLake-v0
-------------------- >> begin captured logging << --------------------
gym.envs.tests.test_envs_semantics: INFO: Testing rollout for FrozenLake-v0 environment...
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: gym.envs.tests.test_envs_semantics.test_env_semantics:462
EnvSpec(Pendulum-v0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gym\gym\envs\tests\test_envs_semantics.py", line 90, in test_env_semantics
    assert rollout_dict[spec.id]['rewards'] == rewards_now, 'Rewards not equal for {}'.format(spec.id)
AssertionError: Rewards not equal for Pendulum-v0
-------------------- >> begin captured logging << --------------------
gym.envs.tests.test_envs_semantics: INFO: Testing rollout for Pendulum-v0 environment...
--------------------- >> end captured logging << ---------------------
--------------------------------
```

The rewards and observations that are unequal are non-empty.
Also see #99.

**Comment by christopherhesse** [comment]
Closing in favor of #99
