### ISSUE TITLE
Stochastic `GLException` test failure on Windows

### ISSUE THREAD

**Issue by crizCraig** [openai/gym#359]
This seems to happen ~25% of time on Windows.

```
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: gym.envs.tests.test_envs.test_env:520
EnvSpec(OffSwitchCartpole-v0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gym\gym\envs\tests\test_envs.py", line 71, in test_env
    env.render(mode=mode)
  File "C:\projects\gym\gym\core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "C:\projects\gym\gym\envs\classic_control\cartpole.py", line 149, in _render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "C:\projects\gym\gym\envs\classic_control\rendering.py", line 84, in render
    self.window.dispatch_events()
  File "c:\python27_32\lib\site-packages\pyglet\window\win32\__init__.py", line 593, in dispatch_events
    self.dispatch_pending_events()
  File "c:\python27_32\lib\site-packages\pyglet\window\win32\__init__.py", line 609, in dispatch_pending_events
    event[0](*event[1:])
  File "c:\python27_32\lib\site-packages\pyglet\window\win32\__init__.py", line 887, in _event_size
    self.dispatch_event('on_resize', self._width, self._height)
  File "c:\python27_32\lib\site-packages\pyglet\window\__init__.py", line 1155, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "c:\python27_32\lib\site-packages\pyglet\event.py", line 365, in dispatch_event
    if getattr(self, event_type)(*args):
  File "c:\python27_32\lib\site-packages\pyglet\window\__init__.py", line 722, in on_resize
    gl.glOrtho(0, width, 0, height, -1, 1)
  File "c:\python27_32\lib\site-packages\pyglet\gl\lib.py", line 104, in errcheck
    raise GLException(msg)
GLException: invalid value
-------------------- >> begin captured stderr << ---------------------
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "c:\python27_32\lib\site-packages\pyglet\window\win32\__init__.py", line 617, in f
    result = event_handler(msg, wParam, lParam)
  File "c:\python27_32\lib\site-packages\pyglet\window\win32\__init__.py", line 887, in _event_size
    self.dispatch_event('on_resize', self._width, self._height)
  File "c:\python27_32\lib\site-packages\pyglet\window\__init__.py", line 1155, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "c:\python27_32\lib\site-packages\pyglet\event.py", line 365, in dispatch_event
    if getattr(self, event_type)(*args):
  File "c:\python27_32\lib\site-packages\pyglet\window\__init__.py", line 722, in on_resize
    gl.glOrtho(0, width, 0, height, -1, 1)
  File "c:\python27_32\lib\site-packages\pyglet\gl\lib.py", line 104, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: invalid value
--------------------- >> end captured stderr << ----------------------
----------------------------------------------------------------------
Ran 2125 tests in 2.641s
FAILED (errors=1
```

[Example on AppVeyor](https://ci.appveyor.com/project/crizCraig/gym/build/job/l2y0cedekpqa55b1)
Also see #99.

**Comment by christopherhesse** [comment]
Is there a script that would reproduce this reliably on windows?

**Comment by christopherhesse** [comment]
Closing due to lack of activity.
