### ISSUE TITLE
video rendering doesn't work on windows

### ISSUE THREAD

**Issue by 222464** [openai/gym#4]
Hello,

I am able to run the gym on my windows machine, for the most part. However, despite ffmpeg being installed and added to the PATH (and detected), I get the following error when trying to render video:

`Clearing 2 monitor files from previous run (because force=True was provided)
[2016-04-27 16:31:49,407] Starting new video recorder writing to C:\tmp\random-agent-results\openaigym.video.0.17236.video000000.mp4
/dev/stdin: No such file or directory
Traceback (most recent call last):
  File "Gym.py", line 76, in <module>
    ob = env.reset()
  File "C:\Users\BlackBox\Anaconda3\envs\py27\lib\site-packages\gym-0.0.3-py2.7.egg\gym\core.py", line 87, in reset
    self.monitor._after_reset(observation)
  File "C:\Users\BlackBox\Anaconda3\envs\py27\lib\site-packages\gym-0.0.3-py2.7.egg\gym\monitoring\monitor.py", line 237, in _after_reset
    self.video_recorder.capture_frame()
  File "C:\Users\BlackBox\Anaconda3\envs\py27\lib\site-packages\gym-0.0.3-py2.7.egg\gym\monitoring\video_recorder.py", line 111, in capture_frame
    self._encode_image_frame(frame)
  File "C:\Users\BlackBox\Anaconda3\envs\py27\lib\site-packages\gym-0.0.3-py2.7.egg\gym\monitoring\video_recorder.py", line 161, in _encode_image_frame
    self.encoder.capture_frame(frame)
  File "C:\Users\BlackBox\Anaconda3\envs\py27\lib\site-packages\gym-0.0.3-py2.7.egg\gym\monitoring\video_recorder.py", line 284, in capture_frame
    self.proc.stdin.write(frame.tobytes())
IOError: [Errno 22] Invalid argument
[2016-04-27 16:31:50,016] VideoRecorder encoder exited with status 1`

When not using video, and explicitly calling env.render(), it works fine.

It seems to be a Linux-specific thing? Is there a quick way to fix this to get it to run on windows?

**Comment by jonasschneider** [comment]
Hi, sorry, we currently aren't testing anything on Windows specifically. However, we'd love to help with getting everything to work there (and will definitely merge changes that fix compatibility).

If you have the time, could you try just replacing `/dev/stdin` with `-` in the `video_recorder.py` line mentioned in your log? This particular issue might be an easy fix.

**Comment by 222464** [comment]
Yes, it seems to work now. Thanks!
