### ISSUE TITLE
Can't roll back numpy; was not uninstalled

### ISSUE THREAD

**Issue by dendisuhubdy** [openai/gym#411]
```
creating build/temp.linux-x86_64-2.7/numpy/core/src/multiarray

creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/multiarray

creating build/temp.linux-x86_64-2.7/numpy/core/src/private

compile options: '-DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c'

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/compiled_base.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/sequence.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/descriptor.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/getset.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/arrayobject.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/methods.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/datetime_busdaycal.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/vdot.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/array_assign_array.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/buffer.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/refcount.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/convert.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/shape.c

x86_64-linux-gnu-gcc: numpy/core/src/multiarray/numpymemoryview.c

x86_64-linux-gnu-gcc: build/src.linux-x86_64-2.7/numpy/core/src/multiarray/lowlevel_strided_loops.c

x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.

x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.

error: Command "x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c build/src.linux-x86_64-2.7/numpy/core/src/multiarray/lowlevel_strided_loops.c -o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/multiarray/lowlevel_strided_loops.o" failed with exit status 4

----------------------------------------
  Can't roll back numpy; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kCQwwZ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/numpy
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

```

**Comment by tlbtlbtlb** [comment]
This is an issue with gcc and Numpy, not gym.

You might try upgrading your version of gcc.

If that doesn't fix it, ask the Numpy people at http://www.scipy.org/scipylib/bug-report.html

**Comment by lekhamohan** [comment]
@dendisuhubdy  Hello! Please comment below if you had this issue solved

**Comment by xy1377660586** [comment]
I am facing similar problem 
Can't roll back scipy; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RnYuvZ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/scipy
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66: ordinal

any ideas?

Thanks
