### ISSUE TITLE
Can't render when using Tensorflow

### ISSUE THREAD

**Issue by pavitrakumar78** [openai/gym#418]
Hi,

I am not able to call the render function anywhere when I am using tensorflow. I am working on a DQN implementation using TF and Open-AI gym. My code is [here](https://gist.github.com/pavitrakumar78/560c2d750a58da9ee29ffbc4200d8d05). 

Python: 2.7.6
Pyglet version: 1.2.4
TF version: 0.12.0-rc1 (GPU enabled)
OS: Ubuntu 14.04 LTS 64Bit

glxinfo | grep 'version' output:

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.3.0 NVIDIA 367.57
OpenGL core profile shading language version string: 4.30 NVIDIA via Cg compiler
OpenGL version string: 4.5.0 NVIDIA 367.57
OpenGL shading language version string: 4.50 NVIDIA

```

Full error:

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Initializing Atari...
[2016-12-11 15:53:12,476] Making new env: SpaceInvaders-v0
Atari initialized.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 660
major: 3 minor: 0 memoryClockRate (GHz) 1.0845
pciBusID 0000:01:00.0
Total memory: 1.94GiB
Free memory: 1.77GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 660, pci bus id: 0000:01:00.0)
Network created!
Loading model from:  /home/pavitrakumar/Desktop/DQN Agents/simple TF mem repl/tmp/model.ckpt
Starting the training!
======================================
Training finished. It's time to watch!
Traceback (most recent call last):
  File "space_invaders_TF.py", line 355, in <module>
    game.render()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/atari/atari_env.py", line 119, in _render
    from gym.envs.classic_control import rendering
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 1817, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 505, in __init__
    config = screen.get_best_config(template_config)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/base.py", line 161, in get_best_config
    configs = self.get_matching_configs(template)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/xlib.py", line 179, in get_matching_configs
    configs = template.match(canvas)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py", line 29, in match
    have_13 = info.have_version(1, 3)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/glx_info.py", line 89, in have_version
    client = [int(i) for i in client_version.split('.')]
ValueError: invalid literal for int() with base 10: 'None'

```

**Comment by pavitrakumar78** [comment]
Fixed by calling render before any tensorflow initializations. Reference from: #403

**Comment by act65** [comment]
similar problem. https://github.com/tensorflow/tensorflow/issues/7486#issuecomment-279894075

**Comment by tlbtlbtlb** [comment]
Probably better to 
```
import pyglet
import tensorflow as tf
```
at the top of the main file, to ensure correct import order.
