### ISSUE TITLE
python 3.5.2 cannot import universe: __init__() got an unexpected keyword argument 'timestep_limit'

### ISSUE THREAD

**Issue by nojvek** [openai/gym#445]
```
universe git:(master) python3
Python 3.5.2 (default, Jun 29 2016, 13:42:46) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/noj/Documents/dev/git/universe/universe/__init__.py", line 120, in <module>
    timestep_limit=500,
  File "/usr/local/lib/python3.5/site-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'
```

Seems like a recent commit broke the contract between universe and gym. 

https://github.com/openai/gym/commit/68c66b9a00bfd6a25336898887a373f0bf2555da

**Comment by tlbtlbtlb** [comment]
Fixed in https://github.com/openai/gym/commit/4cec14144b2a190e88b346231cb1ba3f5df759c8. Thanks for reporting

**Comment by murdo25** [comment]
I'm still getting that error with python Python 2.7.6 but not in 3.4 for some reason.

Traceback (most recent call last):
  File "try1.py", line 2, in <module>
    import universe # register Universe environments into Gym
  File "/usr/local/lib/python2.7/dist-packages/universe/__init__.py", line 120, in <module>
    timestep_limit=500,
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'

**Comment by tlbtlbtlb** [comment]
Are you sure you installed updated versions of both universe and gym for 2.7?

**Comment by ultimatehrishi** [comment]
Hi , I have completed installation but import universe gives error


(universe) hrishikesh@DeepState:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hrishikesh/universe/universe/__init__.py", line 86, in <module>
    timestep_limit=500,
  File "/home/hrishikesh/anaconda3/envs/universe/lib/python3.6/site-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/home/hrishikesh/anaconda3/envs/universe/lib/python3.6/site-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'
>>>

**Comment by nojvek** [comment]
I wonder if the latest modules have been published to pip.

**Comment by tlbtlbtlb** [comment]
@nottombrown Can you check that the timestep_limit changes are published to PyPI?
