### ISSUE TITLE
Error when trying to monitor training process

### ISSUE THREAD

**Issue by JunhongXu** [openai/gym#452]
Hi

I am using this code to monitor my training process but I encountered an error when using the following code. I do not know if this is a bug or I am using Monitor class wrong.

`def __init(...):
    self.monitor = Monitor(self.env, os.path.join(directory, self.env_name), force=True)`

```
def evaluate():
    for epoch in range(self.max_test_epoch):
        state = self.monitor.reset().reshape(1, -1)
        done = False
        while not done:
                self.monitor.render()
                action = self.action(state.reshape(1, -1))
                state, reward, done, _ = self.monitor.step(action)
                reward_per_epoch += reward
    # close the monitor
    self.monitor.close()
```

But I got a numpy array is not json serializable error.

The trace is :

> Traceback (most recent call last):
  File "/Users/JunhongXu/Desktop/Python Project/DRL-Tensorflow/main.py", line 29, in <module>
    agent.fit()
  File "/Users/JunhongXu/Desktop/Python Project/DRL-Tensorflow/src/agent/ddpg.py", line 124, in fit
    self.evaluate()
  File "/Users/JunhongXu/Desktop/Python Project/DRL-Tensorflow/src/agent/ddpg.py", line 144, in evaluate
    self.monitor.close()
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/site-packages/gym/core.py", line 191, in close
    self._close()
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/site-packages/gym/wrappers/monitoring.py", line 38, in _close
    self._monitor.close()
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/site-packages/gym/monitoring/monitor_manager.py", line 189, in close
    self.stats_recorder.close()
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/site-packages/gym/monitoring/stats_recorder.py", line 88, in close
    self.flush()
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/site-packages/gym/monitoring/stats_recorder.py", line 102, in flush
    }, f)
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/Users/JunhongXu/anaconda/envs/tensorflow/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([-119.38552581]) is not JSON serializable
Error in atexit._run_exitfuncs:

I found that in `flush` method in monitoring/stats_recorder.py module trying to serialize `self.episode_rewards`, which is a numpy array, as json format:

   ```
 def flush(self):
        if self.closed:
            return

        with atomic_write.atomic_write(self.path) as f:
            json.dump({
                'initial_reset_timestamp': self.initial_reset_timestamp,
                'timestamps': self.timestamps,
                'episode_lengths': self.episode_lengths,
                'episode_rewards': self.episode_rewards,
                'episode_types': self.episode_types,
            }, f)
```

I solved it by convert `self.rewards` into floating number in `save_complete` method:

```
   def save_complete(self):
        if self.steps is not None:
            self.episode_lengths.append(self.steps)
            self.episode_rewards.append(float(self.rewards))
            self.timestamps.append(time.time())
```

I am not sure if this a bug or I am using the Monitor class wrong?

**Comment by tlbtlbtlb** [comment]
Thanks for reporting
