### ISSUE TITLE
Uploading results throws with "Must provide a training episode batch."

### ISSUE THREAD

**Issue by mbz** [openai/gym#465]
This is my first time uploading as score, so please forgive me if I doing something dumb.

I've recorded a few episodes of my agent playing Pong and when I try to upload the results, this is the error I'm getting:

```
[2017-01-20 16:17:12,319] [PongDeterministic-v0] Uploading videos of 2 training episodes (1914 bytes)
[2017-01-20 16:17:12,924] [PongDeterministic-v0] Creating evaluation object from /home/mbz/experiment-1/ with training video
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mbz/projects/gym/gym/scoreboard/api.py", line 83, in upload
    evaluation = _upload(training_dir, algorithm_id, writeup, benchmark_run_id, api_key, ignore_open_monitors)
  File "/home/mbz/projects/gym/gym/scoreboard/api.py", line 132, in _upload
    api_key=api_key,
  File "/home/mbz/projects/gym/gym/scoreboard/client/resource.py", line 323, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/home/mbz/projects/gym/gym/scoreboard/client/api_requestor.py", line 41, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/home/mbz/projects/gym/gym/scoreboard/client/api_requestor.py", line 157, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/home/mbz/projects/gym/gym/scoreboard/client/api_requestor.py", line 55, in handle_api_error
    rbody, rcode, resp, rheaders)
gym.error.InvalidRequestError: Request req_1bxhqlHEQ6eydV8sYMS1Kg: Must provide a training episode batch.

```

**Comment by tlbtlbtlb** [comment]
The scoreboard is intended to measure the rate of learning. So you have to run it on the entire training run (usually 10000+ episodes), not just a few episodes to demonstrate an already-trained agent. For final score it takes the average of the last 100 episodes (a "batch").

**Comment by mbz** [comment]
Thanks Trevor, 
is that the case for all the results in scoreboard? For some of them it seems the agents have been evaluated after the training. For example, please look at [this](https://gym.openai.com/evaluations/eval_8L7SV59nSW6GGbbP3N4G6w).

Another question is whether you are aware of any performance degradation while monitoring the training? The `MonitorManager` class seems to be heavy weight.

**Comment by tlbtlbtlb** [comment]
Yes, that's clearly a pre-trained network. I'll flag it for review.

You can make MonitorManager less slow by reducing the frequency of video recording. See 
https://github.com/openai/gym/blob/master/gym/monitoring/monitor_manager.py#L64

**Comment by mbz** [comment]
Thanks for the help :)
