### ISSUE TITLE
CarRacing env.render(), env.reset() and env.step() failing when run on the SSH rooted machine

### ISSUE THREAD

**Issue by Instassa** [openai/gym#538]
My code for CarRacing runs smoothly on a GPU self-managed machine, when I launch it directly.
However when I try to run it on the same machine from my laptop through ssh (same machine, same code, same conda environment activated) it throws the following error:

```
Using TensorFlow backend.
[2017-03-22 16:02:51,037] Making new env: CarRacing-v0
Traceback (most recent call last):
  File "CarRacing_newQlearning_Conv.py", line 378, in <module>
    Rewards, Times, CummulativeRewards, Weights = Q_learning(model, epochs = 1, stages = 10, gamma = 0.975, epsilon = 0.99, batchSize = 100, buffer = 3000, randSeed = 42, replay = None)
  File "CarRacing_newQlearning_Conv.py", line 220, in Q_learning
    env.render()
  File "/home/marija/gym/gym/core.py", line 153, in render
    return self._render(mode=mode, close=close)
  File "/home/marija/gym/gym/core.py", line 285, in _render
    return self.env.render(mode, close)
  File "/home/marija/gym/gym/core.py", line 153, in render
    return self._render(mode=mode, close=close)
  File "/home/marija/gym/gym/envs/box2d/car_racing.py", line 332, in _render
    from gym.envs.classic_control import rendering
  File "/home/marija/gym/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 493, in __init__
    display = get_platform().get_default_display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1765, in get_default_display
    return pyglet.canvas.get_display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/canvas/xlib.py", line 83, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

And when the I comment out the env.render() part it throws this error:
```
[2017-03-22 15:42:15,277] Making new env: CarRacing-v0
[2017-03-22 15:42:15,303] Clearing 4 monitor files from previous run (because force=True was provided)
Track generation: 1111..1393 -> 282-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1133..1420 -> 287-tiles track
Traceback (most recent call last):
  File "CarRacing_newQlearning_Conv.py", line 378, in <module>
    Rewards, Times, CummulativeRewards, Weights = Q_learning(model, epochs = 1, stages = 10, gamma = 0.975, epsilon = 0.99, batchSize = 100, buffer = 3000, randSeed = 42, replay = None)
  File "CarRacing_newQlearning_Conv.py", line 236, in Q_learning
    state = env.reset(); state = state.reshape((1,96,96,3))
  File "/home/marija/gym/gym/core.py", line 107, in reset
    return self._reset()
  File "/home/marija/gym/gym/wrappers/monitoring.py", line 40, in _reset
    observation = self.env.reset()
  File "/home/marija/gym/gym/core.py", line 107, in reset
    return self._reset()
  File "/home/marija/gym/gym/wrappers/time_limit.py", line 49, in _reset
    return self.env.reset()
  File "/home/marija/gym/gym/core.py", line 107, in reset
    return self._reset()
  File "/home/marija/gym/gym/envs/box2d/car_racing.py", line 292, in _reset
    return self._step(None)[0]
  File "/home/marija/gym/gym/envs/box2d/car_racing.py", line 304, in _step
    self.state = self._render("state_pixels")
  File "/home/marija/gym/gym/envs/box2d/car_racing.py", line 332, in _render
    from gym.envs.classic_control import rendering
  File "/home/marija/gym/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 493, in __init__
    display = get_platform().get_default_display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1765, in get_default_display
    return pyglet.canvas.get_display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home/marija/anaconda3/envs/tensorflow-gpu-3.5/lib/python3.5/site-packages/pyglet/canvas/xlib.py", line 83, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

When I remove env.reset() and make state just equal to zeros it starts complaining about the env.step().

Any ideas or solutions for this problem?

**Comment by olegklimov** [comment]
I guess it's not a CarRacing problem. Please try to run `xclock` first. If you're running it on the same machine that has X server, `export DISPLAY=:0` may help.

**Comment by charan223** [comment]
Is this problem solved for anyone? I get same error if I login using ssh or ssh -X
