### ISSUE TITLE
cant import mujoco env

### ISSUE THREAD

**Issue by prakashyadav008** [openai/gym#540]
I am having issues importing environments from mujoco and Box2d and the same error pops up for all the mujoco environments and Box2d as shown below:

Mujoco:

>>> env = gym.make('Ant-v1')
[2017-03-24 22:48:33,295] Making new env: Ant-v1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/gym/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/prakash/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/prakash/gym/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/prakash/gym/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/prakash/gym/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/prakash/gym/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/mujoco_py/__init__.py", line 2, in <module>
    init_config()
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/mujoco_py/config.py", line 33, in init_config
    raise error.MujocoDependencyError('To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujoco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.')
mujoco_py.error.MujocoDependencyError: To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujoco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.

Box2d:

>>> env = gym.make('LunarLander-v2')
[2017-03-24 23:10:15,305] Making new env: LunarLander-v2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/gym/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/prakash/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/prakash/gym/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/prakash/gym/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/prakash/gym/gym/envs/box2d/__init__.py", line 1, in <module>
    from gym.envs.box2d.lunar_lander import LunarLander
  File "/home/prakash/gym/gym/envs/box2d/lunar_lander.py", line 4, in <module>
    import Box2D
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/Box2D/Box2D.py", line 32, in <module>
    _Box2D = swig_import_helper()
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/Box2D/Box2D.py", line 28, in swig_import_helper
    _mod = imp.load_module('_Box2D', fp, pathname, description)
  File "/home/prakash/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/prakash/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/prakash/anaconda3/lib/python3.6/site-packages/Box2D/_Box2D.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm

System info:
operating system: Ubuntu 16.04 LTS
graphic driver: Nvidia 375.39
Ram :4gb
any suggestions ?

**Comment by tlbtlbtlb** [comment]
For Mujoco, did you follow the instructions at the URL it prints?

For Box2D, that error is probably due to compiling with a different version of python than you're currently using. `pip install --ignore-installed box2d-py` will probably fix it.

**Comment by prakashyadav008** [comment]
thanks, I havnt tried the steps for Mujoco Ill do it but will after the trial will i have to do it again or get the paid services.
and for the Box2D I am still getting the same error's after running the command `pip install --ignore-installed box2d-py` .

**Comment by tlbtlbtlb** [comment]
The Pachi error looks like the same problem as the Box2D error: you compiled for a different version of Python. Fix is the same: `pip install --ignore-installed pachi-py`.

**Comment by prakashyadav008** [comment]
@tlbtlbtlb Box2D and BoardGames environments from both are working now thanks for the suggestion.

**Comment by gte620v** [comment]
@prakashyadav008 What did you do to fix the issue?  You said `--ignore-installed` didn't work for you and it doesn't work for me either.  Any pointers?
