### ISSUE TITLE
`GLIBCXX_3.4.20' not found while using atari environments

### ISSUE THREAD

**Issue by prakashyadav008** [openai/gym#543]
i am trying to use the atari environments but for all the environments i am gettting the same issue as below:

>>> env = gym.make('Assault-v0')
[2017-03-26 13:31:13,199] Making new env: Assault-v0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/gym/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/prakash/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/prakash/gym/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/prakash/gym/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/prakash/gym/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/prakash/gym/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/prakash/anaconda3/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 13, in <module>
    'ale_interface/build/libale_c.so'))
  File "/home/prakash/anaconda3/lib/python3.6/ctypes/__init__.py", line 422, in LoadLibrary
    return self._dlltype(name)
  File "/home/prakash/anaconda3/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/prakash/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/prakash/anaconda3/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)

any suggestion ?

System info:
operating system: Ubuntu 16.04 LTS
graphic driver: Nvidia 375.39 (installed from the Ubuntu repository)
Ram :4gb

**Comment by prakashyadav008** [comment]
found the solution updating the libgcc worked for me using:
`conda install libgcc`
