### ISSUE TITLE
AttributeError: Fourrooms instance has no attribute 'unwrapped'

### ISSUE THREAD

**Issue by cardwing** [openai/gym#569]
I have defined my own environment by following the instructions in the documentation of gym. However, when I use env = gym.make('Fourrooms-v0') to load the environment and it raises the following error:

[2017-04-27 10:52:42,250] Making new env: Fourrooms-v0
Traceback (most recent call last):
  File "transfer.py", line 201, in <module>
    env = gym.make('Fourrooms-v0')
  File "/home/cardwing/gym/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/cardwing/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/cardwing/gym/gym/envs/registration.py", line 89, in make
    env.unwrapped.spec = self
AttributeError: Fourrooms instance has no attribute 'unwrapped'

I don't know why this happens since in old version of gym it can work well. Can anyone help me? Thanks a lot!
Regards,
Cardwing

**Comment by tlbtlbtlb** [comment]
Perhaps your env isn't a subclass of gym.Env? You should define it like this:
```
class Fourrooms(core.Env):
```

**Comment by cardwing** [comment]
Thanks for your help! The problem has been solved. More details can be seen in https://github.com/jeanharb/option_critic/issues/4.
