### ISSUE TITLE
Blackjack-v0 errors with universal starter agent

### ISSUE THREAD

**Issue by martinstuder** [openai/gym#603]
Running the Blackjack-v0 environment with the universal starter agent (`python train.py --num-workers 6 --env-id Blackjack-v0 --log-dir /tmp/blackjack`) yields an error `TypeError: tuple indices must be integers, not tuple`:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/mstuder/Documents/Projects/openai/universe-starter-agent/a3c.py", line 93, in run
    self._run()
  File "/home/mstuder/Documents/Projects/openai/universe-starter-agent/a3c.py", line 102, in _run
    self.queue.put(next(rollout_provider), timeout=600.0)
  File "/home/mstuder/Documents/Projects/openai/universe-starter-agent/a3c.py", line 112, in env_runner
    last_state = env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 107, in reset
    return self._reset()
  File "/home/mstuder/Documents/Projects/openai/universe/universe/wrappers/vectorize.py", line 41, in _reset
    observation_n = self.env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 107, in reset
    return self._reset()
  File "/home/mstuder/Documents/Projects/openai/universe/universe/vectorized/vectorize_filter.py", line 28, in _reset
    observation_n = self.env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 107, in reset
    return self._reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 310, in _reset
    return self._observation(observation)
  File "/home/mstuder/Documents/Projects/openai/universe-starter-agent/envs.py", line 187, in _observation
    return [_process_frame42(observation) for observation in observation_n]
  File "/home/mstuder/Documents/Projects/openai/universe-starter-agent/envs.py", line 169, in _process_frame42
    frame = frame[34:34+160, :160]
TypeError: tuple indices must be integers, not tuple
```

**Comment by martinstuder** [comment]
This may actually not be an issue but just a misunderstanding from my side on the requirements to a gym environment that can be run against the universe starter agent. I therefore opened an appropriate [stackoverflow question](https://stackoverflow.com/questions/44276677/openai-gym-environment-for-universe-starter-agent).

**Comment by christopherhesse** [comment]
The universe project isn't being supported anymore, sorry about that!
