### ISSUE TITLE
MoJoCo env could not be setup

### ISSUE THREAD

**Issue by citihome** [openai/gym#62]
>>> import gym
>>> env=gym.make('Humanoid-v0')
[2016-05-07 00:16:38,716] Making new env: Humanoid-v0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gym/envs/registration.py", line 76, in make
    return spec.make()
  File "gym/envs/registration.py", line 51, in make
    cls = load(self._entry_point)
  File "gym/envs/registration.py", line 13, in load
    result = entry_point.load(False)
  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 2229, in load
  File "/usr/local/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 2235, in resolve
ImportError: No module named None

**Comment by JKCooper2** [comment]
MuJoCo environments are all at v1 now: https://gym.openai.com/envs#mujoco
You should just need to change Humanoid-v0 to Humanoid-v1

**Comment by joschu** [comment]
@citihome, are you still getting this error with v1 and the latest version of `gym`?

**Comment by gdb** [comment]
(Closing for now.)
