### ISSUE TITLE
Trying to upload result but fail

### ISSUE THREAD

**Issue by chaotaklon** [openai/gym#620]
Hi,

My script is the following:
import gym
gym.upload('/home/alanmain/Reinforcement_Learning/out/cartpole-q', api_key='<<<masked>>>')

and I got this error:
[2017-06-12 20:21:50,772] [CartPole-v0] Uploading 400 episodes of training data
Traceback (most recent call last):
  File "upload.py", line 2, in <module>
    gym.upload('/home/alanmain/Reinforcement_Learning/out/cartpole-q', api_key='<<<masked>>>')
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/api.py", line 54, in upload
    skip_videos=skip_videos,
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/api.py", line 137, in _upload
    env_info, training_episode_batch, training_video = upload_training_data(training_dir, api_key=api_key, skip_videos=skip_videos)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/api.py", line 193, in upload_training_data
    training_episode_batch = upload_training_episode_batch(data_sources, episode_lengths, episode_rewards, episode_types, initial_reset_timestamps, timestamps, api_key, env_id=env_id)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/api.py", line 211, in upload_training_episode_batch
    file_upload = resource.FileUpload.create(purpose='episode_batch', api_key=api_key)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/client/resource.py", line 358, in create
    'post', url, params=params)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/client/api_requestor.py", line 40, in request
    method.lower(), url, params, headers)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/client/api_requestor.py", line 132, in request_raw
    method, abs_url, headers, post_data)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/client/http_client.py", line 64, in request
    self._handle_request_error(e, method, url)
  File "/usr/lib/python2.7/site-packages/gym-0.9.1-py2.7.egg/gym/scoreboard/client/http_client.py", line 94, in _handle_request_error
    raise error.APIConnectionError(msg)
gym.error.APIConnectionError: Unexpected error communicating with OpenAI Gym. It looks like there's probably a configuration issue locally.  If this problem persists, let
us know at gym@openai.com.

(Network error: A AttributeError was raised with error message 'X509' object has no attribute '_x509')

I have googled the msg but found nothing, so open a new issue.

Thanks.

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
