### ISSUE TITLE
Error Monitoring Training "could not find any manifest files"

### ISSUE THREAD

**Issue by qfettes** [openai/gym#646]
When trying to upload, I get the error that I have not closed the experiment yet; however it is closed on the previous line.

Here is the code:
```
    env = gym.make('FrozenLake-v0')
    env.monitor.start('frozenlake-experiment-1', force=True)

    Q = np.zeros((env.observation_space.n, env.action_space.n))
    updateCounts = np.zeros((env.observation_space.n, env.action_space.n))

    deltas = []
    averageReturn = 0
    lastHalfAverage = 0
    for episode in xrange(NUM_EPISODES):

        s = env.reset()

        biggest_change = 0
        while True:
            a = np.argmax(Q[s, :])
            a = random_action(a, env, EPSILON)

            old_qsa = Q[s, a]

            s2, r, done, info = env.step(a)

            #alpha = (ALPHA/(updateCounts[s, a]+1))
            alpha = ALPHA
            updateCounts[s, a] += 1

            a2 = np.argmax(Q[s2, :])
            maxNext = Q[s2, a2]
            Q[s, a] = old_qsa + alpha*(r + GAMMA*maxNext - old_qsa)
            biggest_change = max(biggest_change, np.abs(old_qsa - Q[s, a]))

            updateCounts[s, a] = updateCounts[s, a] + 1

            s=s2
            a=a2

            if(done):
                averageReturn = averageReturn + (r-averageReturn)/(episode+1)
                if episode > NUM_EPISODES - 500:
                    lastHalfAverage = lastHalfAverage + (r-lastHalfAverage)/(episode-NUM_EPISODES/2)
                EPSILON *= EPSILON_DECAY
                if episode%10000 == 0:
                    print "Episode: ", episode
                    print 'Epsilon: ', EPSILON
                    print 'Average Return: ', averageReturn
                    if episode > NUM_EPISODES - 500:
                        print 'Last 1% Average Return: ', lastHalfAverage
                break
        deltas.append(biggest_change)

    env.close()

    gym.upload('cartpole-experiment-1', api_key='I-removed-my-API-Key')
```

And Here is the error message:

> Traceback (most recent call last):
  File "/home/quintin/PycharmProjects/MonteCarlo/Q.py", line 79, in <module>
    gym.upload('cartpole-experiment-1', api_key='sk_hSfoPutQSKW4gHovkHuJRg')
  File "/usr/local/lib/python2.7/dist-packages/gym/scoreboard/api.py", line 54, in upload
    skip_videos=skip_videos,
  File "/usr/local/lib/python2.7/dist-packages/gym/scoreboard/api.py", line 137, in _upload
    env_info, training_episode_batch, training_video = upload_training_data(training_dir, api_key=api_key, skip_videos=skip_videos)
  File "/usr/local/lib/python2.7/dist-packages/gym/scoreboard/api.py", line 176, in upload_training_data
    (HINT: this usually means you did not yet close() your env.monitor and have not yet exited the process. You should call 'env.monitor.start(training_dir)' at the start of training and 'env.close()' at the end, or exit the process.)'''.format(training_dir))
gym.error.Error: Could not find any manifest files in cartpole-experiment-1.
(HINT: this usually means you did not yet close() your env.monitor and have not yet exited the process. You should call 'env.monitor.start(training_dir)' at the start of training and 'env.close()' at the end, or exit the process.)

**Comment by qfettes** [comment]
Whoops it was my mistake in the directory I was uploading.
Issue closed
