### ISSUE TITLE
Doom Dependency 

### ISSUE THREAD

**Issue by dookdick** [openai/gym#662]
Hi Guys

I'm getting an error from running an AI program on Doom environment, and I just couldn't figure it out how to solve this issue. My program always shows dependency error even I'm pretty sure that everything is installed and updated.

The following is what I got after running an ai.py (a tutorial on Doom); 

...............................................................................................

Traceback (most recent call last):

File "", line 11, in  from ppaquette_gym_doom.wrappers.action_space import ToDiscrete

File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/init.py", line 4, in  from .doom_env import DoomEnv, MetaDoomEnv

File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in  "with 'pip install doom_py.)'".format(e))

DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)' 

...............................................................................................

Once I tried 'pip install doom_py', it showed "Requirement already satisfied" on both doom_py and numpy.

I've also successfully installed the following lines as mentioned in ppaquette/gym-doom github;

pip install gym-pull 

pip install ppaquette-gym-doom

Anyway, I received another error when trying to run the DoomCorridor-v0 environment as shown;  

...............................................................................................

# to load and run the DoomCorridor env

import gym 

import ppaquette_gym_doom 

env = gym.make('ppaquette/DoomCorridor-v0')

Traceback (most recent call last):

File "", line 2, in  import ppaquette_gym_doom

File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/init.py", line 4, in  from .doom_env import DoomEnv, MetaDoomEnv

File "/home/nat/anaconda3/lib/python3.6/site-packages/ppaquette_gym_doom/doom_env.py", line 18, in  "with 'pip install doom_py.)'".format(e))

DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)' 

...............................................................................................

# an alternative way to load and run the DoomCorridor env

import gym 

import gym_pull 

gym_pull.pull('github.com/ppaquette/gym-doom') 

env = gym.make('ppaquette/DoomCorridor-v0')

Traceback (most recent call last):

File "", line 2, in  import gym_pull

File "/home/nat/anaconda3/lib/python3.6/site-packages/gym_pull/init.py", line 43, in  gym.upload = gym_pull.scoreboard.api.upload

AttributeError: module 'gym_pull' has no attribute 'scoreboard' ...............................................................................................

The following line was also run in terminal as mentioned, but they're all set and updated, and same error still existed; 

apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip git

Truly appreciate all your thought in advance

Nat

**Comment by dookdick** [comment]
The whole things need to run on python 2.7. That's it.

**Comment by djbyrne** [comment]
I am having the same issue as you but nothing seems to be working. I have tried running it on 2.7.12, 2.7.6 and 3.5

Is there anything else you did to get it working?

**Comment by dookdick** [comment]
Hi djbyrne

Let's look at all the steps provided under "the red star Answer" by Igor. (you might have to search down to the bottom, and also probably click "load more answer" just to make it shown)

https://www.udemy.com/artificial-intelligence-az/learn/v4/questions/2584938
Hope this help.

**Comment by prabhat428** [comment]
Hi dookdick 
i also get same error , but still didn't find a solution
