### ISSUE TITLE
Installing "gym[atari]" on Google Cloud ML

### ISSUE THREAD

**Issue by kimardenmiller** [openai/gym#669]
Failing with:
`Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-build-AD77v0/atari-py/setup.py", line 36, in <module> tests_require=['nose2'] File "/usr/lib/python2.7/distutils/core.py", line 151, in setup dist.run_commands() File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands self.run_command(cmd) File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command cmd_obj.run() File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run return orig.install.run(self) File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run self.run_command('build') File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command self.distribution.run_command(command) File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command cmd_obj.run() File "/tmp/pip-build-AD77v0/atari-py/setup.py", line 16, in run subprocess.check_call(cmd) File "/usr/lib/python2.7/subprocess.py", line 540, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2`

Also tried installing atari_py directly, same result.

I don't need visualize / render anything.  Just trying to save weights.

GCS setup.py:
```
REQUIRED_PACKAGES = [
          'pillow',
          'cmake',
          'gym[atari]',
          'numpy',
          'keras',
          'h5py',
          'tensorflow'
]
```

**Comment by perduta** [comment]
Having same issue here.

**Comment by Adri31** [comment]
Same problem. Someone has any idea ?

**Comment by drallensmith** [comment]
By installing directly, do you mean running `make build -C atari_py/ale_interface -j 7` directly? If so, any additional info?

**Comment by perduta** [comment]
@drallensmith I believe there is no way to run make (nor install `cmake`) on ML Engine job.

**Comment by drallensmith** [comment]
Then how is the program running make, at least from the looks of things? I am admittedly quite unfamiliar with ML Engine.

**Comment by kimardenmiller** [comment]
To my eye it's something in atari_py that is failing.

**Comment by MyHumbleSelf** [comment]
Still failing…

**Comment by sfujiwara** [comment]
Is it a problem of Google Cloud ML Engine?

**Comment by Amicond** [comment]
The same problem

**Comment by christopherhesse** [comment]
We have atari_py binaries now, so please file a new issue if this problem still exists.

**Comment by leigh-johnson** [comment]
Hi! First, thank you for all of the work on this project! 

I'm still experiencing this issue in Google Cloud ML engine, even after updating my dependencies to use the `atari_py` package. I'm using the Tensorflow 1.13.1 runtime.

```
requirements = ['cmake', 'gym[atari]', 'tensorflow',
                'numpy', 'agents']
```
```

2019-06-01 11:33:20.360 PDT
master-replica-0
copying atari_py/package_data.txt -> build/lib.linux-x86_64-2.7/atari_py
 
2019-06-01 11:33:20.360 PDT
master-replica-0
running build_ext
2019-06-01 11:33:20.360 PDT
master-replica-0
make: Entering directory '/tmp/pip-install-6cB3jG/atari-py/build/lib.linux-x86_64-2.7/atari_py/ale_interface'
2019-06-01 11:33:20.360 PDT
master-replica-0
mkdir -p build && cd build && cmake .. && make -j4
2019-06-01 11:33:20.360 PDT
master-replica-0
/bin/sh: 1: cmake: not found
2019-06-01 11:33:20.360 PDT
master-replica-0
Makefile:4: recipe for target 'build' failed
2019-06-01 11:33:20.361 PDT
master-replica-0
make: *** [build] Error 127
2019-06-01 11:33:20.361 PDT
master-replica-0
make: Leaving directory '/tmp/pip-install-6cB3jG/atari-py/build/lib.linux-x86_64-2.7/atari_py/ale_interface'
2019-06-01 11:33:20.361 PDT
master-replica-0
Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
2019-06-01 11:33:20.361 PDT
master-replica-0
----------------------------------------
2019-06-01 11:33:20.361 PDT
master-replica-0
ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-6cB3jG/atari-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-q_2EcX/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-6cB3jG/atari-py/
2019-06-01 11:33:20.473 PDT
master-replica-0
Command '['pip', 'install', '--user', u'zero_to_rl_skiing-0.0.1.tar.gz']' returned non-zero exit status 1.
2019-06-01 11:33:20.475 PDT
master-replica-0
Module completed; cleaning up.
2019-06-01 11:33:20.475 PDT
master-replica-0
Clean up finished.
2019-06-01 11:33:37.802 PDT
The replica master 0 exited with a non-zero status of 1. Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-6cB3jG/atari-py/setup.py", line 42, in <module> tests_require=['nose2'] File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup return distutils.core.setup(**attrs) File "/usr/lib/python2.7/distutils/core.py", line 151, in setup dist.run_commands() File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands self.run_command(cmd) File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command cmd_obj.run() File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run return orig.install.run(self) File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run self.run_command('build') File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command self.distribution.run_command(command) File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command cmd_obj.run() File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run self.run_command(cmd_name) File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command self.distribution.run_command(command) File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command cmd_obj.run() File "/tmp/pip-install-6cB3jG/atari-py/setup.py", line 17, in run subprocess.check_call(cmd, cwd=self.build_lib) File "/usr/lib/python2.7/subprocess.py", line 541, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2 To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=702148157522&resource=ml_job%2Fjob_id%2Fskiing_v0_20190601_113047&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22skiing_v0_20190601_113047%22
2019-06-01 11:37:11.214 PDT
Job failed.
No newer entries found matching current filter.   
```

As a work-around, I'm going to try creating a custom Docker container for OpenAI Gym use in Google Cloud ML Engine. The steps to do this are outlined here: https://cloud.google.com/ml-engine/docs/using-containers#using_gpus_with_custom_containers

Wish me luck! Will share if successful.

**Comment by Michalos88** [comment]
@leigh-johnson - You can simply install CMAKE and other non-pip dependencies by defining subprocesses in `setup.py` file. 
```
import setuptools
from setuptools import find_packages
from setuptools import setup
import subprocess
from distutils.command.build import build as _build

class build(_build):
  """A build command class that will be invoked during package install.
    The package built using the current setup.py will be staged and later
    installed in the worker using `pip install package'. This class will be
    instantiated during install for this specific scenario and will trigger
    running the custom commands specified.
    """
  sub_commands = _build.sub_commands + [('CustomCommands', None)]


# The list of required libraries is taken from:
# https://github.com/openai/gym#installing-everything
_LIBS = ('python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools'
         ' xorg-dev python-opengl libboost-all-dev libsdl2-dev swig').split()

CUSTOM_COMMANDS = [
    ['apt-get', 'update'],
    ['apt-get', 'install', '-y'] + _LIBS,
]

class CustomCommands(setuptools.Command):
  """A setuptools Command class able to run arbitrary commands."""

  def initialize_options(self):
    pass

  def finalize_options(self):
    pass

  def RunCustomCommand(self, command_list):
    print 'Running command: %s' % command_list
    p = subprocess.Popen(
        command_list,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT)
    # Can use communicate(input='y\n'.encode()) if the command run requires
    # some confirmation.
    stdout_data, _ = p.communicate()
    print 'Command output: %s' % stdout_data
    if p.returncode != 0:
      raise RuntimeError(
          'Command %s failed: exit code: %s' % (command_list, p.returncode))

  def run(self):
    for command in CUSTOM_COMMANDS:
      self.RunCustomCommand(command)
``` 


**References:**
See complete `setup.py`[ here](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/blogs/rl-on-gcp/DQN_Breakout/rl_on_gcp/setup.py)
See Googles Tutorial on deploying Gym on Cloud ML [here](https://cloud.google.com/blog/products/ai-machine-learning/deep-reinforcement-learning-on-gcp-using-hyperparameters-and-cloud-ml-engine-to-best-openai-gym-games)

**Comment by leigh-johnson** [comment]
@Michalos88 Thank you for the comprehensive example and additional references! 🙇‍♀
