### ISSUE TITLE
can not pip install -e '.[all]'

### ISSUE THREAD

**Issue by jude2014** [openai/gym#67]
I don't know what happens, pip install -e .  is okay, but when I execute pip install '.[all]', it says:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 280, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 136, in from_editable
    editable_req, default_vcs)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1146, in parse_editable
    '__placeholder__' + extras
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'__placeh'"

**Comment by gdb** [comment]
This indicates an old pip! Try `pip install --ignore-installed pip` to upgrade?

**Comment by jude2014** [comment]
it does work! Thank you so much!
