### ISSUE TITLE
module 'gym' has no attribute 'make'

### ISSUE THREAD

**Issue by akhilesh9999** [openai/gym#670]
I am aware there are several other posts online about this topic, but I really am confused about how ubuntu works. In order to complete an independed Deep learning project, I need to use OpenAI gym, so I installed Virtualbox and used ubuntu. I installed gym using the terminal and the following commands: 

`git clone https://github.com/openai/gym.git
cd gym
pip install -e .`

A folder called gym is now located in my /home folder, and when I try to run the example code using the python IDLE:

`import gym
env = gym.make('Copy-v0')
env.reset()
env.render()`

It comes up with this error: 
```
Traceback (most recent call last):
  File "/home/akhi/Documents/random.py", line 2, in <module>
    env = gym.make('Copy-v0')
AttributeError: module 'gym' has no attribute 'make''
```
Note I called the document "random.py" because some answers said there should be a gym.py file which is confusing the IDLE. I typed python into the terminal and then "import gym" and then "gym.__file__". The result was "'gym/__init__.py'". For some reason I can't do this in the IDLE because it gives me this error:
 
`Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    gym.__file__
AttributeError: module 'gym' has no attribute '__file__'`

I'm really just puzzled at the moment, and i'm watching random youtube videos about learning basic ubuntu terminal commands, but it doesn't seem to be helping. If you could explain why these problems are occurring I would greatly appreciate it.

**Comment by akhilesh9999** [comment]
After spending many more hours on this, I found out the problem, which also explains why calling gym.__file__ in the terminal after entering python worked, whereas typing the command in the IDLE didn't. This was because I had installed python3.5 for the IDLE, whereas all the gym modules were installed in the site packages directory for python2.7. I simply ran the space invaders example in the terminal after calling python and it worked. Long story short, don't be a clutz and install 2 versions of python.
