### ISSUE TITLE
Atari: WinError 126: Module not found

### ISSUE THREAD

**Issue by FlashTek** [openai/gym#672]
Hello,
after installing `pip install gym[atari]` executing this line `gym.make("Amidat-v0")` is crashing the script with this error message:

> [2017-07-30 15:26:34,540] Making new env: Amidar-v0
Traceback (most recent call last):
  File "DQN.py", line 108, in <module>
    main()
  File "DQN.py", line 92, in main
    env = gym.make(env_name)
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\registration.py", line 161, in make
    return registry.make(id)
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\registration.py", line 85, in make
  cls = load(self._entry_point)
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\registration.py", line 17, in load
    result = entry_point.load(False)
  File "C:\Users\Roland\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2302, in load
    return self.resolve()
  File "C:\Users\Roland\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "C:\Users\Roland\Anaconda3\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "C:\Users\Roland\Anaconda3\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Users\Roland\Anaconda3\lib\site-packages\atari_py\ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "C:\Users\Roland\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Roland\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

The last line can be translated with `The specified module could not be found`. How do I solve this error?

Edit: Following [this comment](https://github.com/openai/gym/issues/11#issuecomment-282783535), I was able to solve the problem as a workarround.

**Comment by deep999** [comment]
I have identical error. So as you did with linked comment I inputed in cmd: pip install -U git+https://github.com/Kojoley/atari-py.git ... but I get error:
error: command 'D:\Anaconda\Library\mingw-w64\bin\gcc.exe' failed wi
th exit status 1

----------------------------------------
Rolling back uninstall of atari-py
Command "d:\Anaconda\python.exe -u -c "import setuptools, tokenize;file='
C:\Users\AppData\Local\Temp\pip-2dbb83b_-build\setup.py';f=getattr(
tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, file, 'exec'))" install --record C:\Users\URO~1\AppData\L
ocal\Temp\pip-wd7z84h6-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in C:\Users\AppData\Local\Temp\pi
p-2dbb83b_-build\

An ideas what to do? Something is finaly moving after hours of trying haha.
