### ISSUE TITLE
when call render() function, it say:XlibException: Could not create UTF8 text property

### ISSUE THREAD

**Issue by flutist** [openai/gym#673]
Hello, i want to ask a question, not matter what env i initial, when i call render() function, it say:

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py", line 115, in _render
    from gym.envs.classic_control import rendering

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/__init__.py", line 558, in __init__
    self._create()

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 353, in _create
    self.set_caption(self._caption)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 513, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)

  File "/home/hit/anaconda2/envs/py3k/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 783, in _set_text_property
    raise XlibException('Could not create UTF8 text property')

XlibException: Could not create UTF8 text property

can you help me, thanks

**Comment by dukelec** [comment]
I got the same problem.

**Comment by zeus7777777** [comment]
Same issue

**Comment by dukelec** [comment]
Python2.7 has no such issue.

**Comment by Guiadan** [comment]
same problem
anybody fixed this somehow?

**Comment by kanakkabara** [comment]
Any fixes?

**Comment by MobiusZ** [comment]
same problem for python 3.5

**Comment by 20chase** [comment]
pygame environment also has this problem for python 3.5

**Comment by SunnerLi** [comment]
```python
import pyglet
window = pyglet.window.Window()
```

It's the problem of pyglet.
I try for the above code, 
and the error will occur.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyglet/__init__.py", line 378, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/__init__.py", line 1884, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/__init__.py", line 571, in __init__
    self._create()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 356, in _create
    self.set_caption(self._caption)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 522, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 806, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property
```

I refer to others opinion.
Maybe try to revise the locale setting can solve the problem.
However, I try for the following commands,
I don't know how to revise `uft8` into `utf-8`.
```
$ sudo cat /etc/default/locale 
#  File generated by update-locale
LANG=en_US.UTF-8
LC_NUMERIC="lzh_TW"
LC_TIME="lzh_TW"
LC_MONETARY="lzh_TW"
LC_PAPER="lzh_TW"
LC_NAME="lzh_TW"
LC_ADDRESS="lzh_TW"
LC_TELEPHONE="lzh_TW"
LC_MEASUREMENT="lzh_TW"
LC_IDENTIFICATION="lzh_TW"

$ sudo locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
lzh_TW
lzh_TW.utf8
POSIX
```

The only possible way is just use python 2.7 to run.
Does anyone have other idea?

**Comment by SunnerLi** [comment]
I found an awkward solution:
1. edit your `/etc/default/locale/', and try to feed all locale critiria as the same:
```
#  File generated by update-locale
LANG=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

2. Use `sudo dpkg-reconfigure locales` to set your own language. Make sure to mark `en_US.UTF-8` selection.

3. `sudo locale-gen en_US en_US.UTF-8`

4. Reboot

**Comment by tengerye** [comment]
Is there any solution so far?

**Comment by alonrs** [comment]
Simpler solution:

In your terminal window:
1. Write LANG=en_US
2. Run your python code
It worked for me. You will need to do this every time you open a new terminal.

Another option:
Add the following to your python code (before everything):
```
import os
os.environ['LANG']='en_US'
```

**Comment by christopherhesse** [comment]
Thanks for answering this @SunnerLi and @tengerye.  Some applications seem to require running `locale-gen en_US.UTF-8` or one of these other solutions.

**Comment by matanster** [comment]
Is this compatibility issue going to be fixed? it seems that changing the locale is only a workaround until the library regains the ability to work across locales.

**Comment by JamesKCS** [comment]
I had the same problem, but none of the solutions above worked.  The problem turned out to be some kind of conflict with [SMFL](https://www.sfml-dev.org/).  So if you are getting this error, the solutions above are not working, and you have other libraries that you're working with that might do something with rendering text, it's worth checking if those other libraries are causing a conflict.

**Comment by amir-teymuri** [comment]
> 

doesn't work for me on ubuntu
