### ISSUE TITLE
Running the DuskDrive demo crashing after a while

### ISSUE THREAD

**Issue by EMCP** [openai/gym#697]
Receiving different errors when running the DuskDrive demo for longer than 2 minutes or so..

```
import gym
import universe # register the universe environments
env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1) # automatically creates a local docker container
observation_n = env.reset()
while True:
 action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] # your agent here
 observation_n, reward_n, done_n, info = env.step(action_n)
 env.render()
```

Environment will run fine for a while on a MBP with OS X 10.12.6 , and python 3.5 .. but eventually get some errors

```
universe-AYdAfa-0 | [2017-08-19 15:59:31,739] [INFO:gym_controlplane.reward.reward] First score parsed: score=386
[2017-08-19 17:59:32,356] [0] Closing rewarder connection
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/Users/emcp/Dev/git/openai/gym/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/emcp/Dev/git/openai/universe/universe/wrappers/timer.py", line 23, in _step
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/Users/emcp/Dev/git/openai/gym/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/emcp/Dev/git/openai/universe/universe/wrappers/render.py", line 33, in _step
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/Users/emcp/Dev/git/openai/gym/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/emcp/Dev/git/openai/universe/universe/wrappers/throttle.py", line 117, in _step
    observation_n, reward_n, done_n, info = self._substep(action_n)
  File "/Users/emcp/Dev/git/openai/universe/universe/wrappers/throttle.py", line 132, in _substep
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/Users/emcp/Dev/git/openai/gym/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/emcp/Dev/git/openai/universe/universe/envs/vnc_env.py", line 464, in _step
    self._handle_crashed_n(info_n)
  File "/Users/emcp/Dev/git/openai/universe/universe/envs/vnc_env.py", line 537, in _handle_crashed_n
    raise error.Error('{}/{} environments have crashed! Most recent error: {}'.format(len(self.crashed), self.n, errors))
universe.error.Error: 1/1 environments have crashed! Most recent error: {'0': 'Both VNC and rewarder sessions failed: [0:localhost:5900] vnc error: could not read message type: EOF; Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)'}
[2017-08-19 17:59:32,562] Killing and removing container: id=52b2c8c2a32f8c62233e1fffa17372624605a0e616659562dece691226bf6761
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.30/containers/52b2c8c2a32f8c62233e1fffa17372624605a0e616659562dece691226bf6761?link=False&v=False&force=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emcp/Dev/git/openai/universe/universe/remotes/docker_remote.py", line 341, in _remove
    self.client.remove_container(container=self._container_id, force=True)
  File "/usr/local/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/docker/api/container.py", line 293, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix /Users/emcp/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused'")
[2017-08-19 17:59:34,360] Killing and removing container: id=52b2c8c2a32f8c62233e1fffa17372624605a0e616659562dece691226bf6761
Exception ignored in: <bound method DockerInstance.__del__ of <universe.remotes.docker_remote.DockerInstance object at 0x11d136080>>
Traceback (most recent call last):
  File "/Users/emcp/Dev/git/openai/universe/universe/remotes/docker_remote.py", line 361, in __del__
  File "/Users/emcp/Dev/git/openai/universe/universe/remotes/docker_remote.py", line 372, in close
  File "/Users/emcp/Dev/git/openai/universe/universe/remotes/docker_remote.py", line 341, in _remove
  File "/usr/local/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "/usr/local/lib/python3.5/site-packages/docker/api/container.py", line 291, in remove_container
  File "/usr/local/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 147, in _delete
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 547, in delete
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 466, in request
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 626, in merge_environment_settings
  File "/usr/local/lib/python3.5/site-packages/requests/utils.py", line 568, in get_environ_proxies
  File "/usr/local/lib/python3.5/site-packages/requests/utils.py", line 556, in should_bypass_proxies
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2546, in proxy_bypass
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2523, in proxy_bypass_macosx_sysconf
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2470, in _proxy_bypass_macosx_sysconf
ImportError: import of 'fnmatch' halted; None in sys.modules
```

**Comment by christopherhesse** [comment]
Universe has been deprecated, closing this issue.
