### ISSUE TITLE
Error uploading Pusher-v0 evaluation

### ISSUE THREAD

**Issue by larrywyang** [openai/gym#707]
I am trying to upload an evaluation of the [Pusher-v0](https://github.com/openai/gym/blob/master/gym/envs/__init__.py#L214) environment but am getting the following error:

```
[2017-08-29 20:38:52,689] [Pusher-v0] Uploading 500 episodes of training data
[2017-08-29 20:38:53,100] [Pusher-v0] Uploading videos of 8 training episodes (306225 bytes)
[2017-08-29 20:38:53,335] [Pusher-v0] Creating evaluation object from /home/larry/lib/rllab/data/local/trpo-pusher/trpo-pusher_2017_08_29_19_29_14_0001/gym_log with learning curve and training video
Traceback (most recent call last):
  File "scripts/submit_gym.py", line 22, in <module>
    gym.upload(args.log_dir, algorithm_id=args.algorithm_id)
  File "/home/larry/lib/gym/gym/scoreboard/api.py", line 54, in upload
    skip_videos=skip_videos,
  File "/home/larry/lib/gym/gym/scoreboard/api.py", line 165, in _upload
    api_key=api_key,
  File "/home/larry/lib/gym/gym/scoreboard/client/resource.py", line 323, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/home/larry/lib/gym/gym/scoreboard/client/api_requestor.py", line 41, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/home/larry/lib/gym/gym/scoreboard/client/api_requestor.py", line 157, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/home/larry/lib/gym/gym/scoreboard/client/api_requestor.py", line 55, in handle_api_error
    rbody, rcode, resp, rheaders)
gym.error.InvalidRequestError: Request req_GlbitW4uQWy4sadpGDq9w: Unknown environment 'Pusher-v0'. No registered env with id: Pusher-v0
```

I verified that the environment is found in `gym.envs.registry.all()`.  What other steps are necessary to upload a task evaluation?

Thanks!

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
