### ISSUE TITLE
Error while installing gym for python 2.x

### ISSUE THREAD

**Issue by NSAryan12** [openai/gym#709]
I get the error
when I put in ``` sudo pip install gym ```
I have tried all the solutions from other issues but none of them seem to work.
surprisingly it works on python 3.x

```
sudo pip install gym
The directory '/Users/Aryan/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Aryan/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gym
Requirement already satisfied (use --upgrade to upgrade): six in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from gym)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /Library/Python/2.7/site-packages (from gym)
Requirement already satisfied (use --upgrade to upgrade): pyglet>=1.2.0 in /Library/Python/2.7/site-packages (from gym)
Collecting numpy>=1.10.4 (from gym)
  Downloading numpy-1.13.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.6MB)
    100% |████████████████████████████████| 4.6MB 261kB/s 
Requirement already satisfied (use --upgrade to upgrade): idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests>=2.0->gym)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests>=2.0->gym)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests>=2.0->gym)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests>=2.0->gym)
Installing collected packages: numpy, gym
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-H4ROeL-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by neveryoubetray** [comment]
I don't think python2 is supported unfortunately

**Comment by FirefoxMetzger** [comment]
@neveryoubetray I use Python 2.7 and it is working for me, further the docker builds both use 2.7 .

@NSAryan12 The error you are getting is because you are using numpy v1.8 with python 2.X. You installed this using `apt install

**Comment by christopherhesse** [comment]
Thanks for answering this @FirefoxMetzger !
