### ISSUE TITLE
Error with Doom_py

### ISSUE THREAD

**Issue by gamesgomez123** [openai/gym#760]
Hi, 
I am using windows 10 with Anaconda and python  and trying to build the Doom environment. I am getting the following error when I try to install the ppaquette-gym-doom environment with "pip install ppaquette-gym-doom". Error is attached for reference.. can anyone help?

(C:\Users\AdamZ\Anaconda3) C:\gym>pip install ppaquette-gym-doom
Collecting ppaquette-gym-doom
Collecting doom-py>=0.0.11 (from ppaquette-gym-doom)
  Using cached doom-py-0.0.15.tar.gz
Requirement already satisfied: gym>=0.8.0 in c:\gym (from ppaquette-gym-doom)
Requirement already satisfied: numpy in c:\users\AdamZ\anaconda3\lib\site-packages (from doom-py>=0.0.11->ppaquette-gym-doom)
Requirement already satisfied: requests>=2.0 in c:\users\AdamZ\anaconda3\lib\site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Requirement already satisfied: six in c:\users\AdamZ\anaconda3\lib\site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Requirement already satisfied: pyglet>=1.2.0 in c:\users\AdamZ\anaconda3\lib\site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Building wheels for collected packages: doom-py
  Running setup.py bdist_wheel for doom-py ... error
  Complete output from command "c:\users\AdamZ\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\AdamZ~1\\AppData\\Local\\Temp\\pip-build-an2563di\\doom-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\AdamZ~1\AppData\Local\Temp\tmpuh6ixdntpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 88, in <module>
      include_package_data=True,
    File "c:\users\AdamZ\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\AdamZ\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "c:\users\AdamZ\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 63, in run
      build_func()
    File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 45, in build_windows
      build_common('dll')
    File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 23, in build_common
      python_library = find_python_library()
    File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 16, in find_python_library
      python_library = os.path.join(sysconfig.get_config_var(var), 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension))
    File "c:\users\AdamZ\anaconda3\lib\ntpath.py", line 75, in join
      path = os.fspath(path)
  TypeError: expected str, bytes or os.PathLike object, not NoneType

  ----------------------------------------
  Failed building wheel for doom-py
  Running setup.py clean for doom-py
Failed to build doom-py
Installing collected packages: doom-py, ppaquette-gym-doom
  Running setup.py install for doom-py ... error
    Complete output from command "c:\users\AdamZ\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\AdamZ~1\\AppData\\Local\\Temp\\pip-build-an2563di\\doom-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AdamZ~1\AppData\Local\Temp\pip-8veof2ru-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 88, in <module>
        include_package_data=True,
      File "c:\users\AdamZ\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\AdamZ\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\AdamZ\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\AdamZ\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\AdamZ\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 63, in run
        build_func()
      File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 45, in build_windows
        build_common('dll')
      File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 23, in build_common
        python_library = find_python_library()
      File "C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\setup.py", line 16, in find_python_library
        python_library = os.path.join(sysconfig.get_config_var(var), 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension))
      File "c:\users\AdamZ\anaconda3\lib\ntpath.py", line 75, in join
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

    ----------------------------------------
Command ""c:\users\AdamZ\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\AdamZ~1\\AppData\\Local\\Temp\\pip-build-an2563di\\doom-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AdamZ~1\AppData\Local\Temp\pip-8veof2ru-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AdamZ~1\AppData\Local\Temp\pip-build-an2563di\doom-py\

**Comment by rounakskm** [comment]
I am facing the same kind of issue.

**Comment by rounakskm** [comment]
You can try downloading the zip file of https://github.com/ppaquette/gym-doom and then unzip it.
Then open the anaconda prompt / git bash / cmd as Administrator in that location
cd gym-doom-master
python setup.py build
python setup.py install
This is successfully installing the  ppaquette_gym_doom 

But if I try 
import ppaquette_gym_doom 

It will throw errors saying : 
DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'

Then, if i try "pip install doom_py" 
I get this same problem you are getting now.

And trying the trick we tried above to install ppaquette_gym_doom 
does install doom-py but the error still persists.

It even shows up when I do conda list

 
<img width="362" alt="1" src="https://user-images.githubusercontent.com/31090080/34324643-48f4de6a-e848-11e7-97c9-f016e32dec3b.PNG">

<img width="303" alt="2" src="https://user-images.githubusercontent.com/31090080/34324644-56855f96-e848-11e7-8884-4fb6e43cc74c.PNG">

**Comment by christopherhesse** [comment]
It looks like we don't have doom environments anymore, please try the VizDoom python bindings that are now available in the VizDoom repo: https://github.com/mwydmuch/ViZDoom
