### ISSUE TITLE
Error on 'zlib' when installking Atari

### ISSUE THREAD

**Issue by tqin** [openai/gym#824]
Hi,

I'm trying to install the Atari option of gym on centos.  I've installed all the dependencies as instructed in the documentation, but I'm getting the following errors, which appears that installation could not find 'zlib'.  However, I have 'zlib' installed already as shown below.  Any idea about the problem or solution is much appreciated!

$ sudo yum install zlib
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * epel: mirrors.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: mirrors.163.com
Package zlib-1.2.7-17.el7.x86_64 already installed and latest version
Nothing to do
=================================================================
The full log trace of installation is as follows:

$ sudo pip install gym[atari]
Requirement already satisfied: gym[atari] in /usr/lib/python2.7/site-packages/gym-0.9.3-py2.7.egg
Requirement already satisfied: numpy>=1.10.4 in /usr/lib64/python2.7/site-packages (from gym[atari])
Requirement already satisfied: requests>=2.0 in /usr/lib/python2.7/site-packages (from gym[atari])
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from gym[atari])
Requirement already satisfied: pyglet>=1.2.0 in /usr/lib/python2.7/site-packages (from gym[atari])
Collecting atari_py>=0.1.1 (from gym[atari])
  Using cached atari-py-0.1.1.tar.gz
Requirement already satisfied: Pillow in /usr/lib64/python2.7/site-packages (from gym[atari])
Requirement already satisfied: PyOpenGL in /usr/lib/python2.7/site-packages (from gym[atari])
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from pyglet>=1.2.0->gym[atari])
Building wheels for collected packages: atari-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mSyleb/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkMQ4lopip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  make: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Check for working C compiler: /bin/cc
  -- Check for working C compiler: /bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: /bin/c++
  -- Check for working CXX compiler: /bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build
  make[1]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make[1]: warning: -jN forced in submake: disabling jobserver mode.
  make[2]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make[3]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  Scanning dependencies of target ale-c-lib
  make[3]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make[3]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  [  0%] [  2%] [  2%] [  2%] Building CXX object CMakeFiles/ale-c-lib.dir/tmp/pip-build-mSyleb/atari-py/atari_py/ale_c_wrapper.cpp.o
  Building CXX object CMakeFiles/ale-c-lib.dir/src/common/ColourPalette.cpp.o
  Building CXX object CMakeFiles/ale-c-lib.dir/src/ale_interface.cpp.o
  Building CXX object CMakeFiles/ale-c-lib.dir/src/common/Constants.cpp.o
  In file included from /tmp/pip-build-mSyleb/atari-py/atari_py/ale_c_wrapper.cpp:1:0:
  /tmp/pip-build-mSyleb/atari-py/atari_py/ale_c_wrapper.h: In function 'void getScreenRGB2(ALEInterface*, unsigned char*)':
  /tmp/pip-build-mSyleb/atari-py/atari_py/ale_c_wrapper.h:71:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for(int i = 0;i < screen_size;i++){
                         ^
  [  3%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/display_screen.cpp.o
  [  4%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/Log.cpp.o
  [  5%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.o
  [  5%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/SoundExporter.cpp.o
  /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:18:18: fatal error: zlib.h: No such file or directory
   #include <zlib.h>
                    ^
  compilation terminated.
  [  6%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/SoundNull.cxx.o
  make[3]: *** [CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/src/common/SoundNull.cxx: In member function 'virtual bool SoundNull::load(Deserializer&)':
  /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/src/common/SoundNull.cxx:49:9: warning: variable 'reg' set but not used [-Wunused-but-set-variable]
     uInt8 reg;
           ^
  make[3]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make[2]: *** [CMakeFiles/ale-c-lib.dir/all] Error 2
  make[2]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make[1]: *** [all] Error 2
  make[1]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
  make: *** [build] Error 2
  make: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface'
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '19']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-mSyleb/atari-py/setup.py", line 36, in <module>
      tests_require=['nose2']
    File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
      dist.run_commands()
    File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-mSyleb/atari-py/setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '19']' returned non-zero exit status 2

  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py
  Running setup.py install for atari-py ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mSyleb/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-OToIqg-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build
    make[1]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[1]: warning: -jN forced in submake: disabling jobserver mode.
    make[2]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[3]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[3]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[3]: Entering directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    [  1%] [  1%] [  2%] [  3%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.o
    Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/ale_controller.cpp.o
    Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/fifo_controller.cpp.o
    Building CXX object CMakeFiles/ale-c-lib.dir/src/common/SoundSDL.cxx.o
    [  4%] Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/rlglue_controller.cpp.o
    /tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:18:18: fatal error: zlib.h: No such file or directory
     #include <zlib.h>
                      ^
    compilation terminated.
    make[3]: *** [CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    make[3]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[2]: *** [CMakeFiles/ale-c-lib.dir/all] Error 2
    make[2]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface/build'
    make: *** [build] Error 2
    make: Leaving directory `/tmp/pip-build-mSyleb/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '19']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mSyleb/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-mSyleb/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '19']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mSyleb/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-OToIqg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mSyleb/atari-py/

**Comment by tqin** [comment]
OK, it turns out that yum install zlib-devel solved the problem.
