### ISSUE TITLE
AttributeError: 'MjViewer' object has no attribute 'get_image' (gym/envs/mujoco/mujoco_env.py", line 106, in render)

### ISSUE THREAD

**Issue by erwincoumans** [openai/gym#841]
I'm getting the error below, when making a video of the most recent gym Humanoid-v2 with mjpro150 and mujoco-py (1.50.1.1) and gym (0.9.5). Training works fine, using TF Agents.

Where is MjViewer:get_image implemented? When I manually implement it using attached patch for mujoco_py taken from rllab, it seems to work.
[mjviewer_get_image.diff.zip](https://github.com/openai/gym/files/1671680/mjviewer_get_image.diff.zip)

Alternatively, what version of mujoco_py and gym v0.9.5 is compatible with mjpro150?

~~~~~~~

ERROR:tensorflow:Error in environment process: Traceback (most recent call last):
  File "/Users/erwincoumans/anaconda3/lib/python3.6/site-packages/agents-1.0.3-py3.6.egg/agents/tools/wrappers.py", line 452, in _worker
    conn.send((self._OBSERV, env.reset()))
  File "/Users/erwincoumans/anaconda3/lib/python3.6/site-packages/agents-1.0.3-py3.6.egg/agents/tools/wrappers.py", line 514, in reset
    observ = self._env.reset()
  File "/Users/erwincoumans/anaconda3/lib/python3.6/site-packages/agents-1.0.3-py3.6.egg/agents/tools/wrappers.py", line 234, in reset
    observ = self._env.reset()
  File "/Users/erwincoumans/dev/gym/gym/wrappers/monitor.py", line 39, in reset
    self._after_reset(observation)
  File "/Users/erwincoumans/dev/gym/gym/wrappers/monitor.py", line 193, in _after_reset
    self.reset_video_recorder()
  File "/Users/erwincoumans/dev/gym/gym/wrappers/monitor.py", line 214, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/Users/erwincoumans/dev/gym/gym/wrappers/monitoring/video_recorder.py", line 101, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/Users/erwincoumans/dev/gym/gym/core.py", line 243, in render
    return self.env.render(mode)
  File "/Users/erwincoumans/dev/gym/gym/envs/mujoco/mujoco_env.py", line 106, in render
    data, width, height = self._get_viewer().get_image()
AttributeError: 'MjViewer' object has no attribute 'get_image'

~~~~~~~

The MjViewer only has those methods:
~~~~~~~
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_marker_to_scene', '_advance_by_one_step', '_button_left_pressed', '_button_right_pressed', '_create_full_overlay', '_cursor_pos_callback', '_gui_lock', '_hide_overlay', '_image_idx', '_image_path', '_init_camera', '_last_mouse_x', '_last_mouse_y', '_loop_count', '_markers', '_mouse_button_callback', '_ncam', '_overlay', '_paused', '_read_pixels_as_in_window', '_record_video', '_render_every_frame', '_run_speed', '_scale', '_scroll_callback', '_set_mujoco_buffers', '_setup_opengl_context', '_show_mocap', '_time_per_render', '_transparent', '_user_overlay', '_video_idx', '_video_path', '_video_queue', '_visible', 'add_marker', 'add_overlay', 'cam', 'con', 'draw_pixels', 'key_callback', 'move_camera', 'offscreen', 'opengl_context', 'pert', 'read_pixels', 'render', 'scn', 'sim', 'update_offscreen_size', 'update_sim', 'upload_texture', 'vopt', 'window']
~~~~~~~~~~

**Comment by guru-florida** [comment]
Thanks erwincoumans! Attached patch worked for me.

**Comment by geg58** [comment]
Where did you put the attached patch?

**Comment by ak-7** [comment]
You should make the changes in mjviewer.py in the directory where your mujoco_py is installed. You can check the path of your python package using 

> import sys
> sys.path

**Comment by hzyjerry** [comment]
Thanks the patch works for me too!

**Comment by geg58** [comment]
Same! Works for me as well! Thanks @erwincoumans  and @ak-7

**Comment by welinder** [comment]
This is fixed in https://github.com/openai/gym/pull/909
