### ISSUE TITLE
Can't install gym[atari] in windows

### ISSUE THREAD

**Issue by stepseazy** [openai/gym#884]
Hi all,

I encountered the below problem message. I've tried installing make and zlib as suggested, as well as running from visual studio prompt. Do you have any idea what could be going wrong? Thanks.

Rik

```
PS C:\WINDOWS\system32> pip install gym[atari]
Requirement already satisfied: gym[atari] in c:\users\hendrick brutsaert\anaconda3\lib\site-packages
Requirement already satisfied: pyglet>=1.2.0 in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Requirement already satisfied: numpy>=1.10.4 in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Requirement already satisfied: requests>=2.0 in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Requirement already satisfied: six in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Collecting atari-py>=0.1.1; extra == "atari" (from gym[atari])
  Using cached atari-py-0.1.1.tar.gz
Requirement already satisfied: PyOpenGL; extra == "atari" in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Requirement already satisfied: Pillow; extra == "atari" in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from gym[atari])
Requirement already satisfied: future in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from pyglet>=1.2.0->gym[atari])
Requirement already satisfied: olefile in c:\users\hendrick brutsaert\anaconda3\lib\site-packages (from Pillow; extra == "atari"->gym[atari])
Building wheels for collected packages: atari-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command "C:\Users\Hendrick Brutsaert\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HENDRI~1\\AppData\\Local\\Temp\\pip-build-tjrw2ozn\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\HENDRI~1\AppData\Local\Temp\tmp05zb_k_6pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  make: Entering directory `C:/Users/HENDRI~1/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- Building for: NMake Makefiles
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:2 (project):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  CMake Error at CMakeLists.txt:2 (project):
    The CMAKE_CXX_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Hendrick Brutsaert/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/Hendrick Brutsaert/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
  make: *** [build] Error 1
  make: Leaving directory `C:/Users/HENDRI~1/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface'
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\HENDRI~1\AppData\Local\Temp\pip-build-tjrw2ozn\atari-py\setup.py", line 36, in <module>
      tests_require=['nose2']
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\HENDRI~1\AppData\Local\Temp\pip-build-tjrw2ozn\atari-py\setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.

  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py
  Running setup.py install for atari-py ... error
    Complete output from command "C:\Users\Hendrick Brutsaert\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HENDRI~1\\AppData\\Local\\Temp\\pip-build-tjrw2ozn\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HENDRI~1\AppData\Local\Temp\pip-5_lbvlqq-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make: Entering directory `C:/Users/HENDRI~1/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:2 (project):
      The CMAKE_C_COMPILER:

        cl

      is not a full path and was not found in the PATH.

      To use the NMake generator with Visual C++, cmake must be run from a shell
      that can use the compiler cl from the command line.  This environment is
      unable to invoke the cl compiler.  To fix this problem, run cmake from the
      Visual Studio Command Prompt (vcvarsall.bat).

      Tell CMake where to find the compiler by setting either the environment
      variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
      the compiler, or to the compiler name if it is in the PATH.


    CMake Error at CMakeLists.txt:2 (project):
      The CMAKE_CXX_COMPILER:

        cl

      is not a full path and was not found in the PATH.

      To use the NMake generator with Visual C++, cmake must be run from a shell
      that can use the compiler cl from the command line.  This environment is
      unable to invoke the cl compiler.  To fix this problem, run cmake from the
      Visual Studio Command Prompt (vcvarsall.bat).

      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Hendrick Brutsaert/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Hendrick Brutsaert/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
    make: *** [build] Error 1
    make: Leaving directory `C:/Users/HENDRI~1/AppData/Local/Temp/pip-build-tjrw2ozn/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HENDRI~1\AppData\Local\Temp\pip-build-tjrw2ozn\atari-py\setup.py", line 36, in <module>
        tests_require=['nose2']
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\HENDRI~1\AppData\Local\Temp\pip-build-tjrw2ozn\atari-py\setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "C:\Users\Hendrick Brutsaert\Anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '7']' returned non-zero exit status 2.

    ----------------------------------------
Command ""C:\Users\Hendrick Brutsaert\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HENDRI~1\\AppData\\Local\\Temp\\pip-build-tjrw2ozn\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HENDRI~1\AppData\Local\Temp\pip-5_lbvlqq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HENDRI~1\AppData\Local\Temp\pip-build-tjrw2ozn\atari-py\
PS C:\WINDOWS\system32>

```

**Comment by AwokeKnowing** [comment]
if windows 10, you could try it on WSL

https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows/44345972#44345972

**Comment by christopherhesse** [comment]
Thanks for answering @AwokeKnowing, that's likely to work, but I will close this particular issue in favor of https://github.com/openai/atari-py/issues/5
