### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by Chenyao2333** [openai/gym#893]
I'm using MacOS. Since the python script finished, it will print such errors:

It's a script will cause this problem:
~~~
import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
env.render()
~~~

And after executing it, the error occurs:
~~~
~/G/qlearning $ python atari.py
Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x1059ab400>>
Traceback (most recent call last):
  File "/Users/louchenyao/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 347, in __del__
  File "/Users/louchenyao/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 343, in close
  File "/Users/louchenyao/anaconda3/lib/python3.6/site-packages/pyglet/window/cocoa/__init__.py", line 281, in close
  File "/Users/louchenyao/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down
~~~

It doesn't affect the environment running. It just a little annoying.

**Comment by rrbb014** [comment]
I also same problem. wanna solutions!

**Comment by robomotic** [comment]
I have the same issue, I fired the debugger but I am not a Cocoa developer but it seems like something to do when closing the window.

**Comment by david-dalisay** [comment]
I don't know if this is helpful. But I've noticed that this issue only comes up if I do more operations in the `while True` loop. I am using the Atari environment to loop through games of Kung Fu Master. And after I call my agent's `act` function, I collect the reward and use it update my agent's Q table. If I do that update operation, I get a bunch of random digits printed to standard output, followed by `Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at`
...
`ImportError: sys.meta_path is None, Python is likely shutting down`

**Comment by MiaoDX** [comment]
Hei, maybe we encounter the same issues, it may not be a bug. Try adding `env.close()` at the end of your programs, in my scenario, it works nice.

**Comment by robomotic** [comment]
Gosh that worked for me!

**Comment by Cyberface** [comment]
I am trying this example https://github.com/openai/gym/blob/master/examples/agents/random_agent.py and getting the same error

As you can see from the example script it has `env.close()` at the end :(

Thanks for any help!

```
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/random-agent-results')
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x106759668>>
Traceback (most recent call last):
  File "/Users/sebastian/work/git/stk/rocket-landing/venv/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/Users/sebastian/work/git/stk/rocket-landing/venv/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/Users/sebastian/work/git/stk/rocket-landing/venv/lib/python3.6/site-packages/pyglet/window/cocoa/__init__.py", line 281, in close
  File "/Users/sebastian/work/git/stk/rocket-landing/venv/lib/python3.6/site-packages/pyglet/window/__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by MiaoDX** [comment]
@Cyberface , this whole issue rise from one not so perfect PR: [Cleanup, removal of unmaintained code #836](https://github.com/openai/gym/pull/836). The line 31 of the example is ` env = wrappers.Monitor(env, directory=outdir, force=True)`, from there, the `env` is one `Moniotr`. Long story short, try `env.env.close()` at the very end. But it should be imporoved with a PR fix in the codebase instead of this ugly patch.

**Comment by robomotic** [comment]
Yes that works for me too.

**Comment by Cyberface** [comment]
thanks worked for me - thanks!

**Comment by wangshub** [comment]
thanks! that works ! @MiaoDX

**Comment by zhanwenchen** [comment]
For me, mine was capturing videos but after a while, I got an exception and it shut down (this is `random_agent.py` in CartPole-v0).

```
DEBUG: Capturing video frame: path=/tmp/random-agent-results/openaigym.video.0.23503.video000064.mp4
DEBUG: Closing video encoder: path=/tmp/random-agent-results/openaigym.video.0.23503.video000064.mp4
DEBUG: Writing training manifest file to /tmp/random-agent-results/openaigym.manifest.0.23503.manifest.json
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/random-agent-results')
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x110c4ecc0>>
Traceback (most recent call last):
  File "/Users/zhanwenchen/Downloads/gym/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/Users/zhanwenchen/Downloads/gym/gym/envs/classic_control/rendering.py", line 62, in close
  File "/Users/zhanwenchen/anaconda/lib/python3.6/site-packages/pyglet/window/cocoa/__init__.py", line 281, in close
  File "/Users/zhanwenchen/anaconda/lib/python3.6/site-packages/pyglet/window/__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by Catherine-Chu** [comment]
I tried a simple instructive code in CartPole-v0 in Pycharm and got the same problem. Unfortunately, `env.close()` didn't work for me. And I tried to run the same code in cmd and the exception disappeared. 
`Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x0000023C2D44A9E8>>
Traceback (most recent call last):
  File "d:\projects\gym\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "d:\projects\gym\gym\envs\classic_control\rendering.py", line 62, in close
  File "D:\installed\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 291, in close
  File "D:\installed\Python36\lib\site-packages\pyglet\window\__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down`

**Comment by CihanSoylu** [comment]
Changing `env.close()` at the end of the file to `env.env.close()` worked for me.

**Comment by Cuiyirui** [comment]
> Traceback (most recent call last):
  File "/usr/pycharm_project/testGym.py", line 8, in <module>
    env.render()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py", line 137, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 85, in render
    self.window.dispatch_events()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 862, in dispatch_events
    self.dispatch_pending_events()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 902, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 744, in on_resize
    gl.glOrtho(0, max(1, width), 0, max(1, height), -1, 1)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7fa0001e0f60>>
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/usr/local/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 281, in destroy
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 276, in detach
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down

The same problem occurs to me. But whether I use env.close() or env.env.close() at the end of my code, it still doesn't work

**Comment by BerrySG** [comment]
Me too, none of the solution above works for me, same error again and again

**Comment by davidlni** [comment]
Try to install ffmpeg with brew to see if it helps. For my case, this error wasn't easy to spot and the screen shows one frame and fails to record the video. After installing ffmpeg, I still need to use env.env.close() to get rid of the "Python is likely shutting down" error.

**Comment by BerrySG** [comment]
@davidlni I fix it by fully reinstall the whole Gym module, thank you for your advice!

**Comment by mjain72** [comment]
env.env.close() worked for me

**Comment by dorlivne** [comment]
tried env.env.close() and env.close() at the end of crm.py , it doesnt work. 
can anyone tell me why this is happening?, tried debugging it but it seems the error generates at __init__.py but that doesn't make any sense.
(im using windows 10 )
**Exception ignored in: <function Viewer.__del__ at 0x072FA930>
Traceback (most recent call last):
  File "C:\python\lib\site-packages\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "C:\python\lib\site-packages\gym\envs\classic_control\rendering.py", line 62, in close
  File "C:\python\lib\site-packages\pyglet\window\win32\__init__.py", line 291, in close
  File "C:\python\lib\site-packages\pyglet\window\__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down**

**Comment by nuckykk** [comment]
Just add the lines below at the end of your program, the Error is raised during GC of the gym module.

```
try:
    del env
except ImportError:
    pass
```

**Comment by CIRCLECHAO** [comment]
楼上的就是在逃避现实  upstaies  YOU ARE JUST CANT SEE THE ERROR ???

**Comment by verasnt** [comment]
For those who are still having problems, on my system - debian linux - I solved installing ffmpeg
 ```# apt-get install ffmpeg ``` as @davidlni  suggested..

**Comment by AndromedaW** [comment]
Have anyone worked out ??? It seems there is something wrong with self.close() ........

**Comment by SunLemuria** [comment]
None of the solutions above works for me.

**Comment by vincent-contreras** [comment]
No solutions??? I tried everything, **brew install ffmpeg** and nothing worked on a macOS Mojave. Even tried **env.close()** and **env.env.close()** and nothing really worked.
What seems to be the problem???

**Comment by Isabek** [comment]
@SunLemuria, @vincent-contreras I have changed render mode and it works like a charm.

```python
import gym

env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render(mode='rgb_array')
    env.step(env.action_space.sample())
env.env.close()

```

**Comment by vincent-contreras** [comment]
I still don't see anything. I **brew install python**, download **virtualenv**. I don't understand why it's I don't see the cartpole :(

**Comment by vincent-contreras** [comment]
I tried without using virtualenv and everything works perfectly. Why isn't virtualenv not working? :(

**Comment by mlda065** [comment]
I thought I had this issue too. Then I realised that there were actually 3 tracebacks. There was a bug in my own code, which was captured with an exception, caused another bug, then captured, then another was caused.

So if you get this error, scroll up and read everything to make sure you look at only the earliest traceback.

**Comment by xuyannus** [comment]
I had the same error on my MacBook Pro and this guy solved my issue "brew install ffmpeg"

**Comment by 1057520143** [comment]
I also encountered this problem when I ran the code with pycharm, and the drawing window flashed. But when I run the code using spyder, the drawing window displays normally. And didn't report a mistake.

**Comment by christopherhesse** [comment]
It looks like the original issue is solved by calling `env.close()`, the example on the website has been updated to include that: https://gym.openai.com/

If any of the other issues are not fixed, please file new issues for those.

**Comment by powerzbt** [comment]
> Hei, maybe we encounter the same issues, it may not be a bug. Try adding `env.close()` at the end of your programs, in my scenario, it works nice.


And add 
'''
    def close(self):
        if self.viewer:
            self.viewer.close()
            self.viewer = None
'''
to the environment you defined

**Comment by nicehiro** [comment]
> > Hei, maybe we encounter the same issues, it may not be a bug. Try adding `env.close()` at the end of your programs, in my scenario, it works nice.
> 
> And add
> '''
> def close(self):
> if self.viewer:
> self.viewer.close()
> self.viewer = None
> '''
> to the environment you defined

Thanks! This fix my problem!

**Comment by DanyParry94** [comment]
I made a consideration: it seems that there is a limit set to the value 200 steps, then the environment automatically shuts down. As above said, for those who cannot solve the problem, instead of using "while", a cycle "for" with range set >200 will solve the problem.

**Comment by Barley-zhang** [comment]
I added 'env.close()' at the end . Then I have run "ipython CartPole-v.py"  It was worked for me
