### ISSUE TITLE
Error while running test Cart Pole code given in documentation.

### ISSUE THREAD

**Issue by richeekawasthi** [openai/gym#895]
I was running this code on gym on my PC,
```import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
```
It is supposed to render a cartpole environment which takes random steps. But I just see a window pop out for a second and this error when I run this code. I can't seem to find the issue here
```
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7fcebafc1b38>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/base.py", line 334, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/lib.py", line 97, in errcheck
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by phamtrongthang123** [comment]
I'm having the same problem. I guess it running so fast because when i've print out the iteration. But the error still the myth and I cannot understand why I have that "running so fast". My laptop use Ubuntu 16.04, NVIDIA GTX 950M. I followed the [link](https://github.com/openai/gym/issues/762#issuecomment-354584877), tried adding `import time` and `time.sleep(0.05)` to slow down the program, It's easier to watch the animation :|

**Comment by LianYun** [comment]
Calling `env.close()` at the end of scripts will solve this problem. 
```
import gym
import time
env = gym.make('Pong-v0')
env.reset()

env.render()
env.step(env.action_space.sample())

env.close()
```

**Comment by phamtrongthang123** [comment]
With me, it does not work!

**Comment by edusco4** [comment]
Thank you, LianYun. It worked for me
