### ISSUE TITLE
Building openai gym docker image fails with "No module named util" in mujoco_py install

### ISSUE THREAD

**Issue by dbdean** [openai/gym#918]
I can't get this project to build using the provided dockerfile, and I get the following error:

```
⟫ docker build --network host .
Sending build context to Docker daemon  8.044MB
Step 1/11 : FROM ubuntu:14.04
 ---> dc4491992653
Step 2/11 : RUN apt-get update     && apt-get install -y libav-tools     python-numpy     python-scipy     python-pyglet     python-setuptools     libpq-dev     libjpeg-dev     curl     cmake     swig     freeglut3     python-opengl     libboost-all-dev     libglu1-mesa     libglu1-mesa-dev     libsdl2-2.0-0    libgles2-mesa-dev     libsdl2-dev     wget     unzip     git     xserver-xorg-input-void     xserver-xorg-video-dummy     python-gtkglext1     xpra     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && easy_install pip
 ---> Using cache
 ---> 585051c31128
Step 3/11 : WORKDIR /usr/local/gym
 ---> Using cache
 ---> 1ff309b48466
Step 4/11 : RUN mkdir -p gym && touch gym/__init__.py
 ---> Using cache
 ---> 09e849dafdec
Step 5/11 : COPY ./gym/version.py ./gym
 ---> Using cache
 ---> e4deb724b510
Step 6/11 : COPY ./requirements.txt .
 ---> Using cache
 ---> d7a7531dcfe3
Step 7/11 : COPY ./setup.py .
 ---> Using cache
 ---> eb93a0e38051
Step 8/11 : RUN pip install -e .[all]
 ---> Running in 4be7b29a5dc1
Obtaining file:///usr/local/gym
Collecting numpy>=1.10.4 (from gym==0.10.3)
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading numpy-1.14.1-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
Collecting requests>=2.0 (from gym==0.10.3)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from gym==0.10.3)
Collecting pyglet>=1.2.0 (from gym==0.10.3)
  Downloading pyglet-1.3.1-py2.py3-none-any.whl (1.0MB)
Collecting Box2D-kengz (from gym==0.10.3)
  Downloading Box2D-kengz-2.3.3.tar.gz (425kB)
Collecting mujoco_py>=1.50 (from gym==0.10.3)
  Downloading mujoco-py-1.50.1.41.tar.gz (115kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iGObfJ/mujoco-py/setup.py", line 2, in <module>
        import importlib.util
    ImportError: No module named util

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iGObfJ/mujoco-py/
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
The command '/bin/sh -c pip install -e .[all]' returned a non-zero code: 1
```

**Comment by FirefoxMetzger** [comment]
Looks like mujoco is failing to setup propperly. From [their repo](https://github.com/openai/mujoco-py)

> Python 2 has been desupported since 1.50.1.0. Python 2 users can stay on the 0.5 branch. The latest release there is 0.5.7 which can be installed with pip install mujoco-py==0.5.7.

The current docker file uses python2.7 so it would require some more involved changes moving to python3 to get mujoco working. Otherwise you can always try to modify it and build without those environments, if applicable to your scenario

**Comment by christopherhesse** [comment]
Sorry but this looks like a `mujoco_py` issue, please file it on that repo: https://github.com/openai/mujoco-py  Thanks!
