### ISSUE TITLE
Mujoco 1.5 import issue.

### ISSUE THREAD

**Issue by bzdlity** [openai/gym#931]
Guys, I just installed mujoco 1.5 on windows 10, python 3.6.
When I import mujoco_py there problem came.

runfile('E:/learn/10-703/mujocotsample.py', wdir='E:/learn/10-703')
Traceback (most recent call last):

  File "<ipython-input-1-c06ae74b1621>", line 1, in <module>
    runfile('E:/learn/10-703/mujocotsample.py', wdir='E:/learn/10-703')

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/learn/10-703/mujocotsample.py", line 7, in <module>
    import mujoco_py

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\mujoco_py-1.50.1.41-py3.6.egg\mujoco_py\__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\mujoco_py-1.50.1.41-py3.6.egg\mujoco_py\builder.py", line 502, in <module>
    cymj = load_cython_ext(mjpro_path)

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\mujoco_py-1.50.1.41-py3.6.egg\mujoco_py\builder.py", line 82, in load_cython_ext
    return load_dynamic_ext('cymj', cext_so_path)

  File "E:\anaconda3\envs\tensorflow\lib\site-packages\mujoco_py-1.50.1.41-py3.6.egg\mujoco_py\builder.py", line 88, in load_dynamic_ext
    return loader.load_module()

ImportError: DLL load failed: %1 is not a valid Win32 application.

Please help me~

**Comment by christopherhesse** [comment]
I'm afraid windows is not a supported platform for mujoco_py: https://github.com/openai/mujoco-py

You can file an issue there if you want windows support though.
