### ISSUE TITLE
AttributeError: 'CarRacing' object has no attribute '_render'

### ISSUE THREAD

**Issue by JamesOwers** [openai/gym#943]
To reproduce the issue:

```
git clone git@github.com:openai/gym.git
cd gym
conda create -n gym python=3 numpy pandas matplotlib jupyter cmake swig
conda activate gym
pip install -e '.[atari,box2d,classic_control]'
python gym/envs/box2d/car_racing.py
```
error:
```
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Track generation: 1138..1426 -> 288-tiles track
Traceback (most recent call last):
  File "gym/envs/box2d/car_racing.py", line 480, in <module>
    env.reset()
  File "gym/envs/box2d/car_racing.py", line 292, in reset
    return self.step(None)[0]
  File "gym/envs/box2d/car_racing.py", line 304, in step
    self.state = self._render("state_pixels")
AttributeError: 'CarRacing' object has no attribute '_render'
```

**Comment by JamesOwers** [comment]
Have opened a pull request to fix this: https://github.com/openai/gym/pull/944

**Comment by JamesOwers** [comment]
This issue is still present, my fix above still applies.

**Comment by christopherhesse** [comment]
Looks like this was merged.
