### ISSUE TITLE
New robotics environments cannot be created on Windows

### ISSUE THREAD

**Issue by aywi** [openai/gym#958]
Run the following code:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import gym


def main():
    env = gym.make('FetchReach-v0')
    env = gym.wrappers.Monitor(env, '.', force=True)
    for episode in range(100):
        done = False
        s = env.reset()
        while not done:
            env.render()
            a = env.action_space.sample()
            s_next, r, done, info = env.step(a)
            s = s_next


if __name__ == '__main__':
    main()
```

Then I get:
```
Traceback (most recent call last):
  File ".\demo.py", line 21, in <module>
    main()
  File ".\demo.py", line 8, in main
    env = gym.make('FetchReach-v0')
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\robotics\fetch\reach.py", line 19, in __init__
    initial_qpos=initial_qpos, reward_type=reward_type)
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\robotics\fetch_env.py", line 48, in __init__
    initial_qpos=initial_qpos)
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\robotics\robot_env.py", line 34, in __init__
    self._env_setup(initial_qpos=initial_qpos)
  File "C:\ProgramData\Miniconda3\lib\site-packages\gym\envs\robotics\fetch_env.py", line 172, in _env_setup
    self.sim.data.set_joint_qpos(name, value)
  File "mujoco_py\generated/wrappers.pxi", line 2536, in mujoco_py.cymj.PyMjData.set_joint_qpos
TypeError: 'numpy.int32' object is not iterable
```

In `mujoco_py\generated/wrappers.pxi`, line 2536 is `start_i, end_i = addr`:
```
    def set_joint_qpos(self, name, value):
        addr = self._model.get_joint_qpos_addr(name)
        if isinstance(addr, (int, np.int32, np.int64)):
            self.qpos[addr] = value
        else:
            start_i, end_i = addr
            value = np.array(value)
            assert value.shape == (end_i - start_i,), (
                "Value has incorrect shape %s: %s" % (name, value))
            self.qpos[start_i:end_i] = value
```

However, the traditional MuJoCo environments like Ant-v2 can still be created correctly.

**Comment by qdenisq** [comment]
any updates on this issue?

**Comment by smmukhal** [comment]
I also have the same issue

**Comment by gabielchong** [comment]
look like is mujoco-py problem?

**Comment by jopdorp** [comment]
I have this problem too on windows too, indeed running from python:

Traceback (most recent call last):
  File "C:\Users\jopdorp\.IntelliJIdea2017.3\config\plugins\python\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Users\jopdorp\.IntelliJIdea2017.3\config\plugins\python\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\jopdorp\.IntelliJIdea2017.3\config\plugins\python\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\jopdorp\.IntelliJIdea2017.3\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/jopdorp/Documents/dev/ddpg-aigym/main.py", line 78, in <module>
    main()    
  File "C:/Users/jopdorp/Documents/dev/ddpg-aigym/main.py", line 16, in main
    env= gym.make(experiment)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\robotics\fetch\pick_and_place.py", line 17, in __init__
    initial_qpos=initial_qpos, reward_type=reward_type)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\robotics\fetch_env.py", line 48, in __init__
    initial_qpos=initial_qpos)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\robotics\robot_env.py", line 34, in __init__
    self._env_setup(initial_qpos=initial_qpos)
  File "C:\Users\jopdorp\Documents\dev\venv-tensorflow\lib\site-packages\gym\envs\robotics\fetch_env.py", line 172, in _env_setup
    self.sim.data.set_joint_qpos(name, value)
  File "wrappers.pxi", line 2536, in mujoco_py.cymj.PyMjData.set_joint_qpos
TypeError: 'numpy.int32' object is not iterable

**Comment by christopherhesse** [comment]
Sorry but this looks like a `mujoco_py` issue, please file it over on the `mujoco_py` repo: https://github.com/openai/mujoco-py
