### ISSUE TITLE
 'Monitor' object has no attribute 'enabled'

### ISSUE THREAD

**Issue by y12uc231** [openai/gym#969]
Traceback (most recent call last):
  File "reinforce.py", line 245, in <module>
    main()
  File "reinforce.py", line 239, in main
    reinfor.test(env, will_record=True)
  File "reinforce.py", line 143, in test
    env = wrappers.Monitor(env, './si' + str(eps), force = True)
  File "/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 15, in __init__
    super(Monitor, self).__init__(env)
  File "/anaconda3/lib/python3.6/site-packages/gym/core.py", line 247, in __init__
    self._warn_double_wrap()
  File "/anaconda3/lib/python3.6/site-packages/gym/core.py", line 258, in _warn_double_wrap
    raise error.DoubleWrapperError("Attempted to double wrap with Wrapper: {}".format(self.__class__.__name__))
gym.error.DoubleWrapperError: Attempted to double wrap with Wrapper: Monitor
Exception ignored in: <bound method Monitor.__del__ of <Monitor<Monitor<TimeLimit<LunarLander<LunarLander-v2>>>>>>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 234, in __del__
    self.close()
  File "/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 141, in close
    if not self.enabled:
AttributeError: 'Monitor' object has no attribute 'enabled'

Please help.

**Comment by srdjaner** [comment]
Did you find a solution for this?

**Comment by christopherhesse** [comment]
Are you wrapping your environment with monitor twice?

**Comment by christopherhesse** [comment]
Closing, looks like a double wrapped environment, please file a new issue if that is not correct.
